### ISSUE TITLE
Removing Link metadata of item while project is open causes crash

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/project-system#1042]
- Create a new Console App (.NET Core) project
- Add a source file outside of the project folder to the project, using "Add as Link".  Save the project file.  You will get an item like the following:

```xml
<Compile Include="..\..\Shared\Class1.cs">
  <Link>Class1.cs</Link>
</Compile>
```

- Open the project file in an external editor, and delete the `Link` metadata item, so you end up with an item like `<Compile Include="..\..\Shared\Class1.cs" />`
- Save the edited project file

EXPECTED: Visual Studio reloads the project file and applies changes
ACTUAL: The project system has encountered an error.  Failed to update the project tree.

```
Recoverable
System.AggregateException: One or more errors occurred. ---> Microsoft.VisualStudio.ProjectSystem.ProjectTreeCorruptionException: Failed to update the project tree. ---> System.NotSupportedException: Specified method is not supported.
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.HandleChangedItems(IProjectTree tree, IImmutableDictionary`2 projectData, IProjectChangeDescription change, String ruleName, String itemType, ConfiguredProjectExports configuredProjectExports, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.OnProjectSubscriptionChanged(IProjectTree originalTree, ConfiguredProjectExports configuredProjectExports, PhysicalProjectTreeInputData updateInput, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.OnProjectSubscriptionChanged(IProjectTree originalTree, ConfiguredProjectExports configuredProjectExports, PhysicalProjectTreeInputData updateInput, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.<>c__DisplayClass172_0.<ProjectSubscriptionService_ChangedAsync>b__0(IProjectVersionedValue`1 treeSnapshot, ConfiguredProjectExports configuredProjectExports, CancellationToken ct)
   at Microsoft.VisualStudio.ProjectSystem.ProjectTreeProviderBase.TreeUpdateSubmission.<UpdateTree>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.ProjectSystem.ProjectTreeProviderBase.<>c__DisplayClass95_0.<<Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.ProjectTreeProviderBase.<>c__DisplayClass102_0.<<SubmitTreeUpdateAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Microsoft.VisualStudio.ProjectSystem.ProjectTreeCorruptionException: Failed to update the project tree. ---> System.NotSupportedException: Specified method is not supported.
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.HandleChangedItems(IProjectTree tree, IImmutableDictionary`2 projectData, IProjectChangeDescription change, String ruleName, String itemType, ConfiguredProjectExports configuredProjectExports, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.OnProjectSubscriptionChanged(IProjectTree originalTree, ConfiguredProjectExports configuredProjectExports, PhysicalProjectTreeInputData updateInput, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.OnProjectSubscriptionChanged(IProjectTree originalTree, ConfiguredProjectExports configuredProjectExports, PhysicalProjectTreeInputData updateInput, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.<>c__DisplayClass172_0.<ProjectSubscriptionService_ChangedAsync>b__0(IProjectVersionedValue`1 treeSnapshot, ConfiguredProjectExports configuredProjectExports, CancellationToken ct)
   at Microsoft.VisualStudio.ProjectSystem.ProjectTreeProviderBase.TreeUpdateSubmission.<UpdateTree>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.ProjectSystem.ProjectTreeProviderBase.<>c__DisplayClass95_0.<<Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.ProjectTreeProviderBase.<>c__DisplayClass102_0.<<SubmitTreeUpdateAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
Project: C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\ConsoleApp2.csproj
PRIOR tree: 
ConsoleApp2 (visibility: visible, capabilities: {ProjectRoot}), FilePath: ""
    bin (visibility: invisible, capabilities: {FileSystemEntity Folder IncludeInProjectCandidate VisibleOnlyInShowAllFiles}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\bin\"
        Debug (visibility: visible, capabilities: {FileSystemEntity Folder IncludeInProjectCandidate}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\bin\Debug\"
            netcoreapp1.0 (visibility: visible, capabilities: {FileSystemEntity Folder IncludeInProjectCandidate}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\bin\Debug\netcoreapp1.0\"
    obj (visibility: invisible, capabilities: {FileSystemEntity Folder IncludeInProjectCandidate VisibleOnlyInShowAllFiles}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\obj\"
        Debug (visibility: visible, capabilities: {FileSystemEntity Folder IncludeInProjectCandidate}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\obj\Debug\"
            netcoreapp1.0 (visibility: visible, capabilities: {FileSystemEntity Folder IncludeInProjectCandidate}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\obj\Debug\netcoreapp1.0\"
                ConsoleApp2.AssemblyInfo.cs (visibility: visible, capabilities: {FileOnDisk FileSystemEntity IncludeInProjectCandidate}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\obj\Debug\netcoreapp1.0\ConsoleApp2.AssemblyInfo.cs"
                CoreCompileInputs.cache (visibility: visible, capabilities: {FileOnDisk FileSystemEntity IncludeInProjectCandidate}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\obj\Debug\netcoreapp1.0\CoreCompileInputs.cache"
                TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs (visibility: visible, capabilities: {FileOnDisk FileSystemEntity IncludeInProjectCandidate}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\obj\Debug\netcoreapp1.0\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs"
                TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs (visibility: visible, capabilities: {FileOnDisk FileSystemEntity IncludeInProjectCandidate}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\obj\Debug\netcoreapp1.0\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs"
                TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs (visibility: visible, capabilities: {FileOnDisk FileSystemEntity IncludeInProjectCandidate}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\obj\Debug\netcoreapp1.0\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs"
        project.assets.json (visibility: visible, capabilities: {FileOnDisk FileSystemEntity IncludeInProjectCandidate}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\obj\project.assets.json"
    Class1.cs (visibility: visible, capabilities: {FileOnDisk FileSystemEntity SourceFile}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\Shared\Class1.cs"
    ConsoleApp2.csproj (visibility: invisible, capabilities: {AlwaysInvisible FileOnDisk FileSystemEntity HiddenProjectSettingsFile IncludeInProjectCandidate}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\ConsoleApp2.csproj"
    Program.cs (visibility: visible, capabilities: {FileOnDisk FileSystemEntity SourceFile}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\Program.cs"
ACTUAL tree: 
ConsoleApp2 (visibility: visible, capabilities: {ProjectRoot}), FilePath: ""
    bin (visibility: invisible, capabilities: {FileSystemEntity Folder IncludeInProjectCandidate VisibleOnlyInShowAllFiles}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\bin\"
        Debug (visibility: visible, capabilities: {FileSystemEntity Folder IncludeInProjectCandidate}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\bin\Debug\"
            netcoreapp1.0 (visibility: visible, capabilities: {FileSystemEntity Folder IncludeInProjectCandidate}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\bin\Debug\netcoreapp1.0\"
    obj (visibility: invisible, capabilities: {FileSystemEntity Folder IncludeInProjectCandidate VisibleOnlyInShowAllFiles}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\obj\"
        Debug (visibility: visible, capabilities: {FileSystemEntity Folder IncludeInProjectCandidate}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\obj\Debug\"
            netcoreapp1.0 (visibility: visible, capabilities: {FileSystemEntity Folder IncludeInProjectCandidate}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\obj\Debug\netcoreapp1.0\"
                ConsoleApp2.AssemblyInfo.cs (visibility: visible, capabilities: {FileOnDisk FileSystemEntity IncludeInProjectCandidate}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\obj\Debug\netcoreapp1.0\ConsoleApp2.AssemblyInfo.cs"
                CoreCompileInputs.cache (visibility: visible, capabilities: {FileOnDisk FileSystemEntity IncludeInProjectCandidate}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\obj\Debug\netcoreapp1.0\CoreCompileInputs.cache"
                TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs (visibility: visible, capabilities: {FileOnDisk FileSystemEntity IncludeInProjectCandidate}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\obj\Debug\netcoreapp1.0\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs"
                TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs (visibility: visible, capabilities: {FileOnDisk FileSystemEntity IncludeInProjectCandidate}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\obj\Debug\netcoreapp1.0\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs"
                TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs (visibility: visible, capabilities: {FileOnDisk FileSystemEntity IncludeInProjectCandidate}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\obj\Debug\netcoreapp1.0\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs"
        project.assets.json (visibility: visible, capabilities: {FileOnDisk FileSystemEntity IncludeInProjectCandidate}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\obj\project.assets.json"
    Class1.cs (visibility: visible, capabilities: {FileOnDisk FileSystemEntity SourceFile}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\Shared\Class1.cs"
    ConsoleApp2.csproj (visibility: invisible, capabilities: {AlwaysInvisible FileOnDisk FileSystemEntity HiddenProjectSettingsFile IncludeInProjectCandidate}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\ConsoleApp2.csproj"
    Program.cs (visibility: visible, capabilities: {FileOnDisk FileSystemEntity SourceFile}), FilePath: "C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\Program.cs"
Inner exception:
System.NotSupportedException: Specified method is not supported.
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.HandleChangedItems(IProjectTree tree, IImmutableDictionary`2 projectData, IProjectChangeDescription change, String ruleName, String itemType, ConfiguredProjectExports configuredProjectExports, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.OnProjectSubscriptionChanged(IProjectTree originalTree, ConfiguredProjectExports configuredProjectExports, PhysicalProjectTreeInputData updateInput, CancellationToken cancellationToken)
<---
```

**Comment by srivatsn** [comment]
@lifengl @jviau @adrianvmsft - looks like a CPS issue?

**Comment by lifengl** [comment]
I am pretty sure that our code doesn't handle this change, because it doesn't happen without editing the file directly.  We don't support a file item outside the project folder without link metadata well, but should not crash.

Maybe more important is to ensure we don't crash when handling an unsupported change in this version, instead of this specific change in the RTM.  I am pretty sure this is not the only case.

Sent from my phone

On Dec 29, 2016, at 4:52 AM, Srivatsn Narayanan <notifications@github.com<mailto:notifications@github.com>> wrote:


@lifengl<https://github.com/lifengl> @jviau<https://github.com/jviau> @adrianvmsft<https://github.com/adrianvmsft> - looks like a CPS issue?

-

**Comment by tmat** [comment]
Happened to me when switching a git branch while having a solution open on the repo.

**Comment by lifengl** [comment]
I tried this scenario, and it does not crash VS, but is reported as a NFE error.  In RTM, showing any file outside of project cone without the link metadata is cut, so I don't think fixing it will reduce much value (as the editing the project to an unsupported way, and it is not a crash, but an error message box.  Basically, I don't think it meets the RTM bar.

**Comment by davkean** [comment]
Closing in lieu of https://devdiv.visualstudio.com/DevDiv/Managed%20Project%20System/_workItems?id=397521&fullScreen=false&_a=edit.

**Comment by davkean** [comment]
Reopening this as CPS won't fixed this.

**Comment by lifengl** [comment]
That has been fixed in 15.3.

Sent from my phone

On Mar 26, 2017, at 6:11 PM, David Kean <notifications@github.com<mailto:notifications@github.com>> wrote:


Reopened #1042<https://github.com/dotnet/roslyn-project-system/issues/1042>.

**Comment by srivatsn** [comment]
Verified that this doesn't crash anymore. With the link metadata the item shows up in the tree and removing it makes the file go away from the tree and VS is still standing.

**Comment by davkean** [comment]
This no longer occurs, files outside of the project cone are always considered as "linked items" now.
