### ISSUE TITLE
Attempting to delete an implicit reference display unintelligable error

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1250]
Targeting .NET Framework 4.5, attempt to delete System reference:

```
---------------------------
Microsoft Visual Studio
---------------------------
Cannot modify an evaluated object originating in an imported file "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.BeforeCommon.targets".
---------------------------
OK   
---------------------------
```

I think we should given an indication that these references are implicit (greyed out or different icon), and then not let you attempt to delete them.

**Comment by davkean** [comment]
Same if you attempt to remove the implict packages:

![image](https://cloud.githubusercontent.com/assets/1103906/22103095/e4d8f778-de8d-11e6-9ca1-0cfa478d82cd.png)

**Comment by abpiskunov** [comment]
Please open an issue in SDK to add a specific metadata so DependencyTree could differentiate between dependencies and have visual differences and functionality differences,

**Comment by srivatsn** [comment]
The implicit refs will now show up in the SDK node but I assume the same behavior will happen for them. This issue is not so much about the implicit refs but any refs outside the project file. We should give the same visual treatment for all such refs.

**Comment by abpiskunov** [comment]
this can be done. I could remove a flag "SupportsRemove" for implicit package references (sdks now) and Remove comand and Delete key would be disabled for them , when user right clicks on them. Another U1 workitem is to show slightly different icon for implicit packages/sdk.

**Comment by srivatsn** [comment]
This is a general issue though. If there's an assembly ref coming from a targets file, we'll still see this error. We'll basically need to tag all refs coming from targets files with the DoesNotSupportRemove flag.

**Comment by abpiskunov** [comment]
Yes, let's keep this issue opened, since my change fixes only packages and sdk. Other types of dependencies don't have metadata yet to differentiate them in the tree provider.

**Comment by davkean** [comment]
This is worse, it now asserts, I'm pulling this back in into 15.3:
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Cannot find reference to remove.



   at Microsoft.Report.Fail(String message)

   at Microsoft.Report.IfNot(Boolean condition, String message)

   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.DependenciesProjectTreeProvider.<RemoveAsync>d__26.MoveNext()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass4_0.<OutputAsyncCausalityEvents>b__0()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()

   at System.Runtime.CompilerServices.TaskAwaiter.<>c__DisplayClass11_0.<OutputWaitEtwEvents>b__0()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()

   at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.<>c.<.cctor>b__8_0(Object state)

   at Microsoft.VisualStudio.Threading.AsyncReaderWriterLock.NonConcurrentSynchronizationContext.<PostHelper>d__9.MoveNext()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass4_0.<OutputAsyncCausalityEvents>b__0()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()

   at System.Runtime.CompilerServices.TaskAwaiter.<>c__DisplayClass11_0.<OutputWaitEtwEvents>b__0()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()

   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)

   at System.Threading.Tasks.Task.FinishContinuations()

   at System.Threading.Tasks.Task.FinishStageThree()

   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)

   at System.Threading.SemaphoreSlim.TaskNode.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by abpiskunov** [comment]
This is bug in sdk - all implicit dependencies provided by sdk must have IsImplicitlyDefined=True metadata, otherwise how do we know that it is implicit? Dependencies already have logic to detect IsImplicitlyDefined metadata and hide Remove command. Assert is just to detect that, on user machine it would just ignore it and do nothing at the moment.   I will open issue in sdk.

**Comment by davkean** [comment]
I

**Comment by davkean** [comment]
Regardless, we can't expect all users to have this metadata applied to references in targets - this bug still exists.

**Comment by abpiskunov** [comment]
how do you know that reference is implicit?

**Comment by davkean** [comment]
Not sure I understand the question...

**Comment by abpiskunov** [comment]
if reference is implictly provided by some target and we can not remove it - how do you know that ? what do you expect the resolution of this bug to be? The only thing i see is better error dialog hinting why we can not remove reference

**Comment by davkean** [comment]
It doesn't have to be a target, it could just be statically defined in a targets file. If the project didn't define the item - don't let me delete it.

**Comment by davkean** [comment]
I suppose I don't undersatnd the point of the IsImplicitlyDefined metadata item - we already know if the project contains the item, why do we need special metadata to indicate that?

**Comment by abpiskunov** [comment]
i don't like to read xml everytime .. but it looks this is the only option. In case of removal we can read xml , since it is one time operation, but in case of adding a list of references to the snapshot , it would be too expensive , so to distinguish between implicit or not we have that metadata. Standard targets should know that and send it. This way we can mark implicit items with different icon  etc..
