### ISSUE TITLE
Changing the Build action of a file asserts with CPS dbg bits

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1314]
1. Select launchsettings.json
2. In properties, change content type from "None" -> "Content"

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Project file "c:\Users\davkean\Documents\Visual Studio 2017\Projects\ClassLibrary13\ClassLibrary13\ClassLibrary13.csproj" changed before it was checked out.



   at Microsoft.Report.Fail(String message)

   at Microsoft.Report.Fail(String message, Object[] args)

   at Microsoft.VisualStudio.ProjectSystem.ProjectLockService.AccessLockEnforcement.ProjectCollection_ProjectDirtied(String projectRootElementFullPath) in E:\CPS\src\Microsoft.VisualStudio.ProjectSystem.Implementation\ProjectLockService.cs:line 1055

   at Microsoft.VisualStudio.ProjectSystem.ProjectLockService.AccessLockEnforcement.ProjectXml_Changed(Object sender, ProjectXmlChangedEventArgs e) in E:\CPS\src\Microsoft.VisualStudio.ProjectSystem.Implementation\ProjectLockService.cs:line 1028

   at Microsoft.Build.Evaluation.ProjectCollection.OnProjectXmlChanged(ProjectXmlChangedEventArgs e)

   at Microsoft.Build.Evaluation.ProjectCollection.ProjectRootElementCache_ProjectRootElementDirtiedHandler(Object sender, ProjectXmlChangedEventArgs e)

  ......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by srivatsn** [comment]
Is there a bug on CPS here? If so can we dupe this to that bug?

**Comment by srivatsn** [comment]
Filed https://devdiv.visualstudio.com/DevDiv/_workitems?id=429302&fullScreen=false&_a=edit
