### ISSUE TITLE
Non Fatal error and Fault on duplicate package

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/project-system#1509]
-Copy the MultiTargetting folder from <internalshare>\public\Jinuj\TestCases\MultiTargetting 
- Open the solution file 
- you will see a non-fatal error followed by this 
![image](https://cloud.githubusercontent.com/assets/12449387/22768142/ea343bcc-ee34-11e6-86ea-ce818b95076e.png)

- log file copied in the same share
- The project is RC2 style so still has package references in the csproj.

**Build**
26208.d15rel

**Comment by davkean** [comment]
The duplicate issue is being tracked by https://github.com/dotnet/roslyn-project-system/issues/1213.

We should make this bug about the non-fatal Watson - I'm unsure if its the same cause (as it happens in different place)

**Comment by davkean** [comment]
@tmeschter Tom can you figure out how to get the non-fatal watson and then file a bug on it? And see it's replaced to the above dialog? Attaching a dialog causes the non-fatal to go away.

**Comment by tmeschter** [comment]
@davkean @jinujoseph I'm not able to reproduce the NFW or the dialog using the latest project-system bits. However, package restore seems to be failing with this callstack:

```
Error occurred while restoring NuGet packages: System.InvalidOperationException: The operation failed as details for project CoreCL could not be loaded.
   at NuGet.PackageManagement.VisualStudio.CpsPackageReferenceProject.GetPackageSpecsAsync(DependencyGraphCacheContext context)
   at NuGet.PackageManagement.DependencyGraphRestoreUtility.<GetSolutionRestoreSpec>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.DependencyGraphRestoreUtility.<IsRestoreRequiredAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestorePackageSpecProjectsAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<ExecuteAsync>d__15.MoveNext()
```

But I'm not sure if that's the problem, or if there's just something out-of-date with the project format. Any ideas?

**Comment by davkean** [comment]
That is a red herring and very likely this bug: https://github.com/NuGet/Home/issues/4577.

I was hitting the NFW all the time - what build do you have?

**Comment by tmeschter** [comment]
No longer meets the bar for 15.5. Moving out to 15.6.

**Comment by Pilchie** [comment]
I can't repro any failures here after adding configuration/platform info to the projects.
