### ISSUE TITLE
Visual Studio crash while restoring

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1646]
Don't have a repro, but VS crashed when I had the ProjectSystem.sln open:

```
Exception Info: System.ArgumentOutOfRangeException
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(System.ExceptionArgument, System.ExceptionResource)
   at System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Item(Int32)
   at System.Collections.ObjectModel.Collection`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Item(Int32)
   at System.Collections.ObjectModel.ObservableCollection`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveItem(Int32, Int32)
   at Microsoft.VisualStudio.Shell.TreeNavigation.GraphProvider.GraphContextResultsCollection.MergeCopy[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Collections.ObjectModel.ObservableCollection`1<System.__Canon>, System.Predicate`1<System.__Canon>)
   at Microsoft.VisualStudio.Shell.TreeNavigation.GraphProvider.GraphContextResultsCollection.SynchronizeResults()
   at Microsoft.VisualStudio.Shell.TreeNavigation.GraphProvider.GraphContextResultsCollection.GraphContextUpdated(System.Object, Microsoft.VisualStudio.Progression.GraphContextUpdatedEventArgs)
   at Microsoft.VisualStudio.Progression.GraphContext.OnGraphContextUpdated(Microsoft.VisualStudio.GraphModel.GraphUpdatedEventArgs)
   at Microsoft.VisualStudio.Progression.ContextSynchronizer.ApplyUndoUnits()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)


```

**Comment by abpiskunov** [comment]
Hm i was thinking if this could be Dependencies graph, however , during restore its unlikely that dependencies graph is updated, since it updates after user opens tree items. Could it be roslyn's graph nodes for classes and lang services updates during restore?

**Comment by davkean** [comment]
Going dupe it against: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/176978.
