### ISSUE TITLE
InvalidCastException when trying to Marshal DTE.Project across processes

### ISSUE THREAD

**Issue by prafullbhosale** [dotnet/project-system#1901]
This used to work in `26228.0` but is failing on `26329.4`

From: @BillHiebert 

We are trying to update our CI machines to the latest lab/vsuwpt build but our Apex integration tests are failing with an invalid cast exception at the highlighted call. The same code works fine against other project types (like WAP), and these tests run fine against dev15Rel drops. This is an Apex test so the code is relying on DCOM to marshal the object between the apex process and VS.  I took a quick look at the Roslyn project system code but I didn’t see anything obvious (I was thought maybe it was aggregating EnvDTE.Project now or something).  Any CPS changes around this?

```cs
        private EnvDTE.Project NavigateProject(EnvDTE.Project p, string projectFileName)
        {
            if (p.Object is EnvDTE80.SolutionFolder)
            {
                // Not a real project, but a solution folder.
                EnvDTE.ProjectItems items = p.ProjectItems;
                if (items != null)
                {
                    foreach (EnvDTE.ProjectItem item in items)
                    {
                        if (item.SubProject != null)
                        {
                            EnvDTE.Project theProject = NavigateProject(item.SubProject, projectFileName);
                            if (theProject != null)
                            {
                                return theProject;
                            }
                        }
                    }
                }
            }
```

#### Stacktrace:
```
System.StubHelpers.InterfaceMarshaler.ConvertToNative(Object objSrc, IntPtr itfMT, IntPtr classMT, Int32 flags)
EnvDTE.Project.get_Object()
Microsoft.VisualStudio.ProjectSystem.Web.IntegrationTests.BasicProjectCreationTest.NavigateProject(Project p, String projectFileName) in D:\dd\WTE\Main\test\ProjectSystem\Web.IntegrationTests\Tests\BasicProjectCreationTest.cs: line 147
Microsoft.VisualStudio.ProjectSystem.Web.IntegrationTests.BasicProjectCreationTest.FindProjectInSolution(String projectFileName) in D:\dd\WTE\Main\test\ProjectSystem\Web.IntegrationTests\Tests\BasicProjectCreationTest.cs: line 135
Microsoft.VisualStudio.ProjectSystem.Web.IntegrationTests.BasicProjectCreationTest.CreateProject(String templateName, String projectName, String projectPath, String templateParams, Boolean exclusive, Boolean waitForRestore, SolutionFolder solutionFolder) in D:\dd\WTE\Main\test\ProjectSystem\Web.IntegrationTests\Tests\BasicProjectCreationTest.cs: line 90
Microsoft.VisualStudio.ProjectSystem.Web.IntegrationTests.BasicProjectCreationTest.CreateNewProjectFromTemplate(String templateName, Boolean useSolutionFolderLayout, String templateParams, Boolean waitForRestore) in D:\dd\WTE\Main\test\ProjectSystem\Web.IntegrationTests\Tests\BasicProjectCreationTest.cs: line 31
Microsoft.VisualStudio.ProjectSystem.Web.IntegrationTests.BasicProjectTest.RunTest(String templateName, RunTestOptions options) in D:\dd\WTE\Main\test\ProjectSystem\Web.IntegrationTests\Tests\BasicProjectTest.cs: line 58
Microsoft.VisualStudio.ProjectSystem.Web.IntegrationTests.EmptyWebTests.EmptyWebOnFullFrameworkTest() in D:\dd\WTE\Main\test\ProjectSystem\Web.IntegrationTests\Tests\EmptyWebTests.cs: line 38
Microsoft.VisualStudio.Web.Common.TestServices.VisualStudioHostWebTest.TestAttributeValidateAndDeactivate() in D:\dd\WTE\Main\test\Common\TestServices\Apex\VisualStudioHostWebTest.cs: line 313
Microsoft.VisualStudio.Web.Common.TestServices.VisualStudioHostWebTest.DoHostTestCleanup() in D:\dd\WTE\Main\test\Common\TestServices\Apex\VisualStudioHostWebTest.cs: line 201
Microsoft.Test.Apex.ExternalProcessHostTest`2.TestCleanup() in F:\dd\src\omni\Apex\MsTestIntegration\ExternalProcessHostTest.cs: line 132
Microsoft.Test.Apex.VisualStudio.VisualStudioHostTest.TestCleanup() in F:\dd\src\omni\Apex\MsTestIntegration\VisualStudioHostTest.cs: line 171

```

cc @davkean, @basoundr

**Comment by basoundr** [comment]
The exception that gets thrown is: 
```System.InvalidCastException : "Specified cast is not valid."
   at System.StubHelpers.InterfaceMarshaler.ConvertToNative(Object objSrc, IntPtr itfMT, IntPtr classMT, Int32 flags)
   at EnvDTE.Project.get_Object()
   at ConsoleApp95.Program.Main(String[] args) in C:\Users\basoundr\documents\visual studio 2017\Projects\ConsoleApp95\ConsoleApp95\Program.cs:line 31
```
ConvertToNative is interesting because the VSProject object that was returned by CPS and the VSProject object that is being returned after my changes, are both managed objects. I tried adding the [ComVisible(true)] attribute to the new object to make it comvisible and that did not work either.

**Comment by davkean** [comment]
Are you saying that the VSProject in the secondary process when it did work is a managed object?

**Comment by srivatsn** [comment]
Keeping this open to resolve @davkean's question in #1932

**Comment by basoundr** [comment]
@davkean @srivatsn This object on the other process is a native wrapper around our implementation
