### ISSUE TITLE
VS crash with ObjectDisposedException 

### ISSUE THREAD

**Issue by mavasani** [dotnet/project-system#1908]
I got a VS crash with the following object disposed exception - I couldn't attach a debugger but a Watson was logged. Filing this bug in case it can be fixed with just the call stack

````
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at Microsoft.Verify.NotDisposed(Microsoft.IDisposableObservable, System.String)
   at Microsoft.VisualStudio.ProjectSystem.ProjectLockService.GetResourceAsync(Microsoft.VisualStudio.ProjectSystem.ConfiguredProject, System.Threading.CancellationToken)
   at Microsoft.VisualStudio.Threading.AsyncReaderWriterResourceLock`2+Helper+<GetResourceAsync>d__14[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.ProjectSystem.Properties.ProjectProperties+<GetEvaluatedPropertyValueAsync>d__7.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.ProjectSystem.PropertyPages.PageProperty+<GetValueAsync>d__18.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.ProjectSystem.PropertyPages.PageStringProperty+<GetValueAsStringAsync>d__6.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.ProjectSystem.PropertyPages.PageStringProperty+<GetValueAsync>d__7.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.ProjectSystem.VS.ProjectLockFileWatcher+<GetProjectLockFilePathAsync>d__12.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.ProjectSystem.VS.ProjectLockFileWatcher+<ProjectTree_ChangedAsync>d__11.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by srivatsn** [comment]
@abpiskunov is this the bug you recently fixed?

**Comment by abpiskunov** [comment]
no, my issue was similar exception in the dependency tree provider, not in ProjectLockFileWatcher

**Comment by BillHiebert** [comment]
This looks like a CPS issue.

**Comment by davkean** [comment]
This is https://github.com/dotnet/project-system/issues/1768.
