### ISSUE TITLE
DataSourceRegressionException: The ConfiguredProjectVersion has decremented, outside the context of an active project config change. 

### ISSUE THREAD

**Issue by tmat** [dotnet/project-system#1969]
=====================
4/11/2017 9:10:05 AM
Recoverable
System.AggregateException: One or more errors occurred. ---> Microsoft.VisualStudio.ProjectSystem.ProjectDataSources+DataSourceRegressionException: The ConfiguredProjectVersion has decremented, outside the context of an active project config change.  This is likely an error, and can lead to hangs.
   at Microsoft.VisualStudio.ProjectSystem.ProjectDataSources.CheckValidVersionProgression(IImmutableDictionary`2 oldDataSourceVersions, IImmutableDictionary`2 dataSourceVersions, Boolean unconfiguredProjectLevel)
   at Microsoft.VisualStudio.ProjectSystem.SyncLinkToLink`1.ProcessData(Boolean inline)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Microsoft.VisualStudio.ProjectSystem.ProjectDataSources+DataSourceRegressionException: The ConfiguredProjectVersion has decremented, outside the context of an active project config change.  This is likely an error, and can lead to hangs.
   at Microsoft.VisualStudio.ProjectSystem.ProjectDataSources.CheckValidVersionProgression(IImmutableDictionary`2 oldDataSourceVersions, IImmutableDictionary`2 dataSourceVersions, Boolean unconfiguredProjectLevel)
   at Microsoft.VisualStudio.ProjectSystem.SyncLinkToLink`1.ProcessData(Boolean inline)<---

===================
4/11/2017 9:10:08 AM
Crippling
System.AggregateException: One or more errors occurred. ---> Microsoft.VisualStudio.ProjectSystem.ProjectDataSources+DataSourceRegressionException: The ConfiguredProjectVersion has decremented, outside the context of an active project config change.  This is likely an error, and can lead to hangs.
   at Microsoft.VisualStudio.ProjectSystem.ProjectDataSources.CheckValidVersionProgression(IImmutableDictionary`2 oldDataSourceVersions, IImmutableDictionary`2 dataSourceVersions, Boolean unconfiguredProjectLevel)
   at Microsoft.VisualStudio.ProjectSystem.SyncLinkToLink`1.ProcessData(Boolean inline)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Microsoft.VisualStudio.ProjectSystem.ProjectDataSources+DataSourceRegressionException: The ConfiguredProjectVersion has decremented, outside the context of an active project config change.  This is likely an error, and can lead to hangs.
   at Microsoft.VisualStudio.ProjectSystem.ProjectDataSources.CheckValidVersionProgression(IImmutableDictionary`2 oldDataSourceVersions, IImmutableDictionary`2 dataSourceVersions, Boolean unconfiguredProjectLevel)
   at Microsoft.VisualStudio.ProjectSystem.SyncLinkToLink`1.ProcessData(Boolean inline)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )<---

===================

**Comment by davkean** [comment]
Can you add the exact build you are using?

**Comment by gusmanb** [comment]
If it helps, I had the same problem after upgrading a project from VS2015 to VS2017, recreating the project with VS2017 and adding all the code files solved the problem.

**Comment by srivatsn** [comment]
@lifengl does this look like a CPS issue?

**Comment by davkean** [comment]
My first assumption would be that it's the Dependency node - it's a pity that the exception doesn't include the data source's name. The stack really gives us nothing.

**Comment by srivatsn** [comment]
Seems to be similar to #1573 where @abpiskunov says the dependencies node is unlikely to cause this.

**Comment by srivatsn** [comment]
Trackign with #1573
