### ISSUE TITLE
Get multiple assertions unloading Roslyn.sln

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2037]
1. git clone https://github.com/jaredpar/roslyn
2. git checkout fix-correct
3. msbuild /t:Restore build\ToolsetPackages\BaseToolset.csproj
4. Open Roslyn.sln
5. Close Roslyn.sln

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
The project XML file "E:\roslyn\src\Compilers\Core\AnalyzerDriver\AnalyzerDriver.projitems" cannot be unloaded because at least one project "E:\roslyn\src\Features\Core\Portable\Features.csproj" is still loaded which references that project XML.
   at Microsoft.Report.Fail(String message)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.SharedProjectFilesPackage.SharedProjectFileVsProject.<<Microsoft-VisualStudio-Shell-Interop-IVsPersistDocData-Close>b__77_0>d.MoveNext() in E:\CPS\src\Microsoft.VisualStudio.ProjectSystem.VS.Implementation\Package\SharedProjects\SharedProjectFileVsProject.cs:line 314
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at Microsoft.VisualStudio.ProjectSystem.ProjectLockService.<>c__DisplayClass52_0.<Microsoft.VisualStudio.ProjectSystem.IProjectLockReleaser.OnCompleted>b__1() in E:\CPS\src\Microsoft.VisualStudio.ProjectSystem.Implementation\ProjectLockService.cs:line 310
   at Microsoft.VisualStudio.Threading.AsyncReaderWriterLock.Awaiter.<>c.<TryScheduleContinuationExecution>b__40_0(Object state)
   at Microsoft.VisualStudio.Threading.AsyncReaderWriterLock.NonConcurrentSynchronizationContext.<PostHelper>d__9.MoveNext()
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.VisualStudio.Threading.AsyncReaderWriterLock.NonConcurrentSynchronizationContext.PostHelper(SendOrPostCallback d, Object state)
   at Microsoft.VisualStudio.Threading.AsyncReaderWriterLock.NonConcurrentSynchronizationContext.<>c.<Post>b__5_0(Object s)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by davkean** [comment]
Closed in lieu of https://devdiv.visualstudio.com/DevDiv/Managed%20Project%20System/_workItems?id=489389&fullScreen=false&_a=edit.
