### ISSUE TITLE
Component designer does not display when targeting .NET Core/.NET Standard

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2100]
_From @JinShil on April 29, 2017 7:47_

.Net Standard 2.0 and .Net Core 2.0 have included APIs in `System.ComponentModel` for building and extending the Visual Studio designer (e.g `Component` class, `DesignerAttribute`, `TypeConverter`, etc..) 

However, if one tries to use these classes in the current release of Visual Studio 2017 to create designers for their classes, Visual Studio displays errors in the designer like

```c#
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Text;

namespace CoreDesignerTest
{
    public class Class1 : Component
    {
    }
}
```

In Visual Studio, right-click on the "Class1.cs" node and choose "View Designer".

> Could not load file or assembly 'System.ComponentModel.Primitives, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. 

With some hacking in my .config files, I can resolve the above error, but eventually Visual Studio fails to load the .Net Core assemblies with an "Invalid Format" error.

I'm assuming this is due to the fact that Visual Studio, being a .Net Framework-based application, is trying to load a .Net Core assembly into a .Net Framework application, and therefore failing.

My question is, with the coming release of .Net Core 2.0 and .Net Standard 2.0, will there also be an accompanying Visual Studio update that will provide the ability to create designers for .Net Core 2.0 and .Net Standard 2.0 classes?

_Copied from original issue: dotnet/corefx#19139_

**Comment by davkean** [comment]
_From @karelz on April 29, 2017 8:12_

If VS changes are needed (which is IMO likely), there will be accompanying VS update.

I wonder if this is more related to Desktop magic retargeting pack (or whatever we call it) -- @weshaggard @ericstj?

**Comment by davkean** [comment]
_From @danmosemsft on April 30, 2017 0:20_

@davkean

**Comment by davkean** [comment]
_From @weshaggard on May 1, 2017 17:13_

Eventually we will likely have VS designer support for .NET Core components but I don't expect that to come online in the next VS update. Most of the Component design is around WinForms and WPF support which is not a target for .NET Core (at least not at this time). 

The errors you are seeing are related to the fact that the inbox .NET Framework doesn't know about most of these .NET Core assembly identities so your assumption of the mixing between .NET Framework and .NET Core is the reason this scenario is broken.

**Comment by davkean** [comment]
_From @karelz on May 1, 2017 18:13_

Seems to be answered by @weshaggard, closing. Please let us know if you need more info (we can reopen again), thanks!

**Comment by danmosemsft** [comment]
@terrajobst will probably chat separately about designer story in Core. The 2.0 data designer does (just about) work today and it aligns with .NET Core goals.

**Comment by coderb** [comment]
i've got a winforms app that references a project library that is dual targeted to net452 and netstandard2.0 (via `<TargetFrameworks>netstandard2.0;net452</TargetFrameworks>` ) and the forms designer shows the exception page with the error:

`Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified. 
`

The referenced library has no winforms dependencies.

This seems like a bug in VS.

**Comment by terrajobst** [comment]
Have you tried changing this:

```xml
<TargetFrameworks>netstandard2.0;net452</TargetFrameworks>
```

to this:

```xml
<TargetFrameworks>net452;netstandard2.0</TargetFrameworks>
```

@davkean would know more but my understanding is that the pieces in VS that aren't aware of multi-targeting will use the first framework in that list.

**Comment by coderb** [comment]
@terrajobst haha... yeah, i tried that right after i wrote my comment.  didn't fix it :-(.

**Comment by terrajobst** [comment]
In that case my entire expertise can be summarized as 🤷‍♂️  😄 . Presumably, there is work left in the project system/MSBuild to light up the designers properly for that case then.

**Comment by Pilchie** [comment]
Oops, didn't mean to close this.

**Comment by w4mmp** [comment]
Hello,
This is the closest thing I have found that I believe relates to an issue I have when attempting to run a dotnet core 3.1 application.    After porting an existing Window Forms application to dotnet 3.1 I receive this when attempting to run the application:
G:\Ham Radio\ominaSDR\Hardware\Linux\dotnettest\mscc\Release\netcoreapp3.1>dotnet mscc.dll
Unhandled exception. System.Resources.MissingManifestResourceException: Could not find the resource "OmniaGUI.Main_form.resources" among the resources "mscc.Properties.Resources.resources" embedded in the assembly "mscc", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at System.Resources.ResourceManager.GetString(String name)
   at OmniaGUI.Main_form.InitializeComponent() in G:\Ham Radio\ominaSDR\Hardware\Linux\dotnettest\mscc\Main_Form.designer.cs:line 1403
   at OmniaGUI.Main_form..ctor() in G:\Ham Radio\ominaSDR\Hardware\Linux\dotnettest\mscc\Main_Form.cs:line 105
   at OmniaGUI.Program.Main() in G:\Ham Radio\ominaSDR\Hardware\Linux\dotnettest\mscc\Program.cs:line 20

Since I am 100% new to dotnet core,  it is most likely an issue with my port, but I am at a lost on how to correct the issue.
Regard,s
Ron

P.S.  I am not intentionally attempting to high jack this thread,  but really looks like a good place to start.  Please let me know if I should start new issue.

**Comment by davkean** [comment]
@w4mmp Start a new bug over http://github.com/microsoft/msbuild. This is likely related to the way we control how we embed resources files in the resulting binary based on the presence/non-presence of source files, ie the feature called out in https://github.com/microsoft/msbuild/issues/4488. It might not be working your case - post the project file as part of the bug.

**Comment by w4mmp** [comment]
Hello,
Thanks for getting back to me so quickly.  I will start a new issue in msbuild.
Cheers,
Ron

**Comment by tmeschter** [comment]
Current status:

I tried the following in class libraries targeting various versions of .NET Standard, .NET Core, and .NET on build 16.9.0 Preview 3.0 [30730.33.main]:

1. Create a C# class library.
2. Right-click on the project, choose Add | New Item..., and add a "Component Class" item.
3. Right-click on the newly-added "Component1.cs" class and choose "View Designer".

Results:

### .NET Standard 2.0

The designer "opens" with the white screen of death and the error "Unsupported type argument in custom attribute signature". Call stack:

```
at Microsoft.MetadataReader.SignatureUtil.GetTypeId(Type type)
at Microsoft.MetadataReader.MetadataOnlyModule.GetConstructorArguments(ConstructorInfo constructorInfo, Byte[] customAttributeBlob, Int32& index)
at Microsoft.MetadataReader.MetadataOnlyModule.LazyAttributeParse(Token token, ConstructorInfo constructorInfo, IList`1& constructorArguments, IList`1& namedArguments)
at Microsoft.MetadataReader.MetadataOnlyCustomAttributeData.get_ConstructorArguments()
at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUtil.ConstructAttribute(CustomAttributeData data)
at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUtil.GetCustomAttributes(ICustomAttributesDataProvider member, Type filter, CustomAttributesCache cache)
at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUtil.GetCustomAttributes(Type type, Type filter, Boolean inherit, CustomAttributesCache cache)
at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkType.GetCustomAttributes(Type filter, Boolean inherit)
at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkAttributeCollection.GetAttributes(Type type, Type filter)
at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkAttributeCollection.GetAttributes(MemberInfo member, Type filter)
at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkAttributeCollection.get_Attributes()
at Microsoft.VisualStudio.Design.VSDesignSurface.EnsureExtensions(IComponent component)
at Microsoft.VisualStudio.Design.VSDesignSurface.CreateInstance(Type type)
at System.ComponentModel.Design.DesignerHost.System.ComponentModel.Design.IDesignerHost.CreateComponent(Type componentType, String name)
at System.ComponentModel.Design.Serialization.DesignerSerializationManager.CreateInstance(Type type, ICollection arguments, String name, Boolean addToContainer)
at System.ComponentModel.Design.Serialization.DesignerSerializationManager.System.ComponentModel.Design.Serialization.IDesignerSerializationManager.CreateInstance(Type type, ICollection arguments, String name, Boolean addToContainer)
at System.ComponentModel.Design.Serialization.TypeCodeDomSerializer.Deserialize(IDesignerSerializationManager manager, CodeTypeDeclaration declaration)
at System.ComponentModel.Design.Serialization.CodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager manager)
at Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager serializationManager)
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager serializationManager)
at System.ComponentModel.Design.Serialization.BasicDesignerLoader.BeginLoad(IDesignerLoaderHost host) 

```


### .NET Standard 2.1

As with .NET Standard 2.0, you get the white screen of death but with a different error: "Value cannot be null. Parameter name: instance". Call stack:

```
at System.ComponentModel.TypeDescriptor.AddAttributes(Object instance, Attribute[] attributes)
at Microsoft.VisualStudio.Design.VSDesignSurface.CreateDesigner(IComponent component, Boolean rootDesigner)
at System.ComponentModel.Design.DesignerHost.AddToContainerPostProcess(IComponent component, String name, IContainer containerToAddTo)
at System.ComponentModel.Design.DesignerHost.PerformAdd(IComponent component, String name)
at System.ComponentModel.Design.DesignerHost.System.ComponentModel.Design.IDesignerHost.CreateComponent(Type componentType, String name)
at System.ComponentModel.Design.Serialization.DesignerSerializationManager.CreateInstance(Type type, ICollection arguments, String name, Boolean addToContainer)
at System.ComponentModel.Design.Serialization.DesignerSerializationManager.System.ComponentModel.Design.Serialization.IDesignerSerializationManager.CreateInstance(Type type, ICollection arguments, String name, Boolean addToContainer)
at System.ComponentModel.Design.Serialization.TypeCodeDomSerializer.Deserialize(IDesignerSerializationManager manager, CodeTypeDeclaration declaration)
at System.ComponentModel.Design.Serialization.CodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager manager)
at Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager serializationManager)
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager serializationManager)
at System.ComponentModel.Design.Serialization.BasicDesignerLoader.BeginLoad(IDesignerLoaderHost host)
```

### .NET Core 3.1

You get an "Opening the file..." dialog for a few seconds, and then nothing--the designer doesn't open at all.

### .NET 5

You get an "Opening the file..." dialog for a few seconds, and then nothing--the designer doesn't open at all.

**Comment by tmeschter** [comment]
I'm going to move this to dotnet/winforms as I don't think these problems have anything in particular to do with the project system.
