### ISSUE TITLE
Upgrade langversion codefix doesn't work for CPS projects

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#2137]
**Version Used**:  D15Rel IntPreview channel

**Steps to Reproduce**:

In a .NET Core project, write some code that uses a 7.1 feature like default literal.
I get a codefix for upgrading the project to use C# 7.1 or latest.
![image](https://cloud.githubusercontent.com/assets/20570/25813694/5eac04dc-33cf-11e7-92b9-68453b16ce80.png)

Invoking the codefix fail with this stack:

```
System.AggregateException : One or more errors occurred. ---> Unable to cast object of type 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectConfigProperties' to type 'VSLangProj80.CSharpProjectConfigurationProperties3'.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass18_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
---> (Inner Exception #0) System.InvalidCastException : Unable to cast object of type 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectConfigProperties' to type 'VSLangProj80.CSharpProjectConfigurationProperties3'.
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyParseOptionsChanged(ProjectId projectId,ParseOptions options)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace,ImmutableArray`1 operations,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(<Unknown Parameters>)<---

```

Looks like we are not implementing some legacy interface.

FYI @jcouv @jaredpar @Pilchie

**Comment by basoundr** [comment]
@jviau @lifengl We might have to do ComAggregation for this type as well. Something similar to how we did [VSProject](https://mseng.visualstudio.com/VSIDEProj/_git/VSIDEProj.CPS/commit/3320603f2b22270c738fa428e068f8bdc4ec9d9c?_a=compare&path=%2Fsrc%2FMicrosoft.VisualStudio.ProjectSystem.VS.Implementation%2FPackage%2FNodes%2FProjectNode.cs&gridItemType=2&mpath=%2Fsrc%2FMicrosoft.VisualStudio.ProjectSystem.VS.Implementation%2FPackage%2FNodes%2FProjectNode.cs&opath=%2Fsrc%2FMicrosoft.VisualStudio.ProjectSystem.VS.Implementation%2FPackage%2FNodes%2FProjectNode.cs&mversion=GC3320603f2b22270c738fa428e068f8bdc4ec9d9c&oversion=GCbd9c2b3542676f20f820b79491c65c409b760d73)
