### ISSUE TITLE
Integration tests fail inside Visual Studio with "There were no instances of Visual Studio 15.0 or later found that match the specified requirements"

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2315]
The integration tests now show up in Test Explorer, but they fail with:

```

Test Name:	ErrorLevelWarning
Test FullName:	Microsoft.VisualStudio.ProjectSystem.IntegrationTests.CSharpErrorListTests.ErrorLevelWarning (3226edaf75ef9851d396b2e1ce55408e25b35f52)
Test Source:	E:\project-system2\src\Microsoft.VisualStudio.ProjectSystem.IntegrationTests\CSharp\CSharpErrorListTests.cs : line 69
Test Outcome:	Failed
Test Duration:	0:00:00.001

Result StackTrace:	
at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstanceFactory.LocateVisualStudioInstance(ImmutableHashSet`1 requiredPackageIds)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstanceFactory.UpdateCurrentlyRunningInstance(ImmutableHashSet`1 requiredPackageIds, Boolean shouldStartNewInstance)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstanceFactory.GetNewOrUsedInstance(ImmutableHashSet`1 requiredPackageIds)
   at Microsoft.VisualStudio.ProjectSystem.IntegrationTests.AbstractIntegrationTest..ctor(String solutionName, String projectTemplate, VisualStudioInstanceFactory instanceFactory) in E:\project-system2\src\Microsoft.VisualStudio.ProjectSystem.IntegrationTests\Utilities\AbstractIntegrationTest.cs:line 29
   at Microsoft.VisualStudio.ProjectSystem.IntegrationTests.CSharpErrorListTests..ctor(VisualStudioInstanceFactory instanceFactory) in E:\project-system2\src\Microsoft.VisualStudio.ProjectSystem.IntegrationTests\CSharp\CSharpErrorListTests.cs:line 17
Result Message:	System.Exception : There were no instances of Visual Studio 15.0 or later found that match the specified requirements.

```

**Comment by srivatsn** [comment]
This what @tannergooding fixed over the weekend right? We need to update the package in this repo? @tannergooding - can you take care of that?

**Comment by tannergooding** [comment]
This needs to be merged first: https://github.com/dotnet/roslyn/pull/19830
