### ISSUE TITLE
OutputPath property is not implemented

### ISSUE THREAD

**Issue by ravipal** [dotnet/project-system#2376]
In the latest preview build (\\cpvsbuild\drops\VS\d15prerel\products\26601.04\channels\internal\Preview\bootstrappers\fixed\Enterprise), OutputPath property is not implemented on ASP .Net Core projects. Is this a known issue?

In Service Fabric ASP .net core projects, we try to read the OutputPath as shown below and it throw exception

DteProject.ConfigurationManager.ActiveConfiguration.Properties.Item("OutputPath").Value

Exception:
System.Runtime.InteropServices.COMException (0x80020009): The method or operation is not implemented.
   at EnvDTE.Property.get_Value()
   at Microsoft.VisualStudio.Azure.Fabric.ApplicationProject.Debugging.DebugParametersFactory.GetOutputPath(Hierarchy project, IServiceProvider serviceProvider) in E:\repo\SFTools\src\CSv2\Fabric.ApplicationProject\Debugging\DebugParametersFactory.cs:line 113

**Comment by srivatsn** [comment]
This had been fixed (https://github.com/dotnet/project-system/pull/2295) in D15Rel. It'll flow to d15prerel add soon.
