### ISSUE TITLE
Build verbosity regressed significantly

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2563]
Sync'd to latest in master, and my verbosity has regressed significantly:

```
  A subdirectory or file E:\project-system2\bin\Release\IntegrationTests\Roslyn\Vsixes already exists.
  "C:\Users\davkean\.nuget\packages\roslyntools.microsoft.vsixexpinstaller\0.4.0-beta\tools\VsixExpInstaller.exe"  -u -
  rootSuffix:RoslynDev -vsInstallDir:"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise" E:\project-sys
  tem2\bin\Release\IntegrationTests\Roslyn\Vsixes\Microsoft.VisualStudio.IntegrationTest.Setup.vsix
    Uninstalling local extension: 'C:\USERS\DAVKEAN\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_958A2F1DROSLYNDEV\EXTENSI
  ONS\OWIZPYMF.FL3\'
      The local extension was succesfully uninstalled.
  Done!
  "C:\Users\davkean\.nuget\packages\roslyntools.microsoft.vsixexpinstaller\0.4.0-beta\tools\VsixExpInstaller.exe"  -u -
  rootSuffix:RoslynDev -vsInstallDir:"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise" E:\project-sys
  tem2\bin\Release\IntegrationTests\Roslyn\Vsixes\Roslyn.VisualStudio.DiagnosticsWindow.vsix
    Uninstalling local extension: 'C:\USERS\DAVKEAN\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_958A2F1DROSLYNDEV\EXTENSI
  ONS\NI3SBEQY.WTT\'
      The local extension was succesfully uninstalled.
  Done!
  "C:\Users\davkean\.nuget\packages\roslyntools.microsoft.vsixexpinstaller\0.4.0-beta\tools\VsixExpInstaller.exe"  -u -
  rootSuffix:RoslynDev -vsInstallDir:"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise" E:\project-sys
  tem2\bin\Release\IntegrationTests\Roslyn\Vsixes\ExpressionEvaluatorPackage.vsix
    Uninstalling local extension: 'C:\USERS\DAVKEAN\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_958A2F1DROSLYNDEV\EXTENSI
  ONS\PVMX4SWZ.MGC\'
      The local extension was succesfully uninstalled. A global extension still exists: 'C:\PROGRAM FILES (X86)\MICROSO
  FT VISUAL STUDIO\PREVIEW\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\MANAGEDLANGUAGES\VBCSHARP\EXPRESSIONEVALUA
  TORS\'
  Done!
  "C:\Users\davkean\.nuget\packages\roslyntools.microsoft.vsixexpinstaller\0.4.0-beta\tools\VsixExpInstaller.exe"  -u -
  rootSuffix:RoslynDev -vsInstallDir:"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise" E:\project-sys
  tem2\bin\Release\IntegrationTests\Roslyn\Vsixes\Roslyn.VisualStudio.InteractiveComponents.vsix
    Uninstalling local extension: 'C:\USERS\DAVKEAN\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_958A2F1DROSLYNDEV\EXTENSI
  ONS\AYC3F3XV.1UN\'
  Exception: The local extension failed to uninstall.
  System.Exception: The local extension failed to uninstall.
     at VsixExpInstaller.Program.<>c__DisplayClass9_3.<Main>g__Uninstall8(IInstalledExtension installedExtension)
     at VsixExpInstaller.Program.<>c__DisplayClass9_2.<Main>g__RunProgram1()
     at VsixExpInstaller.Program.Main(String[] args)
  "C:\Users\davkean\.nuget\packages\roslyntools.microsoft.vsixexpinstaller\0.4.0-beta\tools\VsixExpInstaller.exe"  -u -
  rootSuffix:RoslynDev -vsInstallDir:"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise" E:\project-sys
  tem2\bin\Release\IntegrationTests\Roslyn\Vsixes\Roslyn.VisualStudio.Setup.Next.vsix
    Uninstalling local extension: 'C:\USERS\DAVKEAN\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_958A2F1DROSLYNDEV\EXTENSI
  ONS\0RY0KSX1.U1C\'
  Exception: The local extension failed to uninstall.
  System.Exception: The local extension failed to uninstall.
     at VsixExpInstaller.Program.<>c__DisplayClass9_3.<Main>g__Uninstall8(IInstalledExtension installedExtension)
     at VsixExpInstaller.Program.<>c__DisplayClass9_2.<Main>g__RunProgram1()
     at VsixExpInstaller.Program.Main(String[] args)
  "C:\Users\davkean\.nuget\packages\roslyntools.microsoft.vsixexpinstaller\0.4.0-beta\tools\VsixExpInstaller.exe"  -u -
  rootSuffix:RoslynDev -vsInstallDir:"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise" E:\project-sys
  tem2\bin\Release\IntegrationTests\Roslyn\Vsixes\Roslyn.VisualStudio.Setup.vsix
    Uninstalling local extension: 'C:\USERS\DAVKEAN\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_958A2F1DROSLYNDEV\EXTENSI
  ONS\JXOCXVYA.VZI\'
  Exception: The local extension failed to uninstall.
  System.Exception: The local extension failed to uninstall.
     at VsixExpInstaller.Program.<>c__DisplayClass9_3.<Main>g__Uninstall8(IInstalledExtension installedExtension)
     at VsixExpInstaller.Program.<>c__DisplayClass9_2.<Main>g__RunProgram1()
     at VsixExpInstaller.Program.Main(String[] args)
  "C:\Users\davkean\.nuget\packages\roslyntools.microsoft.vsixexpinstaller\0.4.0-beta\tools\VsixExpInstaller.exe"  -u -
  rootSuffix:RoslynDev -vsInstallDir:"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise" E:\project-sys
  tem2\bin\Release\IntegrationTests\Roslyn\Vsixes\Roslyn.Compilers.Extension.vsix
    Uninstalling local extension: 'C:\USERS\DAVKEAN\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_958A2F1DROSLYNDEV\EXTENSI
  ONS\IIS1TVQL.4XW\'
  Exception: The local extension failed to uninstall.
  System.Exception: The local extension failed to uninstall.
     at VsixExpInstaller.Program.<>c__DisplayClass9_3.<Main>g__Uninstall8(IInstalledExtension installedExtension)
     at VsixExpInstaller.Program.<>c__DisplayClass9_2.<Main>g__RunProgram1()
     at VsixExpInstaller.Program.Main(String[] args)
  "C:\Users\davkean\.nuget\packages\roslyntools.microsoft.vsixexpinstaller\0.4.0-beta\tools\VsixExpInstaller.exe"  -roo
  tSuffix:RoslynDev -vsInstallDir:"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise" E:\project-system
  2\bin\Release\IntegrationTests\Roslyn\Vsixes\Roslyn.Compilers.Extension.vsix
    Updating local extension (C:\USERS\DAVKEAN\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_958A2F1DROSLYNDEV\EXTENSIONS\T
  NCZFK4G.VEY\) to 'E:\project-system2\bin\Release\IntegrationTests\Roslyn\Vsixes\Roslyn.Compilers.Extension.vsix'
      The local extension was succesfully uninstalled.
      The extension was succesfully installed locally: 'C:\USERS\DAVKEAN\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_958A
  2F1DROSLYNDEV\EXTENSIONS\LGZV5IEY.VJS\'
  Done!
  "C:\Users\davkean\.nuget\packages\roslyntools.microsoft.vsixexpinstaller\0.4.0-beta\tools\VsixExpInstaller.exe"  -roo
  tSuffix:RoslynDev -vsInstallDir:"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise" E:\project-system
  2\bin\Release\IntegrationTests\Roslyn\Vsixes\Roslyn.VisualStudio.Setup.vsix
    Updating local extension (C:\USERS\DAVKEAN\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_958A2F1DROSLYNDEV\EXTENSIONS\Z
  UYJLR3M.0QP\) to 'E:\project-system2\bin\Release\IntegrationTests\Roslyn\Vsixes\Roslyn.VisualStudio.Setup.vsix'
  Exception: The local extension failed to uninstall.
  System.Exception: The local extension failed to uninstall.
     at VsixExpInstaller.Program.<>c__DisplayClass9_3.<Main>g__Uninstall8(IInstalledExtension installedExtension)
     at VsixExpInstaller.Program.<>c__DisplayClass9_2.<Main>g__RunProgram1()
     at VsixExpInstaller.Program.Main(String[] args)
E:\project-system2\src\DeployIntegrationDependencies\DeployIntegrationDependencies.csproj(81,5): error MSB3073: The com
mand ""C:\Users\davkean\.nuget\packages\roslyntools.microsoft.vsixexpinstaller\0.4.0-beta\tools\VsixExpInstaller.exe" -
rootSuffix:RoslynDev -vsInstallDir:"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise" E:\project-syste
m2\bin\Release\IntegrationTests\Roslyn\Vsixes\Roslyn.VisualStudio.Setup.vsix" exited with code 2.

Build failed, for full log see E:\project-system2\bin\Release\Logs\Build.log.
```

There used to be only a single line of text per build project by default, these integration tests are logging significantly more than that.

**Comment by davkean** [comment]
tag @jmarolf

**Comment by jmarolf** [comment]
@tannergooding how do we suppress output of `VsixExpInstaller`?

**Comment by tannergooding** [comment]
@jmarolf, modify the sources to support a quiet mode or modify the Exec statement to suppress/swallow the output (not sure if possible).

Realistically, we shouldn't be doing this on build from the command line unless a switch has been passed and we shouldn't do this from within VS unless we are explicitly running one of the integration tests (otherwise the build will stay 'regressed').

**Comment by davkean** [comment]
As far as I can see we didn't resolve this - but instead just hid it behind a switch?

**Comment by jmarolf** [comment]
Sorry, I'll reopen this.  We need to completely blow away your hive like roslyn does so installation does not fail.

**Comment by davkean** [comment]
Ah, that will break any other extensions that I've installed such as CPS. Why do we have to do that?

**Comment by davkean** [comment]
And settings, right?

**Comment by jmarolf** [comment]
There are bugs in the VSSDK that make VSIX deployment unreliable.  I think the fix for this is to document a one-time setup argument such as `build.cmd  /integration-test-setup` which installs that required vsixes and  `build.cmd  /integration-test-setup-force` which installs the required vsixes and blows away your hive.  This way the developer can choose what they want to do.
