### ISSUE TITLE
Command-line build fails in master

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2565]
Sync'd latest to master, and my build fails with:

```
  Exception: The local extension failed to uninstall.
  System.Exception: The local extension failed to uninstall.
     at VsixExpInstaller.Program.<>c__DisplayClass9_3.<Main>g__Uninstall8(IInstalledExtension installedExtension)
     at VsixExpInstaller.Program.<>c__DisplayClass9_2.<Main>g__RunProgram1()
     at VsixExpInstaller.Program.Main(String[] args)
  "C:\Users\davkean\.nuget\packages\roslyntools.microsoft.vsixexpinstaller\0.4.0-beta\tools\VsixExpInstaller.exe"  -u -
  rootSuffix:RoslynDev -vsInstallDir:"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise" E:\project-sys
  tem2\bin\Release\IntegrationTests\Roslyn\Vsixes\Roslyn.VisualStudio.Setup.vsix
    Uninstalling local extension: 'C:\USERS\DAVKEAN\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_958A2F1DROSLYNDEV\EXTENSI
  ONS\JXOCXVYA.VZI\'
  Exception: The local extension failed to uninstall.
  System.Exception: The local extension failed to uninstall.
     at VsixExpInstaller.Program.<>c__DisplayClass9_3.<Main>g__Uninstall8(IInstalledExtension installedExtension)
     at VsixExpInstaller.Program.<>c__DisplayClass9_2.<Main>g__RunProgram1()
     at VsixExpInstaller.Program.Main(String[] args)
  "C:\Users\davkean\.nuget\packages\roslyntools.microsoft.vsixexpinstaller\0.4.0-beta\tools\VsixExpInstaller.exe"  -u -
  rootSuffix:RoslynDev -vsInstallDir:"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise" E:\project-sys
  tem2\bin\Release\IntegrationTests\Roslyn\Vsixes\Roslyn.Compilers.Extension.vsix
    Uninstalling local extension: 'C:\USERS\DAVKEAN\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_958A2F1DROSLYNDEV\EXTENSI
  ONS\IIS1TVQL.4XW\'
  Exception: The local extension failed to uninstall.
  System.Exception: The local extension failed to uninstall.
     at VsixExpInstaller.Program.<>c__DisplayClass9_3.<Main>g__Uninstall8(IInstalledExtension installedExtension)
     at VsixExpInstaller.Program.<>c__DisplayClass9_2.<Main>g__RunProgram1()
     at VsixExpInstaller.Program.Main(String[] args)
  "C:\Users\davkean\.nuget\packages\roslyntools.microsoft.vsixexpinstaller\0.4.0-beta\tools\VsixExpInstaller.exe"  -roo
  tSuffix:RoslynDev -vsInstallDir:"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise" E:\project-system
  2\bin\Release\IntegrationTests\Roslyn\Vsixes\Roslyn.Compilers.Extension.vsix
    Updating local extension (C:\USERS\DAVKEAN\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_958A2F1DROSLYNDEV\EXTENSIONS\T
  NCZFK4G.VEY\) to 'E:\project-system2\bin\Release\IntegrationTests\Roslyn\Vsixes\Roslyn.Compilers.Extension.vsix'
      The local extension was succesfully uninstalled.
      The extension was succesfully installed locally: 'C:\USERS\DAVKEAN\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_958A
  2F1DROSLYNDEV\EXTENSIONS\LGZV5IEY.VJS\'
  Done!
  "C:\Users\davkean\.nuget\packages\roslyntools.microsoft.vsixexpinstaller\0.4.0-beta\tools\VsixExpInstaller.exe"  -roo
  tSuffix:RoslynDev -vsInstallDir:"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise" E:\project-system
  2\bin\Release\IntegrationTests\Roslyn\Vsixes\Roslyn.VisualStudio.Setup.vsix
    Updating local extension (C:\USERS\DAVKEAN\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_958A2F1DROSLYNDEV\EXTENSIONS\Z
  UYJLR3M.0QP\) to 'E:\project-system2\bin\Release\IntegrationTests\Roslyn\Vsixes\Roslyn.VisualStudio.Setup.vsix'
  Exception: The local extension failed to uninstall.
  System.Exception: The local extension failed to uninstall.
     at VsixExpInstaller.Program.<>c__DisplayClass9_3.<Main>g__Uninstall8(IInstalledExtension installedExtension)
     at VsixExpInstaller.Program.<>c__DisplayClass9_2.<Main>g__RunProgram1()
     at VsixExpInstaller.Program.Main(String[] args)
E:\project-system2\src\DeployIntegrationDependencies\DeployIntegrationDependencies.csproj(81,5): error MSB3073: The com
mand ""C:\Users\davkean\.nuget\packages\roslyntools.microsoft.vsixexpinstaller\0.4.0-beta\tools\VsixExpInstaller.exe" -
rootSuffix:RoslynDev -vsInstallDir:"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise" E:\project-syste
m2\bin\Release\IntegrationTests\Roslyn\Vsixes\Roslyn.VisualStudio.Setup.vsix" exited with code 2.

Build failed, for full log see E:\project-system2\bin\Release\Logs\Build.log.

```

Not entirely sure what I'm supposed to do to resolve this.

**Comment by davkean** [comment]
tag @jmarolf

**Comment by jmarolf** [comment]
roslyn extensions aren't installing.  @tannergooding tracked down a similar issue in roslyn.  @tannergooding what was the resolution on that?
