### ISSUE TITLE
'dimensionValuesMap' must contain at least one element. System.ArgumentException 

### ISSUE THREAD

**Issue by piotroko** [dotnet/project-system#2604]
While opening a project from https://github.com/piotrpMSFT/peaky.xunit repository I got this error:

```
=====================
7/12/2017 8:31:15 PM
Recoverable
System.ArgumentException: 'dimensionValuesMap' must contain at least one element.
Parameter name: dimensionValuesMap
   at Microsoft.Requires.NotNullOrEmpty(IEnumerable values, String parameterName)
   at Microsoft.VisualStudio.ProjectSystem.ProjectConfigurationsServiceBase.CreateConfigurations(ImmutableArray`1 orderedDimensionNames, ImmutableDictionary`2 dimensionValuesMap)
   at Microsoft.VisualStudio.ProjectSystem.DeclaredDimensionsProjectConfigurationsService.<CalculateKnownProjectConfigurationsAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectCache`1.<GetValueAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.ProjectConfigurationsServiceBase.<GetKnownProjectConfigurationsAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.DefaultingProjectConfigurationsServiceBase.<GetProjectConfigurationAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.VSUnconfiguredProjectIntegrationService.<GetActiveProjectConfigurationAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.VSUnconfiguredProjectIntegrationService.<RefreshActiveProjectConfigurationAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.CrossTarget.CrossTargetSubscriptionHostBase.<>c__DisplayClass23_0.<<UpdateProjectContextAsync>b__0>d.MoveNext()
```

**Comment by davkean** [comment]
Known. This is occurring because you are missing configurations, we made a breaking change between 15.2 -> 15.3 for projects that don't pull in the SDK. You need to define configurations: https://github.com/dotnet/project-system/blob/master/docs/configurations.md.

The actual crash due to having no configurations is fixed in 15.5.

**Comment by bgever** [comment]
Thanks for reference @davkean. Adding the configurations fixed the problem for me with Visual Studio 2017 Update 3 (15.3.2).

Other symptoms I saw:
- Opening the SLN shows a popup window with the above error, and then that VS is recovering from a "non-fatal crash".
- Affected projects do not show the Build/Rebuild/Clean/Publish options in their context menu.
  *(handy to spot the troublemakers!)*
- When opening the Properties page for the project shows the same error message.

I guess I belong to that 1%. 😉

**Comment by davkean** [comment]
It's only for manually created projects that don't inherit the SDK.

**Comment by bgever** [comment]
The problem happened with legacy net461 (`<TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>`) libraries included in a netcoreapp1.1 project (with other netstandard1.4/1.6) targeting net461 (full framework). Those legacy net461 projects were created with ToolsVersion 12.0 and 15.0.

**Comment by monty241** [comment]
It seems that this error also causes Visual Studio on build to skip child projects of the project with the wrong configuration for building. Running msbuild as 

msbuild sol.sln /p:Configuration=Release /p:Platform="Any CPU"

works fine.

In our case, we've recently introduced build types iPhone and iPhoneSimulator which were not listed in the traditional project file of the master project.

I can imagine other users switch to 17.3 too for better Apple support and experiencing this issue too.

**Comment by MelbourneDeveloper** [comment]
I have a project that runs fine in Visual Studio 2015, but I can't open it in Visual Studio 2017. This appears to be a bug in Visual Studio 2017. The error comes up in a message box when I open the project, and it also comes up when I right click on the project and go to properties. This is an ASP.Net project. Also, when I right click on the project after loading it, I don't see "Set As Startup Project" so I literally can't run the project. However, I can compile it.

**Comment by Algorithman** [comment]
Thanks for the solution, but since this whole property stuff is quite new, can you please add a sample project file? (old->new)
The configurations.md just tells to exchange them, but that's not working for me at all.

**Comment by davkean** [comment]
@Algorithman Most projects opening in the new project system start as .NET Core/.NET Standard projects. File -> New -> Visual C# -> Class Library (.NET Standard).

**Comment by mhutch** [comment]
@davkean when the configurations come from the SDK, presumably this could happen if the SDK was not resolved?

**Comment by davkean** [comment]
Yes, that is possible. Even though we fixed this particular error, I'm not happy where we landed with errors around this when we can't find a config - I've got a bug open against CPS to fix the experience.
