### ISSUE TITLE
Deleting a file in SDK-style project causes non-fatal error

### ISSUE THREAD

**Issue by cartermp** [dotnet/project-system#2727]
1. `dotnet new console -lang F#`
2. Load into VS after packages restore.
3. Add a few F# file.
4. Delete that file.

**Expected:** File deleted with no issue.

**Actual:** File deleted, but VS encounters a non-fatal error.  Log here:

```
=====================
8/23/2017 10:52:24 AM
Recoverable
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: newMkDoc
   at Microsoft.Requires.FailRange(String parameterName, String message)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass478_0.<<TransferItem>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously(Func`1 asyncAction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass558_0.<HrInvoke>b__0()
   at Microsoft.VisualStudio.ProjectSystem.VS.HResult.<>c__DisplayClass36_0.<Invoke>b__0()
   at Microsoft.VisualStudio.ProjectSystem.VS.HResult.Invoke(Func`1 action, IServiceProvider vsShellServiceProvider, IProjectFaultHandlerService projectFaultHandlerService, UnconfiguredProject project)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
===================
```

I can repro this with a Library and MVC templates as well.

**Comment by davkean** [comment]
Closed in lieu of https://devdiv.visualstudio.com/DevDiv/Managed%20Project%20System/_workItems?id=486522&fullScreen=false&_a=edit.

**Comment by tmat** [comment]
Reopening since I just hit this while working in Roslyn.sln. The linked AzDO bug is F# specific, but this happens in C# project.

**Comment by davkean** [comment]
I reopened the F# bug, it's a language service issue.

**Comment by davkean** [comment]
Oh, misread - let me find a home for this.

**Comment by davkean** [comment]
@tmat What was your repro?

**Comment by KevinRansom** [comment]
Lol ... I was about to query this too.

**Comment by davkean** [comment]
Based on @lifengl comments in https://devdiv.visualstudio.com/DevDiv/_workitems/edit/486522?fullScreen=false:

> It looks like what went wrong is inside those frames.  When the document is closed in the project, it seems like the Workspace.OnDocumentClosed will think the file is a shared or linked item, and transfer the document to the new owner.  It appears that it tried to transfer the item back to the project where this document is just deleted.  This sounds wrong somewhere inside the language service code.  Not sure why this only happens for F#.

```
  Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNodeWrapper.TransferItem(string pszMkDocumentOld, string pszMkDocumentNew, Microsoft.VisualStudio.Shell.Interop.IVsWindowFrame punkWindowFrame) Line 190 C# Symbols loaded.
  [Native to Managed Transition]  Annotated Frame
  [Managed to Native Transition]  Annotated Frame
  Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.SetDocumentContext(Microsoft.CodeAnalysis.DocumentId documentId) Unknown No symbols loaded.
  Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Workspace.OnDocumentClosed(Microsoft.CodeAnalysis.DocumentId documentId, Microsoft.CodeAnalysis.TextLoader reloader, bool updateActiveContext) Unknown No symbols loaded.
```

This looks like it might be a Roslyn bug, its asking to transfer an item that doesn't exist and we're validating the moniker and throwing when we can't find the associated file.

**Comment by tmat** [comment]
@jasonmalinowski FYI

**Comment by jasonmalinowski** [comment]
This bug predates the 16.0 rewrite, it's still happening?

**Comment by jasonmalinowski** [comment]
(there's so many old bugs being duped I'm confused...)

**Comment by davkean** [comment]
Bear in mind that we only just recently made "shared projects" actually work correctly, so this may have resulted in bugs like this to be raised.
