### ISSUE TITLE
Error while building in Roslyn.sln

### ISSUE THREAD

**Issue by tmat** [dotnet/project-system#3056]
```
---------------------------
Microsoft Visual Studio
---------------------------
The project system has encountered an error.

Build target stack was corrupted and contain other unfinished targets. Expect: '_GetProjectReferenceTargetFrameworkProperties', Actual: 'ResolveProjectReferences'.

A diagnostic log has been written to the following location: "C:\Users\...\AppData\Local\Temp\VsProjectFault_7abaeedc-0ada-451c-855f-0f3f28ac6119.failure.txt".

---------------------------
OK   
---------------------------
```

log:

```
=====================
12/14/2017 11:17:51 AM
Recoverable
System.InvalidOperationException: Build target stack was corrupted and contain other unfinished targets. Expect: '_GetProjectReferenceTargetFrameworkProperties', Actual: 'ResolveProjectReferences'.
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
===================
12/14/2017 11:17:53 AM
Recoverable
System.InvalidOperationException: Build target stack was corrupted and contain other unfinished targets. Expect: 'ResolveProjectReferences', Actual: 'GetCopyToOutputDirectoryItems'.
===================
12/14/2017 11:17:53 AM
Recoverable
System.InvalidOperationException: Build target stack was corrupted and contain other unfinished targets. Expect: 'DispatchToInnerBuilds', Actual: 'ResolveProjectReferences'.
===================
12/14/2017 11:18:00 AM
Recoverable
System.InvalidOperationException: Build target stack was corrupted and contain other unfinished targets. Expect: '_GetProjectReferenceTargetFrameworkProperties', Actual: 'ResolveProjectReferences'.
===================
12/14/2017 11:18:01 AM
Recoverable
System.InvalidOperationException: Build target stack was corrupted and contain other unfinished targets. Expect: 'ResolveProjectReferences', Actual: 'GetCopyToOutputDirectoryItems'.
===================
12/14/2017 11:18:12 AM
Recoverable
System.InvalidOperationException: Build target stack was corrupted and contain other unfinished targets. Expect: '_GetProjectReferenceTargetFrameworkProperties', Actual: 'ResolveProjectReferences'.
===================
12/14/2017 11:18:19 AM
Recoverable
System.InvalidOperationException: Build target stack was corrupted and contain other unfinished targets. Expect: 'ResolveProjectReferences', Actual: 'GetCopyToOutputDirectoryItems'.
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
===================
```

**Comment by davkean** [comment]
Thanks - this is fixed in recent builds.

**Comment by tmat** [comment]
More recent than 27211.1.d15.6?

**Comment by davkean** [comment]
It was fixed [6 days ago](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/531370) and insert a couple of days later. Ping @adrianvmsft to figure exact build.

**Comment by tmat** [comment]
OK. Cool.
