### ISSUE TITLE
Create a shared project causes a project fault in the build-up-to-date

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3096]
1. Create new C# Shared Project:

=====================
01/04/18 11:12:29 AM
Recoverable
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.ProjectSystem.UpToDate.BuildUpToDateCheck.Initialize() in E:\project-system2\src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\UpToDate\BuildUpToDateCheck.cs:line 110
   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposed.EnsureInitialized(Boolean allowInitializing)
   at Microsoft.VisualStudio.ProjectSystem.UpToDate.BuildUpToDateCheck.Load() in E:\project-system2\src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\UpToDate\BuildUpToDateCheck.cs:line 105
   at Microsoft.VisualStudio.ProjectSystem.ConfiguredProjectImpl.<>c__DisplayClass108_2.<<InitializeAsync>b__6>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.<>c__DisplayClass28_1.<<Fork>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.ProjectSystem.UpToDate.BuildUpToDateCheck.Initialize() in E:\project-system2\src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\UpToDate\BuildUpToDateCheck.cs:line 110
   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposed.EnsureInitialized(Boolean allowInitializing)
   at Microsoft.VisualStudio.ProjectSystem.UpToDate.BuildUpToDateCheck.Load() in E:\project-system2\src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\UpToDate\BuildUpToDateCheck.cs:line 105
   at Microsoft.VisualStudio.ProjectSystem.ConfiguredProjectImpl.<>c__DisplayClass108_2.<<InitializeAsync>b__6>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.<>c__DisplayClass28_1.<<Fork>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)<---

===================

**Comment by davkean** [comment]
Looks like this might have been regressed just recently @panopticoncentral? 

We probably shouldn't be loading the up-to-date in shared projects. 

// cc @Pilchie
