### ISSUE TITLE
Editing csproj with invalid SDKs results in multiple error dialogs

### ISSUE THREAD

**Issue by dasMulli** [dotnet/project-system#3240]
Not sure if this is a project system or VS issue.

Steps to reproduce:
* Use VS 15.6 Preview 4
* Open a valid csproj file.
* Add or edit an SDK specification that can't be resolved via NuGet or file system.
* Multiple warning dialogs pop up
* Edit the csproj to be valid again
* Still a few dialogs pop up

Expected:
Warn only once when the project becomes unloadable. Don't warn when it is valid again.

![vssdkloadissue-720p](https://user-images.githubusercontent.com/6129250/36077138-1153fd6a-0f67-11e8-8e63-e1df215a3ab8.gif)

**Comment by Pilchie** [comment]
Tagging @jviau and @jeffkl

**Comment by Pilchie** [comment]
Ping @jviau - is this an expected outcome of the reloading changes you made?  @sharwell also noticed that if he edited a shared .targets file, he would get a dialog per project (152 in the case of Roslyn.sln).

Is this something that should be looked at more in CPS?

**Comment by jviau** [comment]
To be honest, I have never seen the `<Sdk>` tag before. Does it get translated to an import?

**Comment by jeffkl** [comment]
Yes its just a better way of specifying a version

Identitical:

```xml
<Project Sdk="My.Custom.Sdk/1.0.0">
</Project>
```

```xml
<Project>
  <Sdk Name="My.Custom.Sdk" Version="1.0.0" />
</Project>
```

More info is here: https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk

**Comment by jviau** [comment]
Debugging this it appears `Sdk` elements do not respect `IgnoreMissingImports`/`IgnoreEmptyImports`/`IgnoreInvalidImports`. @jeffkl do you think it should respect those flags?

If not, my only other idea is to veto changes to the Sdk and ask the user to reload the project.

@sharwell do you have an example of the edit you did to a targets file that caused so many dialogs? We should display only 1 dialog, if we are displaying multiple that is pretty bad.

**Comment by jeffkl** [comment]
That seems odd to me.  The `<Sdk />` element just adds `<Import />` elements.  Are you seeing a different behavior?

**Comment by jviau** [comment]
Yes, CPS projects include all 3 of those flags, but `ReevaluateIfNecessary()` throws with something along the lines of SDK not found exception.

**Comment by jeffkl** [comment]
Yeah definitely.  We just discussed this and it makes total sense for us to not throw an `InvalidProjectFileException` if the SDK can't be found.  The project will get unloaded since "expected imports are not found" from what we can tell.  Let me code something up and see if we can get it in 15.6

fyi @andygerlicher

**Comment by jviau** [comment]
The full exception is:
```
The SDK 'Broken/1.0' specified could not be found.  C:\Users\javia\source\repos\ConsoleApp6\ConsoleApp6\ConsoleApp6.csproj 
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly, ISdkResolverService sdkResolverService, Int32 submissionId)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary()
   at Microsoft.VisualStudio.ProjectSystem.ProjectLockService.PrepareResourceForConcurrentAccessAsync(Project resource, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Threading.AsyncReaderWriterResourceLock`2.Helper.<.ctor>b__8_2(Task prev, Object state)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by jeffkl** [comment]
PR is sent, we'll take the bug to shiproom for approval

**Comment by Pilchie** [comment]
Thanks @jeffkl - resolving this as external.
