### ISSUE TITLE
Integration tests are failing with "Message: System.ArgumentException : The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))"

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3286]
All the currently enabled integrations tests are failing with the following both on dev boxes and Jenkins:

```
Test Name:	AddPackageReference
Test FullName:	Microsoft.VisualStudio.ProjectSystem.IntegrationTests.CSharpProjectFileEditTest.AddPackageReference
Test Source:	E:\project-system2\src\Microsoft.VisualStudio.ProjectSystem.IntegrationTests\CSharp\CSharpProjectFileEditTest.cs : line 65
Test Outcome:	Failed
Test Duration:	0:00:00.001

Result StackTrace:	
at EnvDTE.Commands.Item(Object index, Int32 ID)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstance.<>c__DisplayClass85_0.<StartRemoteIntegrationService>b__0()
   at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstance.<>c__DisplayClass88_0`1.<RetryRpcCall>b__0()
   at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstance.RetryRpcCall(Action action)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstance.RetryRpcCall[T](Func`1 action)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstance.StartRemoteIntegrationService(DTE dte)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstance..ctor(Process hostProcess, DTE dte, ImmutableHashSet`1 supportedPackageIds, String installationPath)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstanceFactory.UpdateCurrentlyRunningInstance(ImmutableHashSet`1 requiredPackageIds, Boolean shouldStartNewInstance)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstanceFactory.GetNewOrUsedInstance(ImmutableHashSet`1 requiredPackageIds)
   at Microsoft.VisualStudio.ProjectSystem.IntegrationTests.AbstractIntegrationTest..ctor(String solutionName, String projectTemplate, VisualStudioInstanceFactory instanceFactory)
   at Microsoft.VisualStudio.ProjectSystem.IntegrationTests.CSharpProjectFileEditTest..ctor(VisualStudioInstanceFactory instanceFactory)
Result Message:	System.ArgumentException : The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))

``

**Comment by Pilchie** [comment]
Assigning to @etbyrd since he's looking at integration tests for both roslyn and project-system this sprint.

**Comment by etbyrd** [comment]
No longer relevant.
