### ISSUE TITLE
Close solution and reopen, an internal error occurred.

### ISSUE THREAD

**Issue by Xiu-Li** [dotnet/project-system#3338]
## **Repro steps:**
1. Create a new .net core/standard project.
2. Close the solution and reopen or unload the project and reload.
**Actual results:**
Prompt for the following information:
![image](https://user-images.githubusercontent.com/24784908/36889508-41df95de-1e35-11e8-8ef2-925b759c994f.png)
The diagnostic log:
\\bvtsrv2\team\v-lixiu\DevOpsCTI\E2E Validation\Diagnostic Logs\VsProjectFault_40e71a4f-17db-42fd-82ca-75a31ff5ee0d.failure.txt
**Expected results:**
No any errors and warnings
## **Related information:**
VS build: D15.7stg/27501.3002 (15.7 Preview 1) 
dotnet --info:
```
.NET Command Line Tools (2.1.100)

Product Information:
 Version:            2.1.100
 Commit SHA-1 hash:  b9e74c6520

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.100\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

**Comment by davkean** [comment]
Looks like a regression that I introduced: 
```
Microsoft.Assumes+InternalErrorException: An internal error occurred. Please contact Microsoft Product Support Services.
   at Microsoft.Assumes.Fail(String message, Boolean showAssert)
   at Microsoft.VisualStudio.ProjectSystem.VS.Debug.StartupProjectRegistrar.<InitializeCoreAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposedAsync.<<-ctor>b__4_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.AsyncLazy`1.<>c__DisplayClass13_1.<<GetValueAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposedAsync.<<InitializeAsync>b__27_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by davkean** [comment]
For some reason the GUID is empty.

**Comment by davkean** [comment]
Cannot repro this on _Int Preview VisualStudio.15.IntPreview/15.6.0-pre.7.0+27428.1.d15.6_. Trying 15.7.

**Comment by davkean** [comment]
At the moment, this component isn't actually loading for me on 15.7 due to another issue. Fixing that first.

**Comment by davkean** [comment]
After fixing https://github.com/dotnet/project-system/issues/3341 I can repro this.

**Comment by davkean** [comment]
I understand the bug. Not sure what the fix is at the moment; basically made some incorrect assumptions that the factory completion occurs _after_ the GUID is set, this is not always correct.

**Comment by davkean** [comment]
I have a fix out for review #3364.

**Comment by Xiu-Li** [comment]
@davkean Verified this bug, **not repro** on latest **d15.7**/27508.00. 
But **repro** on latest **d15.7stg**/27508.3006.

**Comment by Xiu-Li** [comment]
**Regression** on latest VS build d15.7/27513.00.

**Comment by davkean** [comment]
@Pilchie Teach me to fish - how do I figure out what was inserted and when?

**Comment by Pilchie** [comment]
Generally - look at the `components.json` for a particular build, and see the signed build version for project-system.

Then look at the signed build queue and look at what commit sha that build was based on.

I wonder if we could get @TyOverby to update http://vsbuildtoroslynsha.azurewebsites.net/ and make it support `project-system` too.

**Comment by TyOverby** [comment]
The site does support project system.  I plugged in those values and got server errors though...

**Comment by Xiu-Li** [comment]
Verified this, **not repro** on latest d15.7 and d15.7stg VS build.

**Comment by davkean** [comment]
Awesome thanks for following up @Xiu-Li!
