### ISSUE TITLE
VS 15.6 creates net461 exectuables that fail with Microsoft.Win32.Primitives not found

### ISSUE THREAD

**Issue by btrepp** [dotnet/project-system#3369]
In visual studio 15.6 using the new SDK  (fsproj), if I build a project it runs fine on the machine, but when deployed to windows server it fails with (whenever it tries to do HTTP calls).

```
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.0.0.0,
Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest
definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Net.Http.WinHttpHandler.HandleAsyncException(WinHttpRequestState state, Exception ex)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__101.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback,
Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state,
Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
This file is in the output directory
`-a----       11/06/2016  11:13 PM          22760 Microsoft.Win32.Primitives.dll`

Why does this work on machines with VS2017 15.6 but not servers?. Especially when the library is on disk and next to the binary?.

**Comment by davkean** [comment]
This issue was moved to dotnet/sdk#2037
