### ISSUE TITLE
project dependency has error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#3371]
VS2017 reports an error on the dependencies of my projects but gives no further hints whats the problem.

After I did an Unload and Load of one of the root-projects I got the following error in the temp-folder:

```
=====================
07.03.2018 14:17:28
Recoverable
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.TryGetCurrentMetadataReference(String filename)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.TryProjectConversionForIntroducedOutputPath(String binPath, AbstractProject projectToReference)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectTracker.UpdateReferencesForBinPathChange(String path, Action updateProjects)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectTracker.UpdateProjectBinPath(AbstractProject project, String oldBinPathOpt, String newBinPathOpt)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectTracker.AddProject(AbstractProject project)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProject..ctor(VisualStudioProjectTracker projectTracker, Func`2 reportExternalErrorCreatorOpt, String projectDisplayName, String projectFilePath, IVsHierarchy hierarchy, String language, Guid projectGuid, String binOutputPath, IServiceProvider serviceProvider, VisualStudioWorkspaceImpl visualStudioWorkspaceOpt, HostDiagnosticUpdateSource hostDiagnosticUpdateSourceOpt, ICommandLineParserService commandLineParserServiceOpt)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProjectFactory.Microsoft.VisualStudio.LanguageServices.ProjectSystem.IWorkspaceProjectContextFactory.CreateProjectContext(String languageName, String projectDisplayName, String projectFilePath, Guid projectGuid, Object hierarchy, String binOutputPath)
   at Microsoft.VisualStudio.ProjectSystem.VS.LanguageServices.UnconfiguredProjectContextProvider.&lt;&gt;c__DisplayClass24_0.&lt;&lt;CreateProjectContextAsyncCore&gt;b__0&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask`1.&lt;JoinAsync&gt;d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.LanguageServices.UnconfiguredProjectContextProvider.&lt;CreateProjectContextAsyncCore&gt;d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.LanguageServices.UnconfiguredProjectContextProvider.&lt;CreateProjectContextAsync&gt;d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost.&lt;&gt;c__DisplayClass26_0.&lt;&lt;UpdateProjectContextAsync&gt;b__0&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.SemaphoreSlimExtensions.&lt;ExecuteWithinLockAsync&gt;d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost.&lt;UpdateProjectContextAsync&gt;d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost.&lt;UpdateProjectContextAndSubscriptionsAsync&gt;d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost.&lt;InitializeCoreAsync&gt;d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposedAsync.&lt;&lt;-ctor&gt;b__4_0&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.AsyncLazy`1.&lt;&gt;c__DisplayClass13_1.&lt;&lt;GetValueAsync&gt;b__0&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposedAsync.&lt;&lt;InitializeAsync&gt;b__27_0&gt;d.MoveNext()
===================
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/209706/project-dependency-has-error.html
VSTS ticketId: 578036_
_These are the original issue comments:_

Kevin Pilch [MSFT] on 3/9/2018, 04:51 PM (2 days ago): <p>Thank you for your feedback! For us to investigate this further, could you please provide more info about your issue?  If possible, can you share a solution where this repros?  We look forward to hearing from you!</p>

Martin Demberger on 3/11/2018, 07:23 AM (25 hours ago): <p>Hi Kevin,</p><p>sorry but I can't give you my solution. It's a large and closed solution.</p><p>I don't know where to find further informations about this. VS2017 doesn't give me any hint what's going wrong. The only Thing I was able to find is the exception from my first message.</p><p>Only one hint: the solution was configured as Release.</p>

Kevin Pilch [MSFT] on 3/12/2018, 08:11 AM (48 min ago): <p>Thanks <a rel="user" href="https://developercommunity.visualstudio.com/users/65516/d93a64f6-1511-6236-897f-e9d9b757824a.html" nodeid="65516">@Martin Demberger</a> - I totally understand not being able to share the solution.  Can you try:</p><ol><li>Start a developer command prompt</li><li>Set an environment variable: `set PROJECTSYSTEM_PROJECTOUTPUTPANEENABLED=1`</li><li>Launch VS from that command prompt: `devenv`</li></ol><p>Once you do this, there should be an extra entry in the output window dropdown for project system logging.  Can you capture the contents of that log when this happens for us to take a look at?</p>

Martin Demberger on 3/12/2018, 08:33 AM (26 min ago): <p>The log file is attached. Can you please delete this attachment when you are done.</p>
_These are the original issue solutions:_
(no solutions)

**Comment by MartinDemberger** [comment]
@Pilchie 
Can you delete the projectlog.zip attachment from this bug report or make it only visible to members of Microsoft!
I'm not happy if everybody can see the hole class structure of my project!

**Comment by Pilchie** [comment]
Done from here (sorry about that).  Unfortunately, I can't seem to delete that comment from developercommunity.  Can you as the poster?  If not, I'll loop in the right folks to get it cleaned up.

**Comment by tmeschter** [comment]
Given that this affects 2017 and we don't have more recent information about it, we're going to close it.
