### ISSUE TITLE
Build stuck due to missing ProjectRestoreInfo

### ISSUE THREAD

**Issue by xen2** [dotnet/project-system#3408]
Since we converted our project (Xenko) to new project system, we often (esp. after switching branches) end up in a broken state.

When trying to build, we end up with something like this in the log:
```
Error occurred while restoring NuGet packages: System.InvalidOperationException: The operation failed as details for project SiliconStudio.Core.Design.Tests could not be loaded.
   at NuGet.PackageManagement.VisualStudio.NetCorePackageReferenceProject.GetPackageSpecsAsync(DependencyGraphCacheContext context)
   at NuGet.PackageManagement.DependencyGraphRestoreUtility.<GetSolutionRestoreSpec>d__7.MoveNext()
```
Build is totally stuck, i.e it stays like this:
```
1>FastUpToDate: Project information is older than current project version, skipping check. (SiliconStudio.Core)
Error occurred while restoring NuGet packages: The operation failed as details for project SiliconStudio.Core.Design.Tests could not be loaded.
2>FastUpToDate: Project information is older than current project version, skipping check. (Irony)
3>FastUpToDate: Project information is older than current project version, skipping check. (SiliconStudio.ExecServer)
```

Restarting VS & git clean (.vs) usually doesn't seem to fix the issue.
I sometime get out of the situation by:
(1) Killing all MSBuild process
(2) Doing a manual (command-line) nuget restore
(3) Sometimes (random magic) git clean and/or VS restart might also be necessary

It happens quite easily on multiple separate PC and users, so not a local issue.

I investigated little bit and it seems `NominateProject` is not called on this specific project.
Not sure if related, but here's what I noticed when debugging project-system:
- Some NominateRestore calls (but only about 20 of them, out of 100+ projects)
- A big `Microsoft.Build.Exceptions.BuildAbortedException` exception
```
Exception thrown: 'Microsoft.Build.Exceptions.BuildAbortedException' in Microsoft.Build.dll
Build was canceled. A node of the required type InProc could not be created.
```
Could this be the main issue?
- Hundreds of `System.OperationCanceledException` in `Microsoft.VisualStudio.Threading.dll`
- A few more NominateRestore (but only for projects that already ran through NominateRestore before).

**Comment by jmarolf** [comment]
@xen2 could you install [this exentions](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools) and capture a verbose build log?

**Comment by Pilchie** [comment]
Also, can you get a project system log as described here: https://github.com/dotnet/project-system/pull/3027#issuecomment-350109050

**Comment by xen2** [comment]
Now loading the project with Build Logging + `PROJECTSYSTEM_PROJECTOUTPUTPANEENABLED=1`:

Here is the Build Logging pane result:
[buildloggingpane2.txt](https://github.com/dotnet/project-system/files/1836037/buildloggingpane2.txt)
We can see lot of `DesignTimeBuild` stuck in `Running` state. This is probably what is preventing normal build to continue.
Here's the MSBuild log of one of those `Running` build: 
[SiliconStudio.Assets.CompilerApp_Debug_AnyCPU_DesignTimeBuild_2018-03-22T12_58_59.3988985+09_00.binlog.zip](https://github.com/dotnet/project-system/files/1836040/SiliconStudio.Assets.CompilerApp_Debug_AnyCPU_DesignTimeBuild_2018-03-22T12_58_59.3988985.09_00.binlog.zip)

I attached to all MSBuild.exe instances and checked their threads. None of them looks busy, so somehow maybe a build success/failure is not properly sent back to caller (DesignTimeBuild still in running state):
![image](https://user-images.githubusercontent.com/527565/37750905-a7771a14-2dd2-11e8-8ab5-4df4c4490a34.png)


Also, when Visual Studio is opening solution, I get the following (maybe unrelated?) error:

![image](https://user-images.githubusercontent.com/527565/37749869-5d5c4242-2dcd-11e8-9fc6-883dec0f2cf5.png)

[VsProjectFault_2ba8a90c-dcc7-484d-99ea-2bf2b784ec95.failure.txt](https://github.com/dotnet/project-system/files/1835993/VsProjectFault_2ba8a90c-dcc7-484d-99ea-2bf2b784ec95.failure.txt)

I also sometimes get lots of `[3/22/2018 12:41:36 PM Error] LoadProjectIdsAsync: Object reference not set to an instance of an object.` in Output > Tests (and it takes over focus of Output pane every second so it is quite annoying).

Hope that helps.

**Comment by Pilchie** [comment]
@lifengl @jviau @adrianvmsft Any ideas here?

**Comment by adrianvmsft** [comment]
I see DesignTimeBuildManagerService in the log, so it could be related to the new DTBB service.
Could you try switching off to the old design time mechanism by setting this environment variable and see if you experience the same behavior?

SET CPS_DesignTimeBuild=Cps

**Comment by lifengl** [comment]
@panopticoncentral do you know about the ProjectLogger code here?

**Comment by adrianvmsft** [comment]
Actually, nevermind, I see it already calls the old design time build system

**Comment by Pilchie** [comment]
Any progress here?  What are next steps?

**Comment by Pilchie** [comment]
@davkean - which nullref do you mean?  The project fault looks like the logger is faulting the output group service dataflow is faulting because of null ref too:

```
System.AggregateException: Project system data flow 'OutputGroupsService Outer 343713' closed because of an exception: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.ProjectSystem.Tools.BuildLogging.Model.LoggerBase.GetLogPath(Build build)
   at Microsoft.VisualStudio.ProjectSystem.Tools.BuildLogging.Model.ProjectLogger.Shutdown()
   at Microsoft.Build.Utilities.MuxLogger.SubmissionRecord.Shutdown()
   at Microsoft.Build.Utilities.MuxLogger.UnregisterLoggers(Int32 submissionId)
   at Microsoft.VisualStudio.ProjectSystem.Build.BuildUtilities.<>c__DisplayClass14_0.<AppendUnregisterLoggersTask>b__0(Task`1 flt)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

@xen2 the project log looks like it's from a bit of an old build?  What version of VS are you using?

**Comment by davkean** [comment]
@xen2 Are you still running into this?

**Comment by clarkitect** [comment]
This has begun on one of our solutions in `15.7.2` this week.  It's a rather crippling, please re-open and I'll see if I can get diagnostic info to attach.

**Comment by Pilchie** [comment]
Is this consistently after debugging or does it only happen with command line builds with `dotnet build`?  If so, we should probably track at https://github.com/dotnet/cli.

**Comment by clarkitect** [comment]
Occurs at, or immediately after, open of solution fresh (escalated privileges, long story) instance of visual studio 2017 15.7.2.

There may have been `dotnet build` command issued recently and there are projects within the solution that have .net core 2 and .net standard build targets defined.

Have _not yet_ experimented with:

1. Uninstalling resharper
1. Uninstalling any other plugins that I've forgotten about

**Comment by roldengarm** [comment]
I have got exactly the same problem. After upgrading to latest VS 15.7.2 this issue started occurring. No idea what is causing it.

**Comment by clarkitect** [comment]
Update: problem "solved" or temporarily quieted.  Cleaned `git clean -fdx` repository and haven't seen the complaint since.

A coworker "solved" or temporarily quieted it by rolling back to previous revision of Visual Studio.
