### ISSUE TITLE
Integration tests are failing indeterminately with MEF composition issue

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3924]
```
20:10:46 Debug Trace:
20:10:46 Error loading dependency assembly 'Microsoft.Test.Apex.TeamFoundation, PublicKeyToken=b03f5f7f11d50a3a' of 'Microsoft.Test.Apex.SourceControlIntegration.dll' for operations composition container. Dependencies from this assembly will be missing in the composition. Could not load file or assembly 'Microsoft.Test.Apex.TeamFoundation, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
20:10:46  Populating Assembly Catalog: ApexAssemblyCatalog (attributed with [ProvidesOperationsExtensionAttribute])
20:10:46      Failed to load assembly Microsoft.VisualStudio.TestTools.UnitTesting.AssertInconclusiveException while looking for exports. Exception: System.TypeLoadException: Cannot find type System.Exception in module System.Runtime.dll.
20:10:46     at Microsoft.MetadataReader.MetadataOnlyAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyAssembly.GetType(String name, Boolean throwOnError)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyModule.ResolveTypeRef(ITypeReference typeReference)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyTypeReference.GetResolvedTypeWorker()
20:10:46     at Microsoft.MetadataReader.TypeProxy.GetResolvedType()
20:10:46     at Microsoft.MetadataReader.TypeProxy.GetCustomAttributesData()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.HasAttributes(Type targetType, Boolean validateInheritedAttributes, Type[] attributeTypes)
20:10:46     at Microsoft.Test.Apex.ApexTypeUniverse.<GetExportedTypes>d__11.MoveNext()
20:10:46      Failed to load assembly Microsoft.VisualStudio.TestTools.UnitTesting.InternalTestFailureException while looking for exports. Exception: System.TypeLoadException: Cannot find type System.Exception in module System.Runtime.dll.
20:10:46     at Microsoft.MetadataReader.MetadataOnlyAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyAssembly.GetType(String name, Boolean throwOnError)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyModule.ResolveTypeRef(ITypeReference typeReference)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyTypeReference.GetResolvedTypeWorker()
20:10:46     at Microsoft.MetadataReader.TypeProxy.GetResolvedType()
20:10:46     at Microsoft.MetadataReader.TypeProxy.GetCustomAttributesData()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.HasAttributes(Type targetType, Boolean validateInheritedAttributes, Type[] attributeTypes)
20:10:46     at Microsoft.Test.Apex.ApexTypeUniverse.<GetExportedTypes>d__11.MoveNext()
20:10:46      Failed to load assembly Microsoft.VisualStudio.TestTools.UnitTesting.ExpectedExceptionAttribute while looking for exports. Exception: System.TypeLoadException: Cannot find type System.Attribute in module System.Runtime.dll.
20:10:46     at Microsoft.MetadataReader.MetadataOnlyAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyAssembly.GetType(String name, Boolean throwOnError)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyModule.ResolveTypeRef(ITypeReference typeReference)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyTypeReference.GetResolvedTypeWorker()
20:10:46     at Microsoft.MetadataReader.TypeProxy.GetResolvedType()
20:10:46     at Microsoft.MetadataReader.TypeProxy.GetCustomAttributesData()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.HasAttributes(Type targetType, Boolean validateInheritedAttributes, Type[] attributeTypes)
20:10:46     at Microsoft.Test.Apex.ApexTypeUniverse.<GetExportedTypes>d__11.MoveNext()
20:10:46      Failed to load assembly Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute while looking for exports. Exception: System.TypeLoadException: Cannot find type System.Attribute in module System.Runtime.dll.
20:10:46     at Microsoft.MetadataReader.MetadataOnlyAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyAssembly.GetType(String name, Boolean throwOnError)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyModule.ResolveTypeRef(ITypeReference typeReference)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyTypeReference.GetResolvedTypeWorker()
20:10:46     at Microsoft.MetadataReader.TypeProxy.GetResolvedType()
20:10:46     at Microsoft.MetadataReader.TypeProxy.GetCustomAttributesData()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.HasAttributes(Type targetType, Boolean validateInheritedAttributes, Type[] attributeTypes)
20:10:46     at Microsoft.Test.Apex.ApexTypeUniverse.<GetExportedTypes>d__11.MoveNext()
20:10:46      Failed to load assembly Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException while looking for exports. Exception: System.TypeLoadException: Cannot find type System.Exception in module System.Runtime.dll.
20:10:46     at Microsoft.MetadataReader.MetadataOnlyAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyAssembly.GetType(String name, Boolean throwOnError)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyModule.ResolveTypeRef(ITypeReference typeReference)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyTypeReference.GetResolvedTypeWorker()
20:10:46     at Microsoft.MetadataReader.TypeProxy.GetResolvedType()
20:10:46     at Microsoft.MetadataReader.TypeProxy.GetCustomAttributesData()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.HasAttributes(Type targetType, Boolean validateInheritedAttributes, Type[] attributeTypes)
20:10:46     at Microsoft.Test.Apex.ApexTypeUniverse.<GetExportedTypes>d__11.MoveNext()
20:10:46      Failed to load assembly Microsoft.VisualStudio.TestTools.UnitTesting.DataTestMethodAttribute while looking for exports. Exception: System.TypeLoadException: Cannot find type System.Attribute in module System.Runtime.dll.
20:10:46     at Microsoft.MetadataReader.MetadataOnlyAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyAssembly.GetType(String name, Boolean throwOnError)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyModule.ResolveTypeRef(ITypeReference typeReference)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyTypeReference.GetResolvedTypeWorker()
20:10:46     at Microsoft.MetadataReader.TypeProxy.GetResolvedType()
20:10:46     at Microsoft.MetadataReader.TypeProxy.GetCustomAttributesData()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.HasAttributes(Type targetType, Boolean validateInheritedAttributes, Type[] attributeTypes)
20:10:46     at Microsoft.Test.Apex.ApexTypeUniverse.<GetExportedTypes>d__11.MoveNext()
20:10:46      Failed to load assembly Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute while looking for exports. Exception: System.TypeLoadException: Cannot find type System.Attribute in module System.Runtime.dll.
20:10:46     at Microsoft.MetadataReader.MetadataOnlyAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyAssembly.GetType(String name, Boolean throwOnError)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyModule.ResolveTypeRef(ITypeReference typeReference)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyTypeReference.GetResolvedTypeWorker()
20:10:46     at Microsoft.MetadataReader.TypeProxy.GetResolvedType()
20:10:46     at Microsoft.MetadataReader.TypeProxy.GetCustomAttributesData()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.HasAttributes(Type targetType, Boolean validateInheritedAttributes, Type[] attributeTypes)
20:10:46     at Microsoft.Test.Apex.ApexTypeUniverse.<GetExportedTypes>d__11.MoveNext()
20:10:46      Failed to load assembly Microsoft.VisualStudio.TestTools.UnitTesting.CssProjectStructureAttribute while looking for exports. Exception: System.TypeLoadException: Cannot find type System.Attribute in module System.Runtime.dll.
20:10:46     at Microsoft.MetadataReader.MetadataOnlyAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyAssembly.GetType(String name, Boolean throwOnError)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyModule.ResolveTypeRef(ITypeReference typeReference)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyTypeReference.GetResolvedTypeWorker()
20:10:46     at Microsoft.MetadataReader.TypeProxy.GetResolvedType()
20:10:46     at Microsoft.MetadataReader.TypeProxy.GetCustomAttributesData()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.HasAttributes(Type targetType, Boolean validateInheritedAttributes, Type[] attributeTypes)
20:10:46     at Microsoft.Test.Apex.ApexTypeUniverse.<GetExportedTypes>d__11.MoveNext()
20:10:46      Failed to load assembly Microsoft.VisualStudio.TestTools.UnitTesting.CssIterationAttribute while looking for exports. Exception: System.TypeLoadException: Cannot find type System.Attribute in module System.Runtime.dll.
20:10:46     at Microsoft.MetadataReader.MetadataOnlyAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyAssembly.GetType(String name, Boolean throwOnError)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyModule.ResolveTypeRef(ITypeReference typeReference)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyTypeReference.GetResolvedTypeWorker()
20:10:46     at Microsoft.MetadataReader.TypeProxy.GetResolvedType()
20:10:46     at Microsoft.MetadataReader.TypeProxy.GetCustomAttributesData()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.HasAttributes(Type targetType, Boolean validateInheritedAttributes, Type[] attributeTypes)
20:10:46     at Microsoft.Test.Apex.ApexTypeUniverse.<GetExportedTypes>d__11.MoveNext()
20:10:46      Failed to load assembly Microsoft.VisualStudio.TestTools.UnitTesting.WorkItemAttribute while looking for exports. Exception: System.TypeLoadException: Cannot find type System.Attribute in module System.Runtime.dll.
20:10:46     at Microsoft.MetadataReader.MetadataOnlyAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyAssembly.GetType(String name, Boolean throwOnError)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyModule.ResolveTypeRef(ITypeReference typeReference)
20:10:46     at Microsoft.MetadataReader.MetadataOnlyTypeReference.GetResolvedTypeWorker()
20:10:46     at Microsoft.MetadataReader.TypeProxy.GetResolvedType()
20:10:46     at Microsoft.MetadataReader.TypeProxy.GetCustomAttributesData()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.<GetAllAttributes>d__3.MoveNext()
20:10:46     at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
20:10:46     at Microsoft.Test.Apex.ReflectionHelpers.HasAttributes(Type targetType, Boolean validateInheritedAttributes, Type[] attributeTypes)
20:10:46     at Microsoft.Test.Apex.ApexTypeUniverse.<GetExportedTypes>d__11.MoveNext()
20:10:46      Found 78 exported, and 0 unexportable types from assemblies 'Microsoft.Test.Apex.Framework.dll, Microsoft.Test.Apex.VSTestIntegration.dll, Microsoft.VisualStudio.ProjectSystem.IntegrationTests.dll, Microsoft.VisualStudio.TestPlatform.TestFramework.dll, Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.dll, Microsoft.Test.Apex.VisualStudio.dll, Microsoft.Test.Apex.VisualStudio.Hosting.dll, Microsoft.Test.Apex.OsIntegration.dll, Microsoft.Test.Apex.SourceControlIntegration.dll'
20:10:46  
20:10:46  Failed to load Omni log dll: System.IO.FileNotFoundException: Could not load file or assembly 'Omni.Logging.Extended' or one of its dependencies. The system cannot find the file specified.
20:10:46  File name: 'Omni.Logging.Extended'
20:10:46     at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
20:10:46     at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
20:10:46     at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
20:10:46     at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
20:10:46     at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
20:10:46     at System.Reflection.Assembly.Load(String assemblyString)
20:10:46     at Microsoft.Test.Apex.Services.Logging.TestLoggerSinks.OmniLog.OmniLogSink..ctor()
```

**Comment by davkean** [comment]
Failure here: https://ci.dot.net/job/dotnet_project-system/job/master/job/windows_integration_debug_prtest/49/consoleFull#-19375457538bb52e59-de52-4f1c-b131-470db4c594cd.

**Comment by davkean** [comment]
And here: https://ci.dot.net/job/dotnet_project-system/job/master/job/windows_integration_debug_prtest/58/consoleFull#18762134808943a369-e80c-4557-899a-c780301de2ed.

**Comment by abpiskunov** [comment]
@davkean Where are your integration tests sources?

**Comment by jmarolf** [comment]
@abpiskunov tests are here: https://github.com/dotnet/project-system/tree/master/src/Microsoft.VisualStudio.ProjectSystem.IntegrationTests

**Comment by davkean** [comment]
And again: https://ci.dot.net/job/dotnet_project-system/job/master/job/windows_integration_debug_prtest/68/consoleFull#18762134808943a369-e80c-4557-899a-c780301de2ed.

**Comment by davkean** [comment]
And again: https://ci.dot.net/job/dotnet_project-system/job/master/job/windows_integration_debug_prtest/65/

**Comment by jmarolf** [comment]
This was due to checking in 15.8 dependencies when we were running on 15.5 machines
