### ISSUE TITLE
VSIX uninstallation should not fail the test run

### ISSUE THREAD

**Issue by jmarolf** [dotnet/project-system#3983]
In [this](https://ci.dot.net/job/dotnet_project-system/job/master/job/windows_integration_debug_prtest/117/) test run VSIXes failed to un-intall.  This should not fail the test run.

```ini
23:50:34 Cannot remove item C:\Users\runner\AppData\Local\Microsoft\VisualStudio\15.0_cfdf9bf9ProjectSystem\Extensions\sskoz1lv.xpl\Microsoft.VisualStudio.ProjectSystem.CSharp.dll: Access to the path 'Microsoft.VisualStudio.ProjectSystem.CSharp.dll' is denied.
23:50:34 System.UnauthorizedAccessException: Access to the path 'Microsoft.VisualStudio.ProjectSystem.CSharp.dll' is denied.
23:50:34    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
23:50:34    at System.IO.FileInfo.Delete()
23:50:34    at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveFileSystemItem(FileSystemInfo fileSystemInfo, Boolean force)
23:50:34 at UninstallVSIXes, D:\j\workspace\windows_integ---e5231994\build\Build.ps1: line 253
23:50:34 at RunIntegrationTests, D:\j\workspace\windows_integ---e5231994\build\Build.ps1: line 300
23:50:34 at <ScriptBlock>, D:\j\workspace\windows_integ---e5231994\build\Build.ps1: line 360
23:50:34 at <ScriptBlock>, <No file>: line 1
23:50:34 Killing running build processes...
```

**Comment by Pilchie** [comment]
Will the failure to uninstall impact subsequent runs?

**Comment by jmarolf** [comment]
A failure to _install_ should fail the run.  No one else runs in the same hive as us so I would not expect a failure to uninstall to break things for other teams

**Comment by jjmew** [comment]
This issue doesn't meet the bar
