### ISSUE TITLE
Integration tests are failing on 16.0 with missing "Microsoft.Test.Apex.Framework, Version=16.0.0.0"

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3992]
Integration tests are failing with the following under 16.0:

```
   Could not load file or assembly 'Microsoft.Test.Apex.Framework, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at MessageHookProc(Int32 nCode, UInt32 wparam, Int32 lparam)
```

**Comment by jmarolf** [comment]
Looks like we'll need to ask @AArnott to upload nuget packages for the 16.0 versions of APEX when they are ready.

**Comment by AArnott** [comment]
To have seen this error at all, it seems you'd have to have something that has already seen Apex 16. so I guess it's already around. I'm no longer in charge of that though. @javierdlg may be the one to do it.

**Comment by jmarolf** [comment]
Currently blocked on not having Dev16 images available

**Comment by javierdlg** [comment]
This is odd, I only got this notification now.
Either way, dev16 bits are already released on the myget repo here:
https://vside.myget.org/feed/vs-impl/package/nuget/Microsoft.Test.Apex.VisualStudio

You should be able to update the nuget dependency to the latest one.

**Comment by davkean** [comment]
Thanks, just need Dev16 images in VSTS.

**Comment by javierdlg** [comment]
Can you go into a bit more detail? Do you need the Apex dlls published on the vs-impl feed?

**Comment by davkean** [comment]
Dependencies are fine, we have all we need from Apex. Just referring to the fact that we don't yet have Virtual Machine images running Dev16 in our build lab that we can use to run against Dev16.

**Comment by davkean** [comment]
When fixing this we also need to fix the reference to 15.0 in build.cmd for uninstall:

`AppData\Local\Microsoft\VisualStudio\15.0_$($vsid)$($hive)\Extensions`

**Comment by jmarolf** [comment]
@javierdlg the 16.0 Apex package is unusable without 16.0 versions of the following packages:

- Microsoft.VisualStudio.Composition
- Microsoft.VisualStudio.Shell.15.0
- Microsoft.VisualStudio.WCFReference.Interop
- Microsoft.VSDesigner
- Microsoft.VisualStudio.ComponentModelHost

**Comment by drewnoakes** [comment]
@davkean were you seeing this when running integration tests locally? They work locally for me.

**Comment by davkean** [comment]
They appear to now run from the UI, but the statement about `build.ps1` for uninstall still stands.
