### ISSUE TITLE
ArgumentException thrown by ReferencesHostBridge: "An item with the same key has already been added."

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/project-system#4237]
**Repro**

1. Install VS 2017 15.9 Preview with the .NET Core workload
1. Clone https://github.com/aspnet/Extensions/tree/release/2.1 (current commit is https://github.com/aspnet/Extensions/tree/290f4b345c82173b2e16cce512dae44e5a1b60da)
2. Open Extensions.sln

**Expected**
The solution should load projects

**Actual**
A popup like this appears a few dozen times:
![image](https://user-images.githubusercontent.com/2696087/48148375-6b57db80-e26e-11e8-9a08-1270c496f275.png)

The diagnostic log contains hundreds of errors like this:

```
===================
11/7/2018 9:18:17 AM
LimitedFunctionality
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ReferencesHostBridge.PreprocessAsync(IProjectVersionedValue`1 input, ReferencesDelta previousOutput)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectHostBridge`3.<>c__DisplayClass37_0.<<InitializeCoreAsync>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ReferencesHostBridge.PreprocessAsync(IProjectVersionedValue`1 input, ReferencesDelta previousOutput)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectHostBridge`3.<>c__DisplayClass37_0.<<InitializeCoreAsync>b__1>d.MoveNext()<---
```

**More details**

I suspect this is related to the way we have written custom targets to resolve `<Reference>` items. Command line builds work just fine, but perhaps we haven't our custom target into the correct design time targets.

Also, the project builds just fine, test explorer finds and run tests, so this doesn't block us from working with the solution. It's just really annoying.

**Comment by Pilchie** [comment]
This is core CPS, not the C#/VB project system. Can you please file internally?

**Comment by natemcmaster** [comment]
Ok. I opened https://developercommunity.visualstudio.com/content/problem/377676/argumentexception-thrown-by-referenceshostbridge-a.html instead.
