### ISSUE TITLE
TreeData.OnAfterApplyTree throws exception

### ISSUE THREAD

**Issue by jmarolf** [dotnet/project-system#4304]
build: 28320.3006.d16.0stg

repro steps:

Unknown, but the last operation I did was modify project xml in temporary tab and then close the tab.

```ini
=====================
11/21/2018 1:21:10 AM
Recoverable
System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.ErrorHandler.ThrowOnFailure(Int32 hr)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.TreeService.TreeData.OnAfterApplyTree(TreeData previouslyAppliedOutput, ImmutableDictionary`2 renames)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.TreeService.ApplyAsync(TreeData value)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__action|0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
===================
```

**Comment by davkean** [comment]
Yeah I hit this also, couldn't repro it. CPS bug.

**Comment by davkean** [comment]
Duplicating against https://devdiv.visualstudio.com/DevDiv/_workitems/edit/736157.
