### ISSUE TITLE
An error dialog pops up after left-double-click "NETCoreTest" project to check the .csproj file

### ISSUE THREAD

**Issue by OliaG** [dotnet/project-system#4491]
_From @Zheng-Li01 on January 23, 2019 8:54_

**OS:** RS4 x64
**VS:** 16.0.0 Preview 2.0 [28522.59.d16.0]
**.NET SDK:** .NET Core 3.0.100-preview-010143
 
**More info:**
1.	This issue also can reproduce on Console and Class library .net core applications.
2.	The issue can’t reproduce on 16.0.0 Preview 1.1 [28408.50.d16.0] + latest NET Core 3.0.100-preview-010143.
 
**Steps to reproduce:**
1.	Install .NET Core 3.0 SDK available from https://github.com/dotnet/core-sdk.
2.	Create a Winforms .Net Core application by command: dotnet new winforms –o “NETCoreTest”.
3.	Open the project and left-double-click "NETCoreTest" project to check the .csproj file.
 
**Actual:**
An error dialog pops up. 
![image](https://user-images.githubusercontent.com/38325459/51594368-3edb6380-1f2f-11e9-9ed9-cf6d1ec8fcdd.png)
**Getting more info from here:**
[\\\trinlab2\BAQAFiles\v-zhgl\New folder\ActivityLog.xml](url)
 
**Expected:**
No error dialog pops up.

_Copied from original issue: dotnet/winforms#347_

**Comment by davidwengier** [comment]
Stack trace from the activity log:

```
System.ArgumentNullException: 
Value cannot be null.
Parameter name: serviceProvider
   at Microsoft.Requires.NotNull[T](T value, String parameterName)
   at Microsoft.VisualStudio.Editor.Implementation.Common.GetService(IServiceProvider serviceProvider, Guid guidService, Boolean unique)
   at Microsoft.VisualStudio.Editor.Implementation.Common.GetService[InterfaceType,ServiceType](IServiceProvider serviceProvider)
   at Microsoft.VisualStudio.Editor.Implementation.CompoundTextViewWindow.UpdateOverrideCaption()
   at Microsoft.VisualStudio.Editor.Implementation.CompoundTextViewWindow.UpdateCaptionAndLabels()
   at Microsoft.VisualStudio.Editor.Implementation.CompoundTextViewWindow.OnUserDataChange(Guid&amp; riidKey, Object vtNewValue)
   at Microsoft.VisualStudio.Editor.Implementation.TextDocData.NotifyOfTextBufferLoad(Boolean isReload)
   at Microsoft.VisualStudio.Editor.Implementation.TextDocData.OnTextDocumentFileActionOccurred(Object sender, TextDocumentFileActionEventArgs args)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by davidwengier** [comment]
Thanks for the report, I've seen this occasionally but never got a reliable repro.

**Comment by davkean** [comment]
Already filed this: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/774140.
