### ISSUE TITLE
Exception loading project

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#4512]
**Visual Studio Version**: d16.0stg, using `master` of project system

**Summary:**

Seeing exception on project load, possibly related to #4509.

![image](https://user-images.githubusercontent.com/350947/52008385-6d75b300-24c8-11e9-9384-55cd652e8e0b.png)

```
System.ArgumentException: CancelOnUnload cannot be satisfied without a project context provided.
Parameter name: options
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.Fork(Func`1 asyncAction, JoinableTaskFactory factory, UnconfiguredProject unconfiguredProject, ConfiguredProject configuredProject, ErrorReportSettings watsonReportSettings, ProjectFaultSeverity faultSeverity, ForkOptions options)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.SDKVersionTelemetryServiceComponent.SDKVersionTelemetryServiceInstance.InitializeCoreAsync(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposedAsync.<<-ctor>b__4_0>d.MoveNext()
   ...
   at Microsoft.VisualStudio.ProjectSystem.ProjectServiceHost.<LoadProjectAsync>d__76.MoveNext()
```

Solution explorer does not populate:

![image](https://user-images.githubusercontent.com/350947/52008454-8bdbae80-24c8-11e9-9b74-0eac129c67f2.png)

**Steps to Reproduce**:

1.  Create a new project

**Expected Behavior**:

No error.

**Actual Behavior**:

Error.

**User Impact**:

User cannot do any work at all.

**Comment by drewnoakes** [comment]
b38d158c4fad7c429e2a7dddc6c33ed0307e982c doesn't exhibit this problem. I'm pretty sure it was introduced in ac5b8562f2afa3285c89c2318074eca9f38c1286.
