### ISSUE TITLE
ArgumentException at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectTree.Add

### ISSUE THREAD

**Issue by mavasani** [dotnet/project-system#4551]
**Visual Studio Version**:
Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.0.0 Preview 3.0 [28531.182.d16.0]

**Summary:**

Added NuGet package reference to `Roslyn.Diagnostics.Analyzers` to a C# console netcore project and was playing around with the editing/moving the shipped API files.

Got the below dialog:
```
---------------------------
Microsoft Visual Studio
---------------------------
The project system has encountered an error.

 

An item with the caption "PublicAPI.Unshipped.txt"(ProjectTreeFlags: FileOnDisk FileSystemEntity MultipleIncludedItem SourceFile) already exists under parent "ConsoleApp10" with the same sort order as the item being added.



A diagnostic log has been written to the following location: "C:\Users\mavasani\AppData\Local\Temp\VsProjectFault_1be59b50-29ee-476a-8d34-c7c05ef0e514.failure.txt".


---------------------------
OK   
---------------------------
```

**Failure.txt:**
```
=====================
2/7/2019 2:31:21 PM
LimitedFunctionality
System.ArgumentException: An item with the caption "PublicAPI.Unshipped.txt"(ProjectTreeFlags: FileOnDisk FileSystemEntity MultipleIncludedItem SourceFile) already exists under parent "ConsoleApp10" with the same sort order as the item being added.
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectTree.Add(UnattachedProjectTreeNode node)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectTree.Add(IProjectItemTree subtree)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.MoveProjectItemToNewDependentParent(IProjectItemTree nodeToChange, IntPtr newParentId)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.RespondToAnyChangeToDependentUponMetadata(ConfiguredProjectExports configuredProjectExports, IImmutableDictionary`2 projectData, IProjectItemTree nodeToChange, IImmutableDictionary`2 oldMetadata, IImmutableDictionary`2 metadata, Boolean alwaysRecalculateDynamicDependency)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.HandleRenamedItemStayingInOriginalFolder(IProjectTree tree, IImmutableDictionary`2 projectData, IProjectChangeDescription change, String itemType, KeyValuePair`2 renamedItem, IImmutableDictionary`2 oldMetadata, IImmutableDictionary`2 newMetadata, HashSet`1 dynamicDependentChildrenAffected, ConfiguredProjectExports configuredProjectExports)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.HandleRenamedItems(IProjectTree tree, IImmutableDictionary`2 projectData, IProjectChangeDescription change, String itemType, IImmutableDictionary`2 changeMap, HashSet`1 dynamicDependentChildrenAffected, ConfiguredProjectExports configuredProjectExports)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.OnProjectSubscriptionChanged(IProjectTree originalTree, ConfiguredProjectExports configuredProjectExports, PhysicalProjectTreeInputData updateInput, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__action|0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
===================
```

**Comment by davkean** [comment]
This is probably causing by including an item multiple-times.

**Comment by davkean** [comment]
I spent some time trying to repro this and couldn't a dump next time might be helpful.
