### ISSUE TITLE
Browsing to a license file crashes VS

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4633]
1. Right-click properties on Microsoft.VisualStudio.ProjectSystem.Managed
2. Click Package
2. In licence file, browse to project-system\licence.md
3. Click OK

-- Crash-- 

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInvalidOperation(System.String, System.Object[])
   at Microsoft.Build.Shared.ErrorUtilities.VerifyThrowInvalidOperation(Boolean, System.String, System.Object, System.Object, System.Object, System.Object)
   at Microsoft.Build.Construction.ProjectItemElement.set_Include(System.String)
   at Microsoft.VisualStudio.Editors.PropertyPages.PackagePropPage+_Closure$__269-0+VB$StateMachine___Lambda$__1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.Threading.JoinableTask+<JoinAsync>d__68.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.ProjectSystem.ProjectLockService+<ExecuteWithinLock>d__117.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.ProjectLockService+<ExecuteWithinLock>d__117.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.Editors.PropertyPages.PackagePropPage+_Closure$__269-0+VB$StateMachine___Lambda$__0.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Editors.PropertyPages.PackagePropPage.AddOrChangeLicenseItem(System.String, System.String)
   at Microsoft.VisualStudio.Editors.PropertyPages.PackagePropPage.AddLicenseItemToProject(System.String)
   at Microsoft.VisualStudio.Editors.PropertyPages.PackagePropPage.LicenseBrowseButton_Click(System.Object, System.EventArgs)
   at System.Windows.Forms.Control.OnClick(System.EventArgs)
   at System.Windows.Forms.Button.OnClick(System.EventArgs)
   at System.Windows.Forms.Button.OnMouseUp(System.Windows.Forms.MouseEventArgs)
   at System.Windows.Forms.Control.WmMouseUp(System.Windows.Forms.Message ByRef, System.Windows.Forms.MouseButtons, Int32)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ButtonBase.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Button.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.OnMessage(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr, Int32, IntPtr, IntPtr)


```

**Comment by etbyrd** [comment]
That is concerning. I’ll look at this today

**Comment by etbyrd** [comment]
Fixed in https://github.com/dotnet/project-system/pull/4639
