### ISSUE TITLE
Error when opening ProjectSystem.sln in d16.1stg (28802.115)

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#4679]
I'm seeing an error when opening ProjectSystem.sln in d16.1stg, 28802.115. Looks like this was caused by #4667.

![image](https://user-images.githubusercontent.com/754264/55440860-be9f4180-55f4-11e9-8aec-2dca86150077.png)

Stack is:
```
SetSite failed for package [ManagedProjectSystemPackage]Source: 'Microsoft.VisualStudio.ProjectSystem.Implementation' Description: CancelOnUnload cannot be satisfied without a project context provided.
Parameter name: options
System.ArgumentException: CancelOnUnload cannot be satisfied without a project context provided.
Parameter name: options
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.Fork(Func`1 asyncAction, JoinableTaskFactory factory, UnconfiguredProject unconfiguredProject, ConfiguredProject configuredProject, ErrorReportSettings watsonReportSettings, ProjectFaultSeverity faultSeverity, ForkOptions options)
   at Microsoft.VisualStudio.ProjectSystem.FaultExtensions.RunAndForget(IProjectThreadingService threadingService, Func`1 asyncAction, UnconfiguredProject unconfiguredProject, ProjectFaultSeverity faultSeverity, ForkOptions options)
   at Microsoft.VisualStudio.ProjectSystem.VS.DotNetCoreProjectCompatibilityDetector.<InitializeAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Packaging.ManagedProjectSystemPackage.<InitializeAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass19_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__68.MoveNext()
```

**Comment by davidwengier** [comment]
Also reported internally: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/835851
