### ISSUE TITLE
OpenWithSpecific throws "GetNestedHierarchy failed"

### ISSUE THREAD

**Issue by jmarolf** [dotnet/project-system#4745]
**Visual Studio Version**: 16.1stg + latest project system master

**Summary:**

found while testing https://github.com/dotnet/project-system/pull/4743

**Steps to Reproduce**:
1. Open the property pages in a debug build

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
GetNestedHierarchy failed



   at Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerView.InitView()

   at Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerWindowPane.PopulateView()

   at Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerWindowPane.ActivateLogicalView(Guid& rguidLogicalView)

   at Microsoft.VisualStudio.Shell.Interop.IVsUIShellOpenDocument.OpenSpecificEditor(UInt32 grfOpenSpecific, String pszMkDocument, Guid& rguidEditorType, String pszPhysicalView, Guid& rguidLogicalView, String pszOwnerCaption, IVsUIHierarchy pHier, UInt32 itemid, IntPtr punkDocDataExisting, IServiceProvider pSPHierContext, IVsWindowFrame& ppWindowFrame)

   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectFileDocumentManager.OpenWithSpecific(SimpleHierarchyNode projectItem, UInt32 editorFlags, Guid& editorType, String physicalView, Guid& logicalView, IntPtr docDataExisting, IVsWindowFrame& frame, WindowFrameShowAction windowFrameActi......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by drewnoakes** [comment]
Fixed in #4843.
