### ISSUE TITLE
DebuggableCallback throws Unable to get connection point container from configuration

### ISSUE THREAD

**Issue by jmarolf** [dotnet/project-system#4746]
**Visual Studio Version**: 16.1stg + latest project system master

**Summary:**

found while testing #4743

**Steps to Reproduce**:

1. Open the 'build' property page in a debug build 

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Unable to get connection point container from configuration



   at Microsoft.VisualStudio.Editors.PropertyPages.PropertyListener.TryCreate(PropPageUserControlBase PropPage, Object EventSource, String DebugSourceName, IVsHierarchy ProjectHierarchy, Boolean ListenToInactiveConfigs)

   at Microsoft.VisualStudio.Editors.PropertyPages.PropPageUserControlBase.AttemptConnectPropertyNotifyObject(Object EventSource, String DebugSourceName)

   at Microsoft.VisualStudio.Editors.PropertyPages.PropPageUserControlBase.ConnectPropertyNotify()

   at Microsoft.VisualStudio.Editors.PropertyPages.PropPageUserControlBase.SetObjects(Object[] objects)

   at Microsoft.VisualStudio.Editors.PropertyPages.PropPageUserControlBase.IPropertyPageInternal_SetObjects(Object[] objects)

   at Microsoft.VisualStudio.Editors.PropertyPages.PropPageBase.Create(IntPtr hWndParent)

   at Microsoft.VisualStudio.Editors.PropertyPages.PropPageBase.IPropertyPage2_Activate(IntPtr hWndParent, RECT[] pRect, Int32 bModal)

   at Microsoft.VisualStudio.Editors.PropPageDesigner.PropPageDesignerView.ActivatePage(IPropertyPage PropPage)

   at Microsoft.VisualStudio.Editors.PropPageDesigner.PropPageDesignerView.Init(Project DTEProject, IPropertyPage PropPage, PropertyPageSite PropPageSite, IVsHierarchy Hierarchy, Boolean IsConfigPage)

   at Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerView.ShowTab(Int32 Index, Boolean ForceShow, Boolean ForceActivate)

   at Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerView.OnItemClick(ProjectDesignerTabButton item, Boolean reactivatePage)

   at Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerView.OnItemClick(ProjectDesignerTabButton item)

   at Microsoft.VisualStudio.Editors.ApplicationDesigner.ProjectDesignerTabButton.OnClick(EventArgs e)

   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)

   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)

   at System.Windows.Forms.Control.WndProc(Message& m)

   at System.Windows.Forms.ButtonBase.WndProc(Message& m)

   at System.Windows.Forms.Button.WndProc(Message& m)

   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)

   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)

   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by davkean** [comment]
This will because the configuration object doesn't implement IConnectionPointContainer.
