### ISSUE TITLE
PackageRestoreUnconfiguredDataSource error when opening a solution or building

### ISSUE THREAD

**Issue by NickCraver** [dotnet/project-system#4801]
**Visual Studio Version**: 16.1 Preview 3

**Summary:** Error when opening or building a solution (possibly due to custom targets?)

**Steps to Reproduce**:
1. Open solution.
2. ...or build.

**Expected Behavior**: No errors. Builds successfully.

**Actual Behavior**: Errors! A manual restore does allow a successful build, though.

**User Impact**: A CLI workaround is required.
1. Open VS 2019 Dev Console
2. `msbuild /t: Restore`

Top error:
![top error](https://user-images.githubusercontent.com/454813/57386827-2eb85e80-7183-11e9-9286-e0b11c0e7a69.png)

Build log:
```
Error occurred while restoring NuGet packages: The operation failed as details for project StackOverflow.Localization could not be loaded.
1>------ Build started: Project: StackOverflow.Common, Configuration: DebugBuildViews Any CPU ------
1>StackOverflow.Common -> C:\code\stackoverflow\StackOverflow.Common\bin\DebugBuildViews\netcoreapp2.2\StackOverflow.Common.dll
1>StackOverflow.Common -> C:\code\stackoverflow\StackOverflow.Common\bin\DebugBuildViews\net462\StackOverflow.Common.dll
2>------ Build started: Project: StackOverflow.Setup, Configuration: Debug Any CPU ------
3>------ Build started: Project: StackOverflow.Tests.Unit, Configuration: Debug Any CPU ------
2>StackOverflow.Setup -> C:\code\stackoverflow\utils\StackOverflow.Setup\bin\Debug\net462\StackOverflow.Setup.exe
3>StackOverflow.Tests.Unit -> C:\code\stackoverflow\tests\StackOverflow.Tests.Unit\bin\Debug\StackOverflow.Tests.Unit.dll
4>------ Build started: Project: StackOverflow.Tests.Integration, Configuration: Debug Any CPU ------
4>StackOverflow.Tests.Integration -> C:\code\stackoverflow\tests\StackOverflow.Tests.Integration\bin\Debug\StackOverflow.Tests.Integration.dll
========== Build: 4 succeeded, 0 failed, 10 up-to-date, 0 skipped ==========
```

Error stack:
```
=====================
5/8/2019 10:37:11 AM
LimitedFunctionality
System.AggregateException: Project system data flow 'PackageRestoreUnconfiguredDataSource: 61263269' closed because of an exception: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.VisualStudio.ProjectSystem.VS.NuGet.PackageRestoreUnconfiguredDataSource.ResolveToolReferenceConflicts(IEnumerable`1 updates)
   at Microsoft.VisualStudio.ProjectSystem.VS.NuGet.PackageRestoreUnconfiguredDataSource.MergeRestoreData(IReadOnlyCollection`1 updates)
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Derive[T,TOut](IProjectVersionedValue`1 projectVersionedValue, Func`2 transform)
   at Microsoft.VisualStudio.ProjectSystem.VS.NuGet.PackageRestoreUnconfiguredDataSource.<LinkExternalInput>b__5_1(IProjectVersionedValue`1 update)
   at Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim`2.TransformBlockSlimSync.ProcessInputAsync(TInput input)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.<ProcessInputQueueAsync>d__5.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.VisualStudio.ProjectSystem.VS.NuGet.PackageRestoreUnconfiguredDataSource.ResolveToolReferenceConflicts(IEnumerable`1 updates)
   at Microsoft.VisualStudio.ProjectSystem.VS.NuGet.PackageRestoreUnconfiguredDataSource.MergeRestoreData(IReadOnlyCollection`1 updates)
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Derive[T,TOut](IProjectVersionedValue`1 projectVersionedValue, Func`2 transform)
   at Microsoft.VisualStudio.ProjectSystem.VS.NuGet.PackageRestoreUnconfiguredDataSource.<LinkExternalInput>b__5_1(IProjectVersionedValue`1 update)
   at Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim`2.TransformBlockSlimSync.ProcessInputAsync(TInput input)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.<ProcessInputQueueAsync>d__5.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.VisualStudio.ProjectSystem.VS.NuGet.PackageRestoreUnconfiguredDataSource.ResolveToolReferenceConflicts(IEnumerable`1 updates)
   at Microsoft.VisualStudio.ProjectSystem.VS.NuGet.PackageRestoreUnconfiguredDataSource.MergeRestoreData(IReadOnlyCollection`1 updates)
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Derive[T,TOut](IProjectVersionedValue`1 projectVersionedValue, Func`2 transform)
   at Microsoft.VisualStudio.ProjectSystem.VS.NuGet.PackageRestoreUnconfiguredDataSource.<LinkExternalInput>b__5_1(IProjectVersionedValue`1 update)
   at Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim`2.TransformBlockSlimSync.ProcessInputAsync(TInput input)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.<ProcessInputQueueAsync>d__5.MoveNext()<---
<---
 ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.VisualStudio.ProjectSystem.VS.NuGet.PackageRestoreUnconfiguredDataSource.ResolveToolReferenceConflicts(IEnumerable`1 updates)
   at Microsoft.VisualStudio.ProjectSystem.VS.NuGet.PackageRestoreUnconfiguredDataSource.MergeRestoreData(IReadOnlyCollection`1 updates)
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Derive[T,TOut](IProjectVersionedValue`1 projectVersionedValue, Func`2 transform)
   at Microsoft.VisualStudio.ProjectSystem.VS.NuGet.PackageRestoreUnconfiguredDataSource.<LinkExternalInput>b__5_1(IProjectVersionedValue`1 update)
   at Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim`2.TransformBlockSlimSync.ProcessInputAsync(TInput input)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.<ProcessInputQueueAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__action|0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.VisualStudio.ProjectSystem.VS.NuGet.PackageRestoreUnconfiguredDataSource.ResolveToolReferenceConflicts(IEnumerable`1 updates)
   at Microsoft.VisualStudio.ProjectSystem.VS.NuGet.PackageRestoreUnconfiguredDataSource.MergeRestoreData(IReadOnlyCollection`1 updates)
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Derive[T,TOut](IProjectVersionedValue`1 projectVersionedValue, Func`2 transform)
   at Microsoft.VisualStudio.ProjectSystem.VS.NuGet.PackageRestoreUnconfiguredDataSource.<LinkExternalInput>b__5_1(IProjectVersionedValue`1 update)
   at Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim`2.TransformBlockSlimSync.ProcessInputAsync(TInput input)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.<ProcessInputQueueAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__action|0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )<---
===================
```
The `StackOverflow.Localization.csproj` that's erroring:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>StackOverflow.Localization</AssemblyName>
    <TargetFrameworks>net462;netcoreapp2.2</TargetFrameworks>
    <EnglishOnly Condition=" '$(EnglishOnly)' == '' ">false</EnglishOnly>
    <LocalizedStringsConnectionString></LocalizedStringsConnectionString>
  </PropertyGroup>
  <Target Name="SetEnglishOnlyConstant" BeforeTargets="CoreCompile" Condition=" '$(EnglishOnly)' == 'true' ">
    <PropertyGroup>
      <DefineConstants>$(DefineConstants);ENGLISH_ONLY</DefineConstants>
    </PropertyGroup>
  </Target>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net462' ">
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Core" />
    <Reference Include="System.Data" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" Version="1.50.7" />
    <PackageReference Include="FastMember" Version="1.4.1" />
    <PackageReference Include="Jil" Version="2.17.0" />
    <PackageReference Include="MiniProfiler.Shared" Version="4.0.165" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.1" />
    <PackageReference Include="StackExchange.MoonSpeak.Shared" Version="5.0.14" />
    <PackageReference Include="StackExchange.Network" Version="1.1.16" />
    <PackageReference Include="Microsoft.Build.Framework" Version="15.9.20" PrivateAssets="all" />
    <DotNetCliToolReference Include="Dotnet.Script" Version="0.28.0" PrivateAssets="all" />
  </ItemGroup>

  <Target Name="_CleanPrecompiledDictionary" AfterTargets="Clean">
    <ItemGroup>
      <_PrecompiledDictionaryFiles Include="$(IntermediateOutputPath)MoonSpeak\PrecompiledLocalizationDictionary.*" />
    </ItemGroup>
    <Delete Files="@(_PrecompiledDictionaryFiles)" />
  </Target>
  <Target Name="_IncludePrecompiledDictionary" Condition="'$(Configuration)' != 'Local'" AfterTargets="BeforeCompile" BeforeTargets="CoreCompile" DependsOnTargets="_GeneratePrecompiledDictionary">
    <ItemGroup>
      <Compile Include="$(IntermediateOutputPath)MoonSpeak\PrecompiledLocalizationDictionary.cs" />
    </ItemGroup>
  </Target>
  <Target Name="_GeneratePrecompiledDictionary" Condition="'$(Configuration)' != 'Local'" Inputs="$(IntermediateOutputPath)MoonSpeak\PrecompiledLocalizationDictionary.lock;PrecompiledLocalizationDictionary.Generator.csx;$(MSBuildThisFilePath)" Outputs="$(IntermediateOutputPath)MoonSpeak\PrecompiledLocalizationDictionary.cs">
    <!-- copy the .csx to the intermediate path (obj/$(Configuration)/...), so that dotnet-script can run them in parallel for each framework specific build -->
    <Copy SourceFiles="PrecompiledLocalizationDictionary.Generator.csx" DestinationFolder="$(IntermediateOutputPath)MoonSpeak\" SkipUnchangedFiles="true" />
    <Exec ConsoleToMSBuild="true" Command="dotnet script --verbosity:d $(IntermediateOutputPath)MoonSpeak\PrecompiledLocalizationDictionary.Generator.csx &quot;$(LocalizedStringsConnectionString)&quot; &quot;$(IntermediateOutputPath)MoonSpeak\PrecompiledLocalizationDictionary.cs&quot; &quot;$(IntermediateOutputPath)MoonSpeak\PrecompiledLocalizationDictionary.lock&quot;">
      <Output TaskParameter="ConsoleOutput" PropertyName="_ConsoleOutput" />
    </Exec>
    <Message Text="$(_ConsoleOutput)" />
  </Target>
</Project>
```

[Link to Twitter thread with some context](https://twitter.com/davkean/status/1126143983086739459)

Please feel free to edit this post with more info...since I'm not sure of the cause, just relaying all the info I have!

**Comment by NickCraver** [comment]
cc @davkean

**Comment by davkean** [comment]
The repro for this is a multi-TFM project with a tool reference. We're trying to handle/merge this case, but clearly that logic is broken.

**Comment by davkean** [comment]
@NickCraver I _think_ a workaround would be to put TFM condition on the tool reference.

**Comment by rrelyea** [comment]
Dotclitoolrefernces are not as strategic as they once were.

They are also inefficient- they cause another restore to be required in this case for the project.

Ideally we fix this case, but might be interesting to understand if this tool can move to a dotnet global tool, or other???

**Comment by NickCraver** [comment]
The main problem with global tools is they're not so friendly with shared build servers. We're flexible to changing this in some way to make it work, there are just issues with the fundamentals of global tools at the moment. Pinging @m0sa on the Stack side to chime in here as well :)

**Comment by m0sa** [comment]
Ideally we could just add those tools at the solution level...

**Comment by NickCraver** [comment]
Putting a crazy TFM does indeed change the issue, for example:
```xml
<DotNetCliToolReference Include="Dotnet.Script" Version="0.28.0" PrivateAssets="all" />
```
becoming:
```xml
<DotNetCliToolReference Condition="'$(TargetFramework)' == 'net462' OR '$(TargetFramework)' != 'net462'" Include="Dotnet.Script" Version="0.28.0" PrivateAssets="all" />
```
...does make that project happy. But produces the same error on the very next project that depends on it. That next project has no tools defined in it, just a lot of vanilla `<PackageReference>` with this section being the only special cases:
```xml
  <ItemGroup Condition=" '$(TargetFramework)' == 'net462'">
    <Reference Include="System.Security" />
    <Reference Include="System.Web" />
    <PackageReference Include="Microsoft.AspNet.WebPages" Version="3.2.7" />
    <PackageReference Include="StackExchange.Exceptional" Version="2.0.0" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' != 'net462'">
    <PackageReference Include="Microsoft.AspNetCore.Html.Abstractions" Version="2.2.0" />
    <PackageReference Include="StackExchange.Exceptional.AspNetCore" Version="2.0.0" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="4.5.2" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="4.5.0" />
  </ItemGroup>
```
