### ISSUE TITLE
Perform class rename after file rename crash

### ISSUE THREAD

**Issue by 333fred** [dotnet/project-system#5210]
I encountered this crash after renaming a file, and clicking yes on the refactor popup after the file was renamed. VS Version Int Preview 16.3 Preview 2.0 29128.8.

Probably important details about the project:
* I was in the middle of moving namespaces around, so some files were in one namespace and the file I renamed was in a different namespace. Those old files had errors in them as they didn't import the new namespace.
* There is another enum in the same file as this class.

<details>

```
=====================
7/30/2019 11:20:38
Recoverable
System.AggregateException: One or more errors occurred. ---> System.NotImplementedException: Not implemented (Exception from HRESULT: 0x80004001 (E_NOTIMPL))
   at EnvDTE.Project.get_FullName()
   at Microsoft.VisualStudio.ProjectSystem.VS.Refactor.VisualStudioRefactorNotifyService.Instance.<TryGetProjectFromPathAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Refactor.VisualStudioRefactorNotifyService.Instance.<GetProjectHierarchy>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Refactor.VisualStudioRefactorNotifyService.Instance.<OnBeforeGlobalSymbolRenamedAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Refactor.VisualStudioRefactorNotifyService.<OnBeforeGlobalSymbolRenamedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Rename.Renamer.<NotifyBeforeRename>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Rename.Renamer.<>c__DisplayClass12_1.<<HandleRenameAsync>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.<>c__DisplayClass13_1`1.<<LoadedProjectAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Rename.Renamer.<>c__DisplayClass12_0.<<HandleRenameAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.ProjectSystem.VS.Waiting.VisualStudioWaitIndicator.Instance.<>c__DisplayClass10_0`1.<WaitForAsyncFunctionWithResult>b__0(CancellationToken token)
   at Microsoft.VisualStudio.ProjectSystem.VS.Waiting.VisualStudioWaitIndicator.Instance.WaitForOperationImpl[T](String title, String message, Boolean allowCancel, Func`2 function)
   at Microsoft.VisualStudio.ProjectSystem.VS.Waiting.VisualStudioWaitIndicator.Instance.WaitForAsyncFunctionWithResult[T](String title, String message, Boolean allowCancel, Func`2 asyncFunction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Waiting.VisualStudioWaitIndicator.WaitForAsyncFunctionWithResult[T](String title, String message, Boolean allowCancel, Func`2 asyncFunction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Rename.Renamer.<HandleRenameAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.<>c__DisplayClass32_1.<<Fork>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__action|0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NotImplementedException: Not implemented (Exception from HRESULT: 0x80004001 (E_NOTIMPL))
   at EnvDTE.Project.get_FullName()
   at Microsoft.VisualStudio.ProjectSystem.VS.Refactor.VisualStudioRefactorNotifyService.Instance.<TryGetProjectFromPathAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Refactor.VisualStudioRefactorNotifyService.Instance.<GetProjectHierarchy>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Refactor.VisualStudioRefactorNotifyService.Instance.<OnBeforeGlobalSymbolRenamedAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Refactor.VisualStudioRefactorNotifyService.<OnBeforeGlobalSymbolRenamedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Rename.Renamer.<NotifyBeforeRename>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Rename.Renamer.<>c__DisplayClass12_1.<<HandleRenameAsync>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.<>c__DisplayClass13_1`1.<<LoadedProjectAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Rename.Renamer.<>c__DisplayClass12_0.<<HandleRenameAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.ProjectSystem.VS.Waiting.VisualStudioWaitIndicator.Instance.<>c__DisplayClass10_0`1.<WaitForAsyncFunctionWithResult>b__0(CancellationToken token)
   at Microsoft.VisualStudio.ProjectSystem.VS.Waiting.VisualStudioWaitIndicator.Instance.WaitForOperationImpl[T](String title, String message, Boolean allowCancel, Func`2 function)
   at Microsoft.VisualStudio.ProjectSystem.VS.Waiting.VisualStudioWaitIndicator.Instance.WaitForAsyncFunctionWithResult[T](String title, String message, Boolean allowCancel, Func`2 asyncFunction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Waiting.VisualStudioWaitIndicator.WaitForAsyncFunctionWithResult[T](String title, String message, Boolean allowCancel, Func`2 asyncFunction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Rename.Renamer.<HandleRenameAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.<>c__DisplayClass32_1.<<Fork>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__action|0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )<---

===================

```

</details>

**Comment by jmarolf** [comment]
@333fred 	this _crashed_ VS? I thought it would just pop a dialog in this case (we should still fix this though).

**Comment by 333fred** [comment]
@jmarolf No, it pops a dialog. Sorry for the confusing wording, the rename crashed which was relatively gracefully handled.
