### ISSUE TITLE
Opt-out of Partial Load Mode for the App Designer

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#5317]
Currently the App Designer (project properties) is opted in to being deferred for Partial Load Mode, because the Resources editor that it hosts needs to be deferred. If it is opted out now the Resources tab errors with the following:

```
An error occurred trying to load the page.
Member not found. (Exception from HRESULT: 0x80020003 (DISP_E_MEMBERNOTFOUND))


[SHOWN IN DEBUG ONLY] STACK TRACE:
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.ErrorHandler.ThrowOnFailure(Int32 hr)
   at Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerPanel.CreateDesigner()
   at Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerPanel.ShowDesigner(Boolean Show)
   at Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerView.ShowTab(Int32 Index, Boolean ForceShow, Boolean ForceActivate)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

We should see if we can change the code here so that the Resources tab shows the same waiting UI as is shown if the user opens the Resources file themselves:
![image](https://user-images.githubusercontent.com/754264/63232018-e5d67280-c266-11e9-9c52-8c51b111c14c.png)

**Comment by davkean** [comment]
Triage: This is figuring out what pages don't actually need design-time build results and stop blocking opening the AppDesigner while PLM/operation progress is in progress, and block pages that actually need operation progress.

**Comment by davidwengier** [comment]
Random notes found while debugging other:

* We need to opt both the ApplicationDesignerEditorFactory and PropPageDesignerEditorFactory out of PLM
* We need to have our own flag in the individual designer tabs to flag whether they need to wait for intellisense
* In the AppDesignerPanel.CreateDesigner method (or similar) we would check that flag to go down one of two paths:
  * If the flag is false, then continue as normal
  * If the flag is true, it means wait for intellisense, which means the CreateDesigner method should create the PartialLoadWindowFrame somehow.
    * It maybe be able to let the shell do it (can we temporarily have `DeferUntilIntellisenseIsReady()` [here](http://index/?query=%60DeferUntilIntellisenseIsReady()&rightProject=VS(Repo)&file=src%5Cenv%5Cmsenv%5Ccore%5Cvsshlsvc.cpp&line=7749) return true?)
    * We show the PartialLoadWindowFrame and hook up to the OnFrameViewReplaced event on the frame, and then show the real content at that point

**Comment by davidwengier** [comment]
Re: opting individual pages into defering, letting the shell do it will definitely be the easiest, we just have to come up with a way for that to happen. We can simply create a second PropPageDesignerEditorFactory that opts-in, and have specific property pages use that instead of the current factory, which opts out. The issue is knowing which pages to do it for, as they are deliberately lazy-loaded so its not trivial to read information from them.

A new registry entry under `[$RootKey$\PropertyPages\{..page guid..}]` for `DeferUntilIntellisenseReady=1` might be the easiest way to go.
