### ISSUE TITLE
TempPEManager faults when rules are missing

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#5341]
**Visual Studio Version**:

**Summary**:

**Steps to Reproduce**:

1. 

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

</Project>
```
2. Change SDK to something random and save

Expected: No fault
Actual: 

```
8/22/2019 6:21:37 PM
LimitedFunctionality
System.AggregateException: One or more errors occurred. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Microsoft.VisualStudio.ProjectSystem.VS.TempPE.TempPEBuildManager.PreprocessAsync(IProjectVersionedValue`1 input, DesignTimeInputsDelta previousOutput)
   at Microsoft.VisualStudio.ProjectSystem.VS.ProjectHostBridge`3.<>c__DisplayClass49_0.<<InitializeCoreAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim`2.TransformManyBlockSlimAsync.<ProcessInputAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.<ProcessInputQueueAsync>d__5.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Microsoft.VisualStudio.ProjectSystem.VS.TempPE.TempPEBuildManager.PreprocessAsync(IProjectVersionedValue`1 input, DesignTimeInputsDelta previousOutput)
   at Microsoft.VisualStudio.ProjectSystem.VS.ProjectHostBridge`3.<>c__DisplayClass49_0.<<InitializeCoreAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim`2.TransformManyBlockSlimAsync.<ProcessInputAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.<ProcessInputQueueAsync>d__5.MoveNext()<---
```

**Comment by davkean** [comment]
tag @davidwengier

**Comment by davidwengier** [comment]
Fixed with https://github.com/dotnet/project-system/pull/5371
