### ISSUE TITLE
ProjectReference to a Project with TargetType=module crashes VS

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/project-system#5380]
- Create a Project with `TargetType=module`
- `ProjectReference` it from another project
- Open the projects from VS. 

Observed: VS will crash. 

```
$exception
{"Can't create a reference to a module."}
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233067
    HelpLink: null
    IPForWatsonBuckets: 0x2a586a41
    InnerException: null
    IsTransient: false
    Message: "Can't create a reference to a module."
    RemoteStackTrace: null
    Source: "Microsoft.CodeAnalysis"
    StackTrace: "   at Microsoft.CodeAnalysis.CompilationReference.GetProperties(Compilation compilation, ImmutableArray`1 aliases, Boolean embedInteropTypes)\r\n   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ToMetadataReference(ImmutableArray`1 aliases, Boolean embedInteropTypes)\r\n   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetMetadataReferenceAsync>d__32.MoveNext() in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 707"
    TargetSite: {Microsoft.CodeAnalysis.MetadataReferenceProperties GetProperties(Microsoft.CodeAnalysis.Compilation, System.Collections.Immutable.ImmutableArray`1[System.String], Boolean)}
    WatsonBuckets: null
    _HResult: -2146233067
    _className: "System.NotSupportedException"
    _data: {System.Collections.ListDictionaryInternal}
    _dynamicMethods: null
    _exceptionMethod: null
    _exceptionMethodString: null
    _helpURL: null
    _innerException: null
    _ipForWatsonBuckets: 0x2a586a41
    _message: "Can't create a reference to a module."
    _remoteStackIndex: 0
    _remoteStackTraceString: null
    _safeSerializationManager: {System.Runtime.Serialization.SafeSerializationManager}
    _source: null
    _stackTrace: {sbyte[96]}
    _stackTraceString: null
    _watsonBuckets: null
    _xcode: -532462766
    _xptrs: 0x00000000
```

```
"System.NotSupportedException: Can't create a reference to a module
at Microsoft.CodeAnalysis.CompilationReference.GetProperties(Compilation compilation, ImmutableArray`1 aliases, Boolean embedInteropTypes)
at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ToMetadataReference(ImmutableArray`1 aliases, Boolean embedInteropTypes)
at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetMetadataReferenceAsync>d__32.MoveNext() in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs:line 707"
```

This is what I'm seeing in `CompilationReference.cs`:

```C#
        internal static MetadataReferenceProperties GetProperties(Compilation compilation, ImmutableArray<string> aliases, bool embedInteropTypes)
        {
            if (compilation == null)
            {
                throw new ArgumentNullException(nameof(compilation));
            }

            if (compilation.IsSubmission)
            {
                throw new NotSupportedException(CodeAnalysisResources.CannotCreateReferenceToSubmission);
            }

            if (compilation.Options.OutputKind == OutputKind.NetModule)
            {
                throw new NotSupportedException(CodeAnalysisResources.CannotCreateReferenceToModule);
            }

            return new MetadataReferenceProperties(MetadataImageKind.Assembly, aliases, embedInteropTypes);
        }
```

[dotnet/wpf](https://github.com/dotnet/wpf) repo is planning on using netmodules it as part of product-binaries, and this would imply that the solution in the repo can not be used/built in VS. It would be great if netmodule-references can be supported in Dev16.4. 

[module-crash-repro.zip](https://github.com/dotnet/project-system/files/3544533/module-crash-repro.zip) 

/cc @rladuca
/cc @tgani-msft, @dotnet/wpf-developers

**Comment by tgani-msft** [comment]
+ @Olga Arkhipova<mailto:olgaark@microsoft.com>
+ @Nick Guerrera<mailto:Nick.Guerrera@microsoft.com>

who're working on the project system support for C++/CLI for .NET Core.

________________________________

**Comment by drewnoakes** [comment]
Is this a project system issue? The code in question is part of Roslyn:

https://github.com/dotnet/roslyn/blob/38559118951cfc4599711141b9bf3bb7fd7b2dc6/src/Compilers/Core/Portable/MetadataReference/CompilationReference.cs#L25-L43

**Comment by davkean** [comment]
What's the expectation here? Clearly we should do better than a crash - but a reference to a module isn't valid.

**Comment by davkean** [comment]
Note that reference is marked as so:

```
    <ProjectReference Include="..\module\module.csproj">
       <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
       <OutputItemType>AddModules</OutputItemType>
    </ProjectReference>
```

Which should mean that it isn't passed a reference, so we have a couple of bugs:

1) We shouldn't crash if someone doesn't specify `ReferenceOutputAssembly`
2) We shouldn't be passing this module to Roslyn when `ReferenceOutputAssembly` is specified.

Probably a combination of Roslyn, Project and MSBuild bugs.
