### ISSUE TITLE
Imports tree should support duplicate node names

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#5711]
Originally this was an error report (see below). That error has now been fixed, but duplicate nodes are hidden. Instead, we should show all nodes so that the import tree is not misleading.

---

A project file that imports two files with the same file name causes this exception:

```
System.ArgumentException: An item with the caption "MicroBuild.Plugins.SwixBuild.props"(ProjectTreeFlags: FileOnDisk ProjectImport) already exists under parent "MicroBuild.Core.props" with the same sort order as the item being added.
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectTree.Add(UnattachedProjectTreeNode node)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectTree.Add(IProjectTree subtree)
   at Microsoft.VisualStudio.ProjectSystem.Tree.ProjectImports.ImportTreeProvider.<set_ShowAllFiles>g__SyncNode|20_8(IReadOnlyList`1 imports, IProjectTree tree)
   at Microsoft.VisualStudio.ProjectSystem.Tree.ProjectImports.ImportTreeProvider.<set_ShowAllFiles>g__SyncNode|20_8(IReadOnlyList`1 imports, IProjectTree tree)
   at Microsoft.VisualStudio.ProjectSystem.Tree.ProjectImports.ImportTreeProvider.<set_ShowAllFiles>g__SyncNode|20_8(IReadOnlyList`1 imports, IProjectTree tree)
   at Microsoft.VisualStudio.ProjectSystem.Tree.ProjectImports.ImportTreeProvider.<set_ShowAllFiles>g__SyncNode|20_8(IReadOnlyList`1 imports, IProjectTree tree)
   at Microsoft.VisualStudio.ProjectSystem.Tree.ProjectImports.ImportTreeProvider.<set_ShowAllFiles>g__SyncNode|20_8(IReadOnlyList`1 imports, IProjectTree tree)
   at Microsoft.VisualStudio.ProjectSystem.Tree.ProjectImports.ImportTreeProvider.<>c__DisplayClass20_0.<set_ShowAllFiles>b__7(IProjectVersionedValue`1 currentTree, ConfiguredProjectExports configuredProjectExports, CancellationToken token)
```

Names should be disambiguated to be made unique.

Repro: https://devdiv.visualstudio.com/DevDiv/_git/VS-Platform?path=%2Fsrc%2FEditor

**Comment by drewnoakes** [comment]
The current state of this is that duplicates are _hidden_. This fixes the exception we saw, but makes the tree misleading.

I'm re-opening this to track the feature gap. 

#5736 fixed the problem completely in its first revision, however that required enabling "display order" support across the whole tree. Instead, we should do this only at the subtree level. This requires CPS changes, and a PR is open with a proposed change to support this: https://dev.azure.com/devdiv/DevDiv/_git/CPS/pullrequest/220752
