### ISSUE TITLE
Visual Studio ran into an unexpected problem error when right clicking on .NET Core 3.0 project to edit

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5772]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/872024/visual-studio-ran-into-an-unexpected-problem-error.html). Please vote and comment there to make sure your voice is heard._

---
[regression] [worked-in:Previous dogfood version]
1. Create a new .NET Core 3.0 WPF project
2. Right-click on project and select "Edit"

Result:

Info bar saying "Visual Studio ran into an unexpected problem with '<projectname>'. You may need to reload the solution if you continue to see errors.

The log is:

```
=====================
1/2/2020 3:14:45 AM
Recoverable
System.Runtime.InteropServices.COMException (0x8000000A): There is no editor available for 'C:\Users\ansonh\source\repos\AudibleToGoodReadsSync\AudibleToGoodReadsSync\AudibleToGoodReadsSync.csproj'.

Make sure the application for the file type (.csproj) is installed.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.ErrorHandler.ThrowOnFailure(Int32 hr, Int32[] expectedHRFailure)
   at Microsoft.VisualStudio.Shell.VsShellUtilities.GetTextView(IVsWindowFrame windowFrame)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.ProjectFrameOpenCloseListener.FrameEventsLifetime.IsTextEditorForOurProjectFile(IVsWindowFrame frame)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.ProjectFrameOpenCloseListener.FrameEventsLifetime.<>c__DisplayClass20_0. <<Microsoft-VisualStudio-Shell-Interop-IVsWindowFrameEvents-OnFrameDestroyed>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously[T](Func`1 asyncAction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.ProjectFrameOpenCloseListener.FrameEventsLifetime.<>c__DisplayClass24_0. <HrAsyncInvoke>b__0()
   at Microsoft.VisualStudio.ProjectSystem.VS.HResult.Invoke(Func`1 action, IServiceProvider vsShellServiceProvider, IProjectFaultHandlerService projectFaultHandlerService, UnconfiguredProject project)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0. <SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0. <Guard>g__action|0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
===================
```

---
#### Visual Studio Feedback System on 1/2/2020, 06:02 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by davidwengier** [comment]
The customers registry is missing the registration for `.csproj` to use the XML editor factory, and the registration for the diff view, that we set up here:
https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ProjectTypeRegistration.cs#L43-L44

There was a slight gap between the CPS insertion for the change that could have shown this error, and the project system insertion that added the registration, but the customer is on a newer version than both. Additionally the registry does have the package registration itself.

CPS: 29520.190
Project System: 29521.83
Customer: 29631.39

I have a clean install of 29708.233 that doesn't exhibit the issue, but I need to check the registry of that install just in case.

**Comment by Se7enstars** [comment]
[same](https://github.com/dotnet/project-system/issues/5772#issue-547011937) problem on opening project (i only updated VS2019 to lastest ver)

**Comment by drewnoakes** [comment]
@Se7enstars please try repairing your VS installation. If the problem persists, open a new issue. Thanks.
