### ISSUE TITLE
Project fault in editor listener while closing a solution

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#5848]
Version 16.5.0 Preview 3.0 [29723.129.master]

No repro, but this faulted when this I closed a solution:

```
System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.ErrorHandler.ThrowOnFailure(Int32 hr, Int32[] expectedHRFailure)
   at Microsoft.VisualStudio.Shell.VsShellUtilities.GetTextView(IVsWindowFrame windowFrame)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.ProjectFrameOpenCloseListener.FrameEventsLifetime.IsTextEditorForOurProjectFile(IVsWindowFrame frame)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.ProjectFrameOpenCloseListener.FrameEventsLifetime.<>c__DisplayClass20_0.<<Microsoft-VisualStudio-Shell-Interop-IVsWindowFrameEvents-OnFrameDestroyed>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously[T](Func`1 asyncAction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.ProjectFrameOpenCloseListener.FrameEventsLifetime.<>c__DisplayClass24_0.<HrAsyncInvoke>b__0()
   at Microsoft.VisualStudio.ProjectSystem.VS.HResult.Invoke(Func`1 action, IServiceProvider vsShellServiceProvider, IProjectFaultHandlerService projectFaultHandlerService, UnconfiguredProject project)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__action|0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
===================
```

**Comment by davkean** [comment]
tag @davidwengier

**Comment by davkean** [comment]
I hit this again when I switched ffrom TargetFramework -> TargetFrameworks and choose reload when prompted while the editor was open.

**Comment by davidwengier** [comment]
How does this manifest? Gold bar? event viewer? I'm not seeing anything when I do the above, though I do get the yellow bar for nuget nomination so maybe its being hidden.

I think I'll just ignore any COM exceptions from GetTextView though, as it will throw them even in normal operation at times.

**Comment by davkean** [comment]
Gold bar.

**Comment by davidwengier** [comment]
Internal PR: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/226676

**Comment by davidwengier** [comment]
PR Completed
