### ISSUE TITLE
 "View Code/F7" should not be present for sub-nodes

### ISSUE THREAD

**Issue by jmarolf** [dotnet/project-system#5948]
**Summary**:
Form1.resx have extra "View Code/ View Designer/ Copy/ Delete / Rename" items in CPS.

**Steps to reproduce:**
1.	Create a .NET Core app, then double click the Form1.cs file to show the Form designer, and the Form1.resx generated.
2.	Right Click the Form1.resx, choose the "View Code/F7".

**Expect Result:**
The "View Code/F7" is not available in the sub-nodes for resource files

**Actual Result：**
After the step2, the "View Code/F7" is not working.
![1](https://user-images.githubusercontent.com/38325459/69129679-dbd44200-0ae9-11ea-84ba-50b497917496.png)

**User Impact**:

**Comment by davkean** [comment]
What does step 3 mean to the bug?

**Comment by Amy-Li03** [comment]
In Dev17 latest build: 17.0.0 Preview 5.0 [31716.426.main], after right click "View Code" on Form1.resx, following dialog will pop up:
![image](https://user-images.githubusercontent.com/62929087/133748734-8be4b7a4-f527-41b5-81b8-6ecbf00ea7d8.png)
System.AggregateException: One or more errors occurred. ---> System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'Microsoft.VisualStudio.Shell.Interop.IVsEditorFactory'.
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.FileDocumentManager.<OpenAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__Action|0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'Microsoft.VisualStudio.Shell.Interop.IVsEditorFactory'.
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.FileDocumentManager.<OpenAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__Action|0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )<---

**Comment by drewnoakes** [comment]
@Amy-Li03 nice find! I've moved it to a new issue as that's unrelated to the above request.
