### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException on first opening of a solution

### ISSUE THREAD

**Issue by vritant24** [dotnet/project-system#6669]
**Visual Studio Version**:
Latest Main

**Summary**:
The following error occurs when the given repro steps are followed
```
=====================

10/9/2020 6:56:01 AM

Recoverable

System.Collections.Generic.KeyNotFoundException: The given key '288' was not present in the dictionary.

   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)

   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.TreeService.TreeData.NodeFromIdentity(IntPtr identity)

   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.TreeService.TreeData.FireProjectItemsEventsItemAddedOrRemovedImpl(IVsExtensibility2 vsExtensibility2, SimpleItemNode simpleItemNode, IProjectTree projectTree, Builder pendingList, Boolean isAdded)

   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.TreeService.TreeData.FireProjectItemsEventsItemAddedOrRemoved(SimpleItemNode simpleItemNode, IProjectTree projectTree, Builder pendingList, Boolean isAdded)

   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.TreeService.TreeData.OnAfterApplyTree(TreeData previouslyAppliedOutput, ImmutableDictionary`2 renames, TreeUIState treeUIState)

   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.TreeService.ApplyAsync(TreeData value)

--- End of stack trace from previous location where exception was thrown ---

   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)

   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()

   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__action|0()

   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )

===================
```

**Steps to Reproduce**:
Another steps to reproduce:
1. Git clone https://github.com/Microsoft/vs-streamjsonrpc
2. Install .NET Core SDK 3.1.102 from https://dotnet.microsoft.com/download/dotnet-core/3.1 
3.Open <ClonedFolder>\vs-streamjsonrpc\src\StreamJsonRpc.sln

**More cases**:
This was discovered when we try to add a Fakes Assembly to a new solution as part of vendor testing. A memdump can be found [here](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1228545)

**Comment by vritant24** [comment]
Does not repro in the latest main anymore

**Comment by davkean** [comment]
This was fixed by the CPS team.
