### ISSUE TITLE
Inserting the default Settings.settings file fails in a .NET 5 Visual Basic Application Framework WinForms App

### ISSUE THREAD

**Issue by KlausLoeffelmann** [dotnet/project-system#6783]
**Visual Studio Version**:
\> 16.8

**Summary**:
In an empty .NET 5 WinForms VB App, inserting the Default Settings.settings file via the Project Designer fails.

**Steps to Reproduce**:

1. Create a new .NET 5 VB WinForms App.
2. Open the Project Designer
3. Switch to the Settings Tab and click on the LinkLabel 'This project does not contain a default settings file. Click here to create one'.

**Expected Behavior**:
Settings file should be inserted.

**Actual Behavior**:
Creating the file fails with 'The system cannot find the file specified. (Exception from HRESULT: 0x80070002)' in `SpecialFileCustomView.CreateNewSpecialFile` and later in `EnvDT80.Solution2.GetProjectItemTemplate`. 
(See also attached stack trace).

**User Impact**:
Settings files are not interactively usable for VB Users in an WinForms app.
(FWIW, this may be not limited to WinForms.)

Stack Trace:
```
   at EnvDTE80.Solution2.GetProjectItemTemplate(String TemplateName, String Language)
   at Microsoft.VisualStudio.ProjectSystem.VS.CreateFileFromTemplateService.<CreateFileAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.SpecialFileProviders.AbstractFindByNameUnderAppDesignerSpecialFileProvider.<CreateFileAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.SpecialFileProviders.AbstractSpecialFileProvider.<CreateDefaultFileAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.SpecialFileProviders.AbstractSpecialFileProvider.<GetFileAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass501_0.<<GetFile>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously(Func`1 asyncAction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass566_0.<HrInvoke>b__0()
   at Microsoft.VisualStudio.ProjectSystem.VS.HResult.<>c__DisplayClass37_0.<Invoke>b__0()
   at Microsoft.VisualStudio.ProjectSystem.VS.HResult.Invoke(Func`1 action, IServiceProvider vsShellServiceProvider, IProjectFaultHandlerService projectFaultHandlerService, UnconfiguredProject project)
```

**Comment by swesonga** [comment]
This is a dup of https://developercommunity2.visualstudio.com/t/Default-VBNet-Core-WinForms-Project-get/1174597 (with PR https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/292088 in progress)

**Comment by jjmew** [comment]
@KlausLoeffelmann this has already been fixed by https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/292088
