### ISSUE TITLE
Updating the Default Settings file in a WinForms .NET 5 Visual Basic app fails.

### ISSUE THREAD

**Issue by KlausLoeffelmann** [dotnet/project-system#6784]
**Visual Studio Version**:
\>=16.8
**Summary**:
Attempting to save after changing a value in the Default Settings file of a WinForms .NET 5 Visual Basic app fails.

**Steps to Reproduce**:

1. Create a new .NET 5 WinForms App.
2. Insert a new App.Config to the project by chosing Add/New Items and General/Application Configuration File.
3. Show All Files in the Solution Explorer and select the My Project branch.
4. Insert a new Settings file to the project by choosing Add/New Items and General/Settings File. Make sure to rename the Name to _Settings.settings_.
5. In the Settings editor, which appears now, add a value and try to save the settings.

**Expected Behavior**:
Settings file should be written, settings designer code be generated.
**Actual Behavior**:
![image](https://user-images.githubusercontent.com/9663150/101575006-b97bc380-398d-11eb-93a6-12d29a1c9f27.png)

Exception:
'An error occurred creating the configuration section handler for userSettings/VbWinForms5EventTest.Settings: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.'

**User Impact**:
Interactively using the settings designer in a .NET 5 VB WinForms App is not possible.

Stack Trace:
```
   at System.Configuration.BaseConfigurationRecord.FindAndEnsureFactoryRecord(String configKey, Boolean& isRootDeclaredHere)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at Microsoft.VisualStudio.Shell.Design.Serialization.ConfigurationHelperService.GetConfigSection(Configuration config, String sectionName, Boolean isUserScoped, Boolean declare)
   at Microsoft.VisualStudio.Shell.Design.Serialization.ConfigurationHelperService.ReadSettings(ExeConfigurationFileMap fileMap, ConfigurationUserLevel userLevel, DocData appConfigDocData, String sectionName, Boolean isUserScoped, SettingsPropertyCollection settings)
   at Microsoft.VisualStudio.Editors.SettingsDesigner.AppConfigSerializer.SynchronizeUserConfig(String SectionName, IVsHierarchy Hierarchy, ConfigurationHelperService ConfigHelperService, Dictionary`2 SettingsTheDesignerKnownsAbout, DocData AppConfigDocData) in D:\Git\project-system\src\Microsoft.VisualStudio.Editors\SettingsDesigner\AppConfigSerializer.vb:line 402
   at Microsoft.VisualStudio.Editors.SettingsDesigner.AppConfigSerializer.SynchronizeUserConfig(String SectionName, IVsHierarchy Hierarchy, ConfigurationHelperService ConfigHelperService, DesignTimeSettings Settings, DocData AppConfigDocData) in D:\Git\project-system\src\Microsoft.VisualStudio.Editors\SettingsDesigner\AppConfigSerializer.vb:line 347
   at Microsoft.VisualStudio.Editors.SettingsDesigner.AppConfigSerializer.Serialize(DesignTimeSettings Settings, SettingsTypeCache typeCache, SettingsValueCache valueCache, String SectionName, DocData AppConfigDocData, IVsHierarchy Hierarchy, Boolean ShouldSynchronizeUserConfig) in D:\Git\project-system\src\Microsoft.VisualStudio.Editors\SettingsDesigner\AppConfigSerializer.vb:line 320
```

**Comment by tmeschter** [comment]
The issue here is that we've serialized a `System.Configuration.ClientSettingsSection` containing the user settings to the app.config file. VS is a .NET Framework 4.8 app, but we know the WinForms app is targeting .NET 5, so we've used the `Microsoft.VSDesigner.MultiTargetService` to map to the .NET 5 type name (including the full assembly name) and that is what has been persisted in the file.

The problem is when we want to _read_ that data later. The .NET Framework 4.8 (running in VS) doesn't know anything about that the .NET 5 assembly, and so it can't deserialize it for us.

The `MultiTargetService` was designed for a world where VS was always running on the latest .NET Framework, though you might be targeting an older version for you app. Since VS was always using the latest Framework, it could count on type forwarders being in place such that the runtime would always be able to deserialize types from previous versions. But now VS is using an older Framework version, and that design no longer works.

The only solution I can think of is to have a variant of the `MultiTargetService` that always returns .NET Framework 4.8 types names, regardless of the target type of the app, on the assumption that all .NET 5, 6, and 7 (and beyond) runtimes will have the appropriate type forwarding in place. The .NET Framework 4.8 version of a type name would effectively become the canonical version.

**Comment by tmeschter** [comment]
My proposed solution will not work here. The System.Configuration shim assembly in .NET 5 does not have a type forwarder for `System.Configuration.ClientSettingsSection`, though it does have one for the base type, `System.Configuration.ConfigurationSection`.

**Comment by Perpete** [comment]
Hello,
By creating a first project with WPF in VB with .net 5 under the Visual Studio 16.11.1 version, I noticed the same issue while creating and using user settings in app.config.

When we add or modify parameters or values of these parameters and save the new information, we get the display of an error message.

**Message :**
_'An error occurred while saving values to the app.config file. This file may be damaged or contains invalid XML code. '_

![2021-08-20 17_02_51-WpfApp5 - Microsoft Visual Studio](https://user-images.githubusercontent.com/66659162/130313298-8e8ec654-12a7-4afe-a738-b76a16f859cb.png)

When using a parameter reading using one of the following instructions
lbEssai.Content = My.MySettings.Default.Essai or lbEssai.Content = My.Settings.Essai,
I have an error in the Settings.Designer.vb file.

![2021-08-20 17_09_54-WpfApp5 (Débogage) - Microsoft Visual Studio](https://user-images.githubusercontent.com/66659162/130313344-a87c97c7-221b-4530-a3b8-58838dd3d4fc.png)

Here are the details of the error.

![2021-08-20 17_47_15-_D__Documents_Visual Studio 2019_Projects_IOCenterOPC_DLL_IOCenterOPC_DLL sln - ](https://user-images.githubusercontent.com/66659162/130313364-2edce9d2-3879-452a-8264-162e1f161962.png)

Here is just my test program.

`Class MainWindow

	Private Sub Button_Click(sender As Object, e As RoutedEventArgs)

		lbEssai.Content = My.MySettings.Default.Essai

		lbEssai.Content = My.Settings.Essai
	End Sub

End Class`

The same program in C # works fine.

What is the solution in VB?

**Comment by Perpete** [comment]
Hello,
In the App.config file, I deleted all the contents of the 'system.diagnostics' tag.
I no longer have an error detected in the Settings.Designer.vb file when reading the setting.
The reading of the parameter value is correct.

![2021-08-20 19_27_58-WpfApp5 - Microsoft Visual Studio](https://user-images.githubusercontent.com/66659162/130313517-be78fd86-4139-4620-b26c-31308c96a72a.png)


On the other hand, from the parameter data grid, there is always the display of the error message when adding or modifying the parameters or the values of these parameters when saving the new information.

**Comment by RussKie** [comment]
@melytc @KlausLoeffelmann @KathleenDollard  the diagnostics section is defined in a template under `src/vsproject/Templates/Windows/VisualBasic/ItemTemplates/AppConfigurationInternal` path.

**Comment by RussKie** [comment]
Copying from AB#1388851

Different scenarios with associated steps to reproduce can be found at https://gist.github.com/RussKie/e33dd2ee4dc18a04f9237b6b42db9596

This is a functionality gap that impacts migration scenarios. In essence, whenever Settings.settings are written into an app.config versions must be locked at 4.0.0.0 and not at the current app's TFM:

```xml
    <configSections>

        <sectionGroup name="applicationSettings" type="System.Configuration.ApplicationSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >
            <section name="settings_issue.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
        </sectionGroup>
        <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >
            <section name="settings_issue.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
        </sectionGroup>

    </configSections>
```

**Comment by RussKie** [comment]
## .NET Framework

A brand new VB Windows Forms .NET Framework (4.7.2) app contains the following app.config
![image](https://user-images.githubusercontent.com/4403806/131610861-e8925e2e-f18a-4270-9e9c-cafb889bea05.png)

Adding/modifying settings makes the following changes to the app.config:
![image](https://user-images.githubusercontent.com/4403806/131610993-67c96ab7-663a-4c0e-a5c6-ec2091632636.png)

## .NET

A brand new VB Windows Forms .NET (6.0) app does not contain an app.config. 
A brand new app.config gets created when settings are added (unlike C#, AB#1386445) but the app.settings contains the spurious `system.diagnostics` section:
![image](https://user-images.githubusercontent.com/4403806/131611497-5dc10d43-9684-4186-bf1d-8c66345c17f3.png)

**Comment by RussKie** [comment]
The second key problem is that the types are written against the app's TFM (e.g. net5.0), which is different from the VS TFM (net472), and this makes VS unable to parse the app.config. And it fails here:
https://github.com/dotnet/project-system/blob/648af14095528d140903d64396711f66873be11d/src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsDesignerLoader.vb#L476-L496

Here's what's is being currently serialised (-) instead of what must be serialised (+):
```diff
    <configSections>
-       <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System.Configuration.ConfigurationManager, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" >
+       <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >
-           <section name="WinFormsApp1.My.MySettings" type="System.Configuration.ClientSettingsSection, System.Configuration.ConfigurationManager, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
+           <section name="WinFormsApp1.My.MySettings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
        </sectionGroup>
-       <sectionGroup name="applicationSettings" type="System.Configuration.ApplicationSettingsGroup, System.Configuration.ConfigurationManager, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" >
+       <sectionGroup name="applicationSettings" type="System.Configuration.ApplicationSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >
-           <section name="WinFormsApp1.My.MySettings" type="System.Configuration.ClientSettingsSection, System.Configuration.ConfigurationManager, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" requirePermission="false" />
+           <section name="WinFormsApp1.My.MySettings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
        </sectionGroup>
    </configSections>
```

1. `System.Configuration.ConfigurationManager` -> `System`
2. `Version=5.0.0.0` -> `Version=4.0.0.0`
3. `PublicKeyToken=cc7b13ffcd2ddd51` -> `PublicKeyToken=b77a5c561934e089`

**Comment by RussKie** [comment]
Reopening as the rogue system.diagnostics section is still unaddressed. @KathleenDollard  and @KlausLoeffelmann need to make a call.

**Comment by merriemcgaw** [comment]
@KlausLoeffelmann / @KathleenDollard  a quick ping here to see how we want to proceed (most importantly for .NET 6 apps)

**Comment by KlausLoeffelmann** [comment]
We need to discuss this with @melytc in the upcoming project system/vb sync.

**Comment by melytc** [comment]
Change missing here is removing the `system.diagnostics` content from the VB AppConfiguration template. Closing this in favor of #7448 which needs the same change.

**Comment by ocallesp** [comment]
The PR https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/403807 should handle the issue in `system.diagnostics`
