### ISSUE TITLE
Error while loading project properties - WinUI 3 preview 3 - Packaged Desktop App

### ISSUE THREAD

**Issue by sjb-sjb** [dotnet/project-system#6928]
Opening [this issue](https://github.com/microsoft/microsoft-ui-xaml/issues/4013) here as requested. 

---

Using: Visual Studio Version 16.9.0 Preview 2.0, WinUI 3 preview 3

### Steps to reproduce

1. Create a new project using the "Blank App, Packaged (WinUI in Desktop)" template.
2. Right-click on the Package project and select "Properties" at the bottom of the context menu.

### Expected

Should open the properties window for the project

### Actual

An exception message occurs as follows:

```
An error occurred while loading the project properties editor

System.ArgumentException: Incorrect number of property values given the dimension matrix
Parameter name: properties
at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.PropertyContext..ctor(ConfigurationMatrix configurationMatrix, ImmutableArray`1 properties, IPropertyValueChangeHandler changeHandler, JoinableTaskFactory jtf)
at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.ProjectPropertiesEditor.<.ctor>g__CreatePropertyContext|0_2(IProject project, JoinableTaskFactory jtf)
at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.ProjectPropertiesEditor.<>c__DisplayClass0_0.<<-ctor>g__LoadPropertyContextAsync|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.ProjectPropertiesEditor.<>c__DisplayClass0_0.<<-ctor>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.AsyncLoadContent.<>c__DisplayClass0_0.<b__0>d.MoveNext()
```

**Comment by drewnoakes** [comment]
Workaround is to disable the preview UI by unchecking the two preview features at:

> Tools > Options > Environment > Preview Features > Enable Updated Project Properties UI

---

We need to determine whether we should be showing the new Project Properties UI for WinUI projects, and if so, why the data received for these properties is not correctly specified.

@sjb-sjb is that the full error message? I would have expected a suffix to the error message along the lines of "Expected 2, got 2.".

Internal PR to improve exception message: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/302828

**Comment by drewnoakes** [comment]
To elaborate on this error...

If a project has two configurations (Debug/Release), a single platform (AnyCPU) and two target frameworks (net5.0 and netstandard1.6) then there are four possible combinations of these three dimensions.

The UI code expects the server to provide six values for each property. In this case, a different number is being returned, which causes this exception.

**Comment by drewnoakes** [comment]
Today I installed the latest Project Reunion bits and tried to repro this in the latest internal builds of VS, but was unable to.

![image](https://user-images.githubusercontent.com/350947/115672833-4a789780-a38f-11eb-8565-ef868231cfec.png)

@sjb-sjb can you try this again? Were there any steps you took other than creating a new project and launching the Project Properties UI?

**Comment by sjb-sjb** [comment]
@drewnoakes  sorry I don’t have any cycles that I can put into this right now.

**Comment by drewnoakes** [comment]
Closing as no-repro.
