### ISSUE TITLE
Changing Nav bar in shared projects causes NFW that forces VS restart

### ISSUE THREAD

**Issue by jaredpar** [dotnet/project-system#7399]
**Visual Studio Version**:  

Reproduces in VS 2019.10 and VS 2022 Int Preview

**Summary**:
Changing the project selected in the navigation bar can cause Visual Studio to issue a NFW. This is particularly relevant now because Visual Studio has changed the recommendations for extension authors to use shared projects. Hence this is likely to pop up more and more as extension authors attempt to migrate to VS 2022 (this is in fact how I found it)

https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022#use-shared-projects-for-multi-targeting

**Steps to Reproduce**:

1. Clone VsVim https://github.com/VsVim/VsVim
2. Open VsVim.sln in Visual Studio
3. Open the file `Src\VimEditorHost\VimEditorHost.cs` (really any shared file will do)
4. Type in the file such that Intellisense shows up. This step is important. The bug will not reproduce without it.
5. Change the nav bar from whatever project is selected to a different project

**Expected Behavior**:
The context for the file changes to the specified project

**Actual Behavior**:
A crash dialog appears and user is notified that a non-fatal error occurred. Visual Studio is not very usable at this point and it must be restarted for reasonable development to continue. The error from the error log is the following:

```
=====================
7/14/2021 8:09:39 AM
Recoverable
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: newMkDoc
   at Microsoft.Requires.FailRange(String parameterName, String message)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass479_0.<<TransferItem>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously(Func`1 asyncAction)
   at Microsoft.VisualStudio.ProjectSystem.VS.HResult.<>c__DisplayClass37_0.<Invoke>b__0()
   at Microsoft.VisualStudio.ProjectSystem.VS.HResult.Invoke(Func`1 action, IServiceProvider vsShellServiceProvider, IProjectFaultHandlerService projectFaultHandlerService, UnconfiguredProject project)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__Action|0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
===================
```

**User Impact**:
The user must restart Visual Studio in order to continue their work.

**Comment by drewnoakes** [comment]
Triage notes: All code in this stack is CPS (The .NET Project System is `MS.VS.PS.Managed`).

**Comment by jaredpar** [comment]
Is this being considered for Dev17? It's making it really difficult to develop VS extensions an the moment. The new VS extension approach is pushing everyone to use shared projects. Pretty much every time I need to jump between VS versions (aka change the selection in the nav bar) it's causing VS to NFW and force a restart. 

@madskristensen

**Comment by madskristensen** [comment]
Let's ask @tinaschrepfer?

**Comment by tmeschter** [comment]
I'm going to move this bug over to the CPS team in AzDO.

**Comment by tmeschter** [comment]
Moved to https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1358472.
