### ISSUE TITLE
Setting do not work on NEW VB .Net 5 Winforms application

### ISSUE THREAD

**Issue by paul1956** [dotnet/project-system#7448]
* .NET Core Version:  What I have installed is below
```
Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.0-preview.2.21154.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
Create a new VB WinForm App, that will read settings, add settings, run app and application will crash as below.

![image](https://user-images.githubusercontent.com/12789369/119243280-20470080-bb1a-11eb-9bcc-4c95a6dd18f3.png)
```
System.Configuration.ConfigurationErrorsException
  HResult=0x80131902
  Message=Configuration system failed to initialize
  Source=System.Configuration.ConfigurationManager
  StackTrace:
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   at System.Configuration.ClientConfigurationSystem.PrepareClientConfigSystem(String sectionName)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.RefreshConfig(String sectionName)
   at System.Configuration.ConfigurationManager.RefreshSection(String sectionName)
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at CareLink.My.MySettings.get_username() in C:\Users\PaulM\Source\Repos\CareLink\CareLink\My Project\Settings.Designer.vb:line 62
   at CareLink.LoginForm1.LoginForm1_Load(Object sender, EventArgs e) in C:\Users\PaulM\Source\Repos\CareLink\CareLink\LoginForm1.vb:line 12
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ConfigurationErrorsException: Unrecognized configuration section system.diagnostics. (C:\Users\PaulM\Source\Repos\CareLink\CareLink\bin\Debug\net5.0-windows\CareLink.dll.config line 8)
```

**Expected behavior:**
I can read settings

**Minimal repro:**
Contents of .config file
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <configSections>
        <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System.Configuration.ConfigurationManager, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" >
            <section name="CareLink.My.MySettings" type="System.Configuration.ClientSettingsSection, System.Configuration.ConfigurationManager, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
        </sectionGroup>
    </configSections>
```
Manually deleting system.diagnostics section fixes the issue until a rebuild.
```
    <system.diagnostics>
        <sources>
            <!-- This section defines the logging configuration for My.Application.Log -->
            <source name="DefaultSource" switchName="DefaultSwitch">
                <listeners>
                    <add name="FileLog"/>
                    <!-- Uncomment the below section to write to the Application Event Log -->
                    <!--<add name="EventLog"/>-->
                </listeners>
            </source>
        </sources>
        <switches>
            <add name="DefaultSwitch" value="Information" />
        </switches>
        <sharedListeners>
            <add name="FileLog"
                 type="Microsoft.VisualBasic.Logging.FileLogTraceListener, Microsoft.VisualBasic, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL"
                 initializeData="FileLogWriter"/>
            <!-- Uncomment the below section and replace APPLICATION_NAME with the name of your application to write to the Application Event Log -->
            <!--<add name="EventLog" type="System.Diagnostics.EventLogTraceListener" initializeData="APPLICATION_NAME"/> -->
        </sharedListeners>
    </system.diagnostics>
```
From here down works
```
    <userSettings>
        <CareLink.My.MySettings>
            <setting name="username" serializeAs="String">
                <value />
            </setting>
            <setting name="password" serializeAs="String">
                <value />
            </setting>
        </CareLink.My.MySettings>
    </userSettings>
</configuration>
```

**Comment by eerhardt** [comment]
I was able to reproduce this on a new .NET 5 VB WinForms app. You just need to "Add => New Item" and choose a "Settings" item. Add a new string setting named "username", and then add code to read the "username" property of a "new Settings1" object.

The `system.diagnostics` section isn't a valid app.config section in .NET 5. The runtime doesn't get configured by app.config in .NET 5 like it did in .NET Framework.

cc @swesonga @jjmew

**Comment by danmoseley** [comment]
Hello project system friends, it would be great if you could take a look at this one as it is a migration blocker for some VB customers.

**Comment by jjmew** [comment]
@melytc Can you take a look at this? maybe get some context from @tmeschter

**Comment by danmoseley** [comment]
cc @KathleenDollard this is a case where tooling apparently breaks upgrade of a VB app. It's writing extra stuff to the config that the runtime won't use, so the config system rejects it.

**Comment by elGuille-info** [comment]
As @paul1956 I have the same issues in .NET 6 and using "My.Settings".
I first had the error when adding a new value to the setting section (Project>Properties>Setting section), then run the project and got the same error as Paul.

First workaround is deleting the app.config file, then run the project and works fine.

Now, reading the Paul's workaround, instead of delete the <system.diagnostics> **I comment it** and now all is working.

If I add or remove a value from settings, I didn't have any error, and the values are added (or deleted) from the app.config file and the commented section remains commented.

Hope it's help.

Guillermo

P.S.
I start a new project and don't use any "upgrade tool".

**Comment by ocallesp** [comment]
The PR https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/403807 should handle the issue in `system.diagnostics`

**Comment by RussKie** [comment]
FYI, `system.diagnostics` section is not being recognised because this section no longer being registered. More information can be found here https://github.com/dotnet/runtime/issues/23937#issuecomment-1189343533.
