### ISSUE TITLE
"View Code" command on Form1.resx shows exception to user

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7619]
In Dev17 latest build: 17.0.0 Preview 5.0 [31716.426.main], after right click "View Code" on Form1.resx, following dialog will pop up:

![image](https://user-images.githubusercontent.com/62929087/133748734-8be4b7a4-f527-41b5-81b8-6ecbf00ea7d8.png)

```
System.AggregateException: One or more errors occurred. ---> System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'Microsoft.VisualStudio.Shell.Interop.IVsEditorFactory'.
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.FileDocumentManager.<OpenAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__Action|0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'Microsoft.VisualStudio.Shell.Interop.IVsEditorFactory'.
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.FileDocumentManager.<OpenAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__Action|0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )<---
```

_Originally posted by @Amy-Li03 in https://github.com/dotnet/project-system/issues/5948#issuecomment-921600889_

**Comment by davkean** [comment]
This will be with async open turned on, in this PR: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/347792.

**Comment by tmeschter** [comment]
Re-open as AzDO issue against CPS(?) or Editor(?).

**Comment by tmeschter** [comment]
Migrated to AB#1415363.
