### ISSUE TITLE
App.config is not created when Settings are modified

### ISSUE THREAD

**Issue by RussKie** [dotnet/project-system#7772]
Porting from [AB#1386445](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1386445) for public awareness.

## Summary

I debugged and narrowed the problem down to the following code:

https://github.com/dotnet/project-system/blob/893e4d23143c6c05250878ad820ea4c59fe2d3d1/src/Microsoft.VisualStudio.Editors/SettingsDesigner/AppConfigSerializer.vb#L188-L196

When attempting to get the file with `__PSFFLAGS.PSFF_CreateIfNotExist Or __PSFFLAGS.PSFF_FullPath` fails with the following error:

![image](https://user-images.githubusercontent.com/4403806/141716803-190877f0-f611-4a1a-91fb-2892682d49b1.png)

```
   at EnvDTE80.Solution2.GetProjectItemTemplate(String TemplateName, String Language)
   at Microsoft.VisualStudio.ProjectSystem.VS.CreateFileFromTemplateService.<CreateFileAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.SpecialFileProviders.AbstractSpecialFileProvider.<CreateDefaultFileAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.SpecialFileProviders.AbstractSpecialFileProvider.<GetFileAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<GetSpecialFilePathAsync>d__557.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass508_0.<<GetFile>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously(Func`1 asyncAction)
   at Microsoft.VisualStudio.ProjectSystem.VS.HResult.<>c__DisplayClass37_0.<Invoke>b__0()
   at Microsoft.VisualStudio.ProjectSystem.VS.HResult.Invoke(Func`1 action, IServiceProvider vsShellServiceProvider, IProjectFaultHandlerService projectFaultHandlerService, UnconfiguredProject project)
```

Narrowed down more, this is what's causing the error - the zip file isn't getting found
![image](https://user-images.githubusercontent.com/4403806/141716774-d5b11bae-a485-4b2d-a844-f000f1b4eb23.png)

I can speculate that https://devdiv.visualstudio.com/DevDiv/_git/VS?path=/src/vsproject/Templates/Windows/CSharp/ItemTemplates/AppConfigInternal is either not getting built, or the archive isn't getting packaged...

## Expected Behavior

The app.config is being created whenever settings are changed.

## User Impact

Wide, e.g., https://stackoverflow.com/q/65518159

**Comment by tmeschter** [comment]
@melytc @drewnoakes One to consider as you look at VB work for 17.2.
