### ISSUE TITLE
ArgumentNullException when setting same value across all configuration dimensions

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7977]
## Visual Studio Version

17.2.0 Preview 3.0 [32308.589.main]

## Summary

It's possible to trigger a yellow bar while using project properties.

## Steps to Reproduce

1. Create a new .NET Console App (targeting .NET 6)
2. Open the Project Properties UI
3. Navigate to Build | Errors and warnings | Warning level
4. Click the gear to vary by configuration
5. Click the gear again to use the same value across all configurations

This produces a yellow bar for exception:

```
=====================
15/03/2022 10:50:55
Recoverable
System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: unevaluatedPropertyValue
   at Microsoft.Requires.NotNull[T](T value, String parameterName)
   at Microsoft.VisualStudio.ProjectSystem.Properties.ProjectPropertiesBase.Microsoft.VisualStudio.ProjectSystem.Properties.IContextSpecificProjectProperties.SetPropertyValueInContextAsync(String propertyName, String groupLabel, String unevaluatedPropertyValue, IReadOnlyDictionary`2 dimensionalConditions)
   at Microsoft.VisualStudio.ProjectSystem.PropertyPages.PageProperty.<SetValueAtDataSourceAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.PropertyPages.PageEnumPropertyBase.<SetValueAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.VS.Query.ProjectSetUIPropertyValueActionCore.<ExecuteAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Query.ProjectSetUIPropertyValueActionBase`1.<ReceiveResultAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.QueryDataProviders.ProjectUpdateBatchProvider.ProjectUpdateBatchExecutor.<>c__DisplayClass4_0.<<ExecuteActionsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.ProjectLockService.<ExecuteWithinLockAsync>d__129.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.ProjectLockService.<ExecuteWithinLockAsync>d__129.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.QueryDataProviders.ProjectUpdateBatchProvider.ProjectUpdateBatchExecutor.<ExecuteActionsAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Query.QueryExecution.QueryBatchExecutorBase.<OnRequestProcessFinishedAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Query.QueryExecution.QueryUpdateExecutionManager.<OnRequestProcessFinishedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Query.QueryExecution.ExecutableQueryDataProducer`2.InnerResultReceiver.<Microsoft-VisualStudio-ProjectSystem-Query-QueryExecution-IQueryResultReceiver<TResult>-OnRequestProcessFinishedAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.QueryDataProviders.ProjectQueryDataProvider.ProjectByIdDataProducer.<SendRequestAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.Query.QueryExecution.MergedQueryByIdDataProducer.ProcessManager.<ProcessRequestAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Query.QueryExecution.ExecutableQueryDataProducer`2.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Query.QueryExecution.ServerRuntimeExecutionEngine.<RunDataProducerAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Query.QueryExecution.ServerRuntimeExecutionEngine.<ExecuteExecutableAsync>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.PropertyContext.<>c__DisplayClass37_0.<<SetEvaluatedValue>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: unevaluatedPropertyValue
   at Microsoft.Requires.NotNull[T](T value, String parameterName)
   at Microsoft.VisualStudio.ProjectSystem.Properties.ProjectPropertiesBase.Microsoft.VisualStudio.ProjectSystem.Properties.IContextSpecificProjectProperties.SetPropertyValueInContextAsync(String propertyName, String groupLabel, String unevaluatedPropertyValue, IReadOnlyDictionary`2 dimensionalConditions)
   at Microsoft.VisualStudio.ProjectSystem.PropertyPages.PageProperty.<SetValueAtDataSourceAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.PropertyPages.PageEnumPropertyBase.<SetValueAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.VS.Query.ProjectSetUIPropertyValueActionCore.<ExecuteAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Query.ProjectSetUIPropertyValueActionBase`1.<ReceiveResultAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.QueryDataProviders.ProjectUpdateBatchProvider.ProjectUpdateBatchExecutor.<>c__DisplayClass4_0.<<ExecuteActionsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.ProjectLockService.<ExecuteWithinLockAsync>d__129.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.ProjectLockService.<ExecuteWithinLockAsync>d__129.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.QueryDataProviders.ProjectUpdateBatchProvider.ProjectUpdateBatchExecutor.<ExecuteActionsAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Query.QueryExecution.QueryBatchExecutorBase.<OnRequestProcessFinishedAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Query.QueryExecution.QueryUpdateExecutionManager.<OnRequestProcessFinishedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Query.QueryExecution.ExecutableQueryDataProducer`2.InnerResultReceiver.<Microsoft-VisualStudio-ProjectSystem-Query-QueryExecution-IQueryResultReceiver<TResult>-OnRequestProcessFinishedAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.QueryDataProviders.ProjectQueryDataProvider.ProjectByIdDataProducer.<SendRequestAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.Query.QueryExecution.MergedQueryByIdDataProducer.ProcessManager.<ProcessRequestAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Query.QueryExecution.ExecutableQueryDataProducer`2.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Query.QueryExecution.ServerRuntimeExecutionEngine.<RunDataProducerAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Query.QueryExecution.ServerRuntimeExecutionEngine.<ExecuteExecutableAsync>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.PropertyContext.<>c__DisplayClass37_0.<<SetEvaluatedValue>b__0>d.MoveNext()<---
```

**Comment by tmeschter** [comment]
To clarify my last comment: the UI initially sees the value of the property as `null` even though it is actually `6`. But `6` doesn't map to one of the admissible values, so the backend reports the value as `null`. Later, the UI tries to reset the value to be the same across all configurations, and it uses the value it knows about--`null`. However, the data source does not support `null` values (if you want to remove a value you should delete the property instead), and throws.

So the root issue here is that the set of admissible values does not line up with what is actually supported.

Further, in many cases (including that of a new .NET 5 or .NET 6 project) the `WarningLevel` cannot be meaningfully set by the user because the SDK will always override it. As such, just adding additional admissible values won't help the user much--they'll be able to go through the repro steps in this issue without error, but they won't meaningfully change the value.

I think the correct solution is to both update the set of admissible values _and_ hide the WarningLevel when the value will be overridden. In that case, maybe we show a read-only version.

**Comment by drewnoakes** [comment]
@tmeschter that makes sense, although the user could still add an unsupported value in the project file and trigger this.

As for hiding `WarningLevel` when it is overridden, we just need to identify when that occurs and capture that in a visibility condition on the property. We can add another read-only property with the inverse condition too.

**Comment by tmeschter** [comment]
@drewnoakes I want to make sure we're fully comfortable with the idea that `null` is valid when setting an evaluated or unevaluated value, and that it means "delete the property". I think that's reasonable and probably the right way to go, but once we make that decision it is going to be hard to change later.

> As for hiding `WarningLevel` when it is overridden, we just need to identify when that occurs and capture that in a visibility condition on the property. We can add another read-only property with the inverse condition too.

I should have a PR out today that does that. I had to reverse engineer the SDK targets, but the condition turns out to be reasonably straightforward.

**Comment by drewnoakes** [comment]
I think having a separate API for "deleting" a property would be less surprising. I envisage this gesture being "reset to default", as delete implies something that imported files might not allow.

Today we allow a null evaluated value, but never a null unevaluated value. The MSBuild view of unevaluated properties is that they're always non-null. What determines when a property's evaluated value might be null?

Is the idea of using null to reset a property based on convenience of implementation, or is there some sense behind null that I can't see?
