### ISSUE TITLE
The "ValidateExecutableReferences" task failed unexpectedly

### ISSUE THREAD

**Issue by Varorbc** [dotnet/project-system#8156]
## Visual Studio Version

17.3 preview1

## Summary

The "ValidateExecutableReferences" task failed unexpectedly

## Steps to Reproduce

global.json

```json
{
  "sdk": {
    "version": "5.0.100",
    "rollForward": "latestMinor"
  }
}
```

ClassLibrary1

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

</Project>
```

ConsoleApp1

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClassLibrary1\ClassLibrary1.csproj" />
  </ItemGroup>

</Project>
```

## Expected Behavior

project loaded successfully

## Actual Behavior

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.NET.Build.Tasks.ValidateExecutableReferences.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

**Comment by drewnoakes** [comment]
Do you have a repro? What steps led up to this? If you could share a project that caused this, it would be helpful.

**Comment by Varorbc** [comment]
@drewnoakes detailed description has been added

**Comment by drewnoakes** [comment]
What is the output of `dotnet --info` on the machine that hit this error?

**Comment by drewnoakes** [comment]
Are you building on the command line or in VS?

**Comment by Varorbc** [comment]
build successfuly on the command line,but build error in vs

```
.NET SDK (反映任何 global.json):
 Version:   5.0.406
 Commit:    3a48fd6fe5

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.406\

Host:
  Version:      7.0.0-preview.5.22226.6
  Architecture: x64
  Commit:       c10154087e

.NET SDKs installed:
  5.0.406 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]
  7.0.100-preview.5.22227.8 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-preview.5.22227.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-preview.5.22226.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-preview.5.22226.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

**Comment by drewnoakes** [comment]
I don't believe the project system is involved here. Moving to MSBuild.

**Comment by BobSilent** [comment]
In `C:\Program Files\dotnet\sdk\5.0.408\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets`

Line 989
```msbuild
  <Target Name="ValidateExecutableReferences"
          AfterTargets="_GetProjectReferenceTargetFrameworkProperties"
          Condition="'$(ValidateExecutableReferencesMatchSelfContained)' != 'false'">

    <ValidateExecutableReferences
      SelfContained="$(SelfContained)"
      IsExecutable="$(_IsExecutable)"
      ReferencedProjects="@(_MSBuildProjectReferenceExistent)"
      />
    
  </Target>
```

The ReferencedProjects are looking different when building from `dotnet build` and within VS

With `dotnet build` the  `ReferencedProjects` have for each project the `AdditionalPropertiesFromProject` looking like this
```
NearestTargetFramework=net5.0
AdditionalPropertiesFromProject=<AdditionalProjectProperties>
                       <net5.0>
                         <SelfContained></SelfContained>
                         <_IsExecutable></_IsExecutable>
                         <ShouldBeValidatedAsExecutableReference></ShouldBeValidatedAsExecutableReference>
                       </net5.0>
```

and from within the VS build the `AdditionalPropertiesFromProject` looks like that
```
NearestTargetFramework=net5.0
AdditionalPropertiesFromProject=<AdditionalProjectProperties>
      <TargetFramework Name="net5.0">
        <SelfContained></SelfContained>
        <_IsExecutable></_IsExecutable>
        <ShouldBeValidatedAsExecutableReference></ShouldBeValidatedAsExecutableReference>
      </TargetFramework>
```

the `Microsoft.NET.Build.Tasks.ValidateExecutableReferences` from `Microsoft.NET.Build.Tasks.dll`
tries to find an XML Element with the name  of the metadata value `NearestTargetFramework` which is `net5.0`
and this cannot be found as in VS the XML Element is named `<TargetFramework Name="net5.0">`

```csharp
string metadata = val.GetMetadata("NearestTargetFramework");
if (string.IsNullOrEmpty(metadata) || !val.HasMetadataValue("AdditionalPropertiesFromProject"))

	continue;
}
XElement xElement = XElement.Parse(val.GetMetadata("AdditionalPropertiesFromProject"));
XElement xElement2 = xElement.Element(metadata);
//                           ^^^^^^^^^^^^^^^^^^^ NullReferenceException
```

**Comment by kvenkatrajan** [comment]
This has been routed to an internal team investigating the issue. Closing this ticket
