### ISSUE TITLE
Unable to save launch settings using ILaunchSettingsProvider2.UpdateAndSaveSettingsAsync

### ISSUE THREAD

**Issue by ravipal** [dotnet/project-system#8160]
## Visual Studio Version
Version 17.3.0 Preview 2.0 [32509.446.main]

## Summary

When trying to save a launch settings using `ILaunchSettingsProvider2.UpdateAndSaveSettingsAsync()`, it throws the following error.

> Unsupported type: System.Collections.Generic.Dictionary`2[System.String,System.String]. Use the JsonSerializer class to get the object's JSON representation. Path 'profiles['Docker Compose']'. Note that the same code works until the previous preview version of VS.

## Steps to Reproduce

1. Ensure the 'Azure Development' workload is installed and [Docker Desktop for Windows](https://docs.docker.com/desktop/windows/install/) is installed
2. Create a console core (.Net 6.0) application.
3. Right click on the project and Add -> Container Orchestrator support ... -> and choose 'Docker Compose' -> Linux as target OS.
4. Right click on the docker-compose project and open 'Manage Docker Compose Launch Settings'. This will open a new dialog and click save.

## Expected Behavior

A launchSettings.json should be created under the docker-compose project

## Actual Behavior

throw the following error

![image](https://user-images.githubusercontent.com/1775825/167906152-15f9c0f1-42f6-447b-92eb-3b0a670b0d2f.png)

```
Unsupported type: System.Collections.Generic.Dictionary'2[System.String,System.String]. Use the JsonSerializer class to get the object's JSON representation. Path 'profiles['Docker Compose']'
   at Newtonsoft.Json.JsonWriter.WriteValue(JsonWriter writer, PrimitiveTypeCode typeCode, Object value)
   at Newtonsoft.Json.JsonWriter.WriteValue(Object value)
   at Newtonsoft.Json.JsonTextWriter.WriteValue(Object value)
   at Microsoft.VisualStudio.ProjectSystem.Debug.LaunchSettingsJsonEncoding.<ToJson>g__WriteLaunchProfile|8_2(ILaunchProfile profile, <>c__DisplayClass8_0& )
   at Microsoft.VisualStudio.ProjectSystem.Debug.LaunchSettingsJsonEncoding.<ToJson>g__WriteSettings|8_0(<>c__DisplayClass8_0& )
   at Microsoft.VisualStudio.ProjectSystem.Debug.LaunchSettingsJsonEncoding.ToJson(IEnumerable`1 profiles, IEnumerable`1 globalSettings)
   at Microsoft.VisualStudio.ProjectSystem.Debug.LaunchSettingsProvider.<SaveSettingsToDiskAsync>d__77.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Debug.LaunchSettingsProvider.<UpdateAndSaveSettingsInternalAsync>d__86.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.Tasks.SequentialTaskExecutor.<>c__DisplayClass8_0.<<ExecuteTask>b__0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.Tasks.SequentialTaskExecutor.<>c__DisplayClass8_0.<<ExecuteTask>g__JoinTaskAsync|1>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Docker.Compose.UI.LaunchSettings.LaunchSettingsViewModel.<SaveLaunchSettingsAsync>d__57.MoveNext() in C:\repo\AT-Docker\src\Docker\Microsoft.VisualStudio.Docker.Compose\UI\LaunchSettings\LaunchSettingsViewModel.cs:line 406
```

## User Impact

User is blocked from creating and manipulating [subset of services](https://docs.microsoft.com/en-us/visualstudio/containers/launch-profiles?view=vs-2022).

**Comment by drewnoakes** [comment]
@ravipal thanks for the clear and actionable bug report.

I broke this with https://github.com/dotnet/project-system/commit/3b523af79a4eb6a5eecaf5794407c90f1ea2168f (which was part of restoring the environment variables grid/editor). The fix should be straightforward, especially with the repro steps given here.

**Comment by drewnoakes** [comment]
The exception's being raised here: https://github.com/dotnet/project-system/blob/5f6c4e83666217a94bc14885ba6138ba68fc9e51/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsJsonEncoding.cs#L168
