### ISSUE TITLE
Crash when renaming a symbol & file in a shared project

### ISSUE THREAD

**Issue by lorcanmooney** [dotnet/project-system#8306]
## Visual Studio Version
17.2.5

## Summary
Renaming a symbol & file is broken in shared projects.

## Steps to Reproduce

1. Create a shared project and add a referenced to it from a non-shared project (without this, step 3 won't be available)
2. Initiate an inline rename for a class in the shared project
3. Ensure "Rename symbols file" is selected, and apply the rename

## Expected Behavior
Both the symbol and file are successfully renamed.

## Actual Behavior
1. The declaration is renamed.
2. References are not renamed.
3. A new file with the new name is created.
4. The old file with the old name remains, but is excluded from the project.
5. A yellow bar with "Error performing rename", and the following stack trace:
```
System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.
   at Microsoft.VisualStudio.ProjectSystem.Designers.UnattachedProjectTreeNode.Find(IntPtr nodeId)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectTree.Find(IntPtr nodeId)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.GetProjectTreeById(IntPtr nodeIdentity)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.SimpleItemNode.get_IsBrowseObjectHidden()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.SimpleItemNode.GetNodeProperties()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProperties.Create(Object parent,SimpleHierarchyNode hierarchyNode)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.Extensions.ProjectItemExtensions.TryGetFullPath(ProjectItem item,String& fullPath)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyDocumentInfoChanged(DocumentId documentId,DocumentInfo updatedInfo)
   at Microsoft.CodeAnalysis.Workspace.ApplyChangedDocument(ProjectChanges projectChanges,DocumentId documentId)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.ApplyRename(Solution newSolution,IUIThreadOperationContext operationContext)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.CommitCore(IUIThreadOperationContext operationContext,Boolean previewChanges)
   at Microsoft.VisualStudio.Editor.Implementation.VSUIThreadOperationExecutor.Execute(UIThreadOperationExecutionOptions executionOptions,Action`1 action)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.CommitWorker(Boolean previewChanges)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.RenameCommandHandler.Commit(InlineRenameSession activeSession,ITextView textView)
```

## User Impact
This one was _incredibly_ confusing when I first hit it. If you initiate the rename at the class declaration, it looks like the rename failed completely since there are no visible changes, and yet you now have errors in other projects telling you the old name no longer exists. In actual fact, the file you're still looking at is no longer part of the project (and might be hidden in the solution explorer if "Show all files" is not enabled).

**Comment by lorcanmooney** [comment]
Oops, this looks like it's probably a duplicate of #6041.
