### ISSUE TITLE
Fix and re-enable integration test BasicSquiggles_NetCore.xml

### ISSUE THREAD

**Issue by mavasani** [dotnet/project-system#850]
Test fails with the below log:

```

VS main window was brought to foreground.
Started new VS and Apex Initialized
Begin Waiting for Apex Communication
	Executing action [11/30/2016 1:20:04 PM] AddProject
	Executing action [11/30/2016 1:20:19 PM] AddItem
 Scenario: Verify Syntax Errors squiggles are showing up
	Executing action [11/30/2016 1:20:24 PM] SetEditorText
	Executing action [11/30/2016 1:20:25 PM] VerifyErrorTags
--------------------------------
System.Runtime.Remoting.RemotingException: Failed to read from an IPC Port: The pipe has been ended.


Server stack trace: 
   at System.Runtime.Remoting.Channels.Ipc.IpcPort.Read(Byte[] data, Int32 offset, Int32 length)
   at System.Runtime.Remoting.Channels.Ipc.PipeStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Runtime.Remoting.Channels.SocketHandler.ReadFromSocket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.SocketHandler.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.SocketHandler.ReadAndMatchFourBytes(Byte[] buffer)
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadAndMatchPreamble()
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadVersionAndOperation(UInt16& operation)
   at System.Runtime.Remoting.Channels.Ipc.IpcClientHandler.ReadHeaders()
   at System.Runtime.Remoting.Channels.Ipc.IpcClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Roslyn.VSHosting.Test.InProcessAPI.InvokeOnUI(RemoteAction action, Object[] args)
   at Roslyn.VSHosting.Test.VerifyTagsAction`2.ExecuteHelper(TagSpanDetails tagSpanDetails, Int32 expectedCount) in c:\roslyn-internal\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\VerifyAdornmentsAction.cs:line 56
   at Roslyn.VSHosting.Test.VerifyTagsAction`2.Execute(TaoEngine engine) in c:\roslyn-internal\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\VerifyAdornmentsAction.cs:line 44
   at Tao.Engine.DebuggableActionExecutor.Execute()
   at Tao.Engine.DefaultActionExecutor.Execute()
================================
```

**Comment by jmarolf** [comment]
resolved with https://github.com/dotnet/project-system/pull/2169
