### ISSUE TITLE
Enable integration test CrossLanguage_NetCore.xml 

### ISSUE THREAD

**Issue by mavasani** [dotnet/project-system#853]
Its currently failing with:

```
VS main window was brought to foreground.
Started new VS and Apex Initialized
Begin Waiting for Apex Communication
	Executing action [11/30/2016 2:20:34 PM] AddProject
	Executing action [11/30/2016 2:20:51 PM] AddProject
 Scenario: Test cross-language project reference
	Executing action [11/30/2016 2:20:54 PM] AddProjectReference
--------------------------------
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Roslyn.VSHosting.Test.RoslynInProcessAPI.<>c__DisplayClass90_0.<AddProjectReference>b__0() in c:\roslyn-internal\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\Utilities\RoslynInProcessAPI.cs:line 592
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at Microsoft.Test.Apex.Hosts.Services.UIThreadInvokerHelper.InvokeByAction(Object[] values)
   at Microsoft.Test.Apex.VisualStudio.Services.Remote.VsUIThreadInvokerService.DispatcherInvocationWrapper(RemoteAction action, Object[] arguments)
================================
```

**Comment by srivatsn** [comment]
Doesn't sound important. Not needed at this time.
