### ISSUE TITLE
Exception in FUTDC dataflow when DisableFastUpToDateCheck is true

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#8721]
Initially reported in https://developercommunity.visualstudio.com/t/Project-Load-Error:-Project-system-data-/10229655

## Visual Studio Version

17.5p2

## Summary

```
System.AggregateException: Project system data flow 'UpToDateCheckConfiguredInputDataSource: 20088938' closed because of an exception.
Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.ProjectSystem.UpToDate.CopyItemAggregator.SetProjectData(ProjectCopyData projectCopyData)
   at Microsoft.VisualStudio.ProjectSystem.UpToDate.UpToDateCheckImplicitConfiguredInputDataSource.<>c__DisplayClass8_0.<<LinkExternalInput>g__TransformAsync|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim`2.TransformBlockSlimAsync.<ProcessInputAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.<ProcessInputQueueAsync>d__5.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.ProjectSystem.UpToDate.CopyItemAggregator.SetProjectData(ProjectCopyData projectCopyData)
   at Microsoft.VisualStudio.ProjectSystem.UpToDate.UpToDateCheckImplicitConfiguredInputDataSource.<>c__DisplayClass8_0.<<LinkExternalInput>g__TransformAsync|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim`2.TransformBlockSlimAsync.<ProcessInputAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.<ProcessInputQueueAsync>d__5.MoveNext()<---
```

## Steps to Reproduce

There is a project attached to the feedback ticket, if needed.

**Comment by drewnoakes** [comment]
The bug occurs when `<DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>` is specified either in the project or a package it references. In the customer's case, they were referencing `MonoGame.Content.Builder.Task` which sets the property in its `MonoGame.Content.Builder.Task.props` file.

I will prepare a fix for 17.5 preview 3.
