### ISSUE TITLE
Multliline string editor should tolerate missing TextWrapping metadata

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#9082]
```
System.Windows.Data Warning: 17 : Cannot get 'Item[]' value (type 'String') from 'EditorMetadata' (type 'ImmutableDictionary`2'). BindingExpression:Path=Parent.EditorMetadata[TextWrapping]; DataItem='PropertyValueViewModel' (HashCode=8215334); target element is 'TextBox' (Name=''); target property is 'TextWrapping' (type 'TextWrapping') TargetInvocationException:'System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Collections.Generic.KeyNotFoundException: The given key 'TextWrapping' was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at MS.Internal.Data.PropertyPathWorker.GetValue(Object item, Int32 level)
   at MS.Internal.Data.PropertyPathWorker.RawValue(Int32 k)'
```

Currently our WPF binding dereferences the item, assuming it's always present:

```
TextWrapping="{Binding Parent.EditorMetadata[TextWrapping], FallbackValue='NoWrap', TargetNullValue='NoWrap', Converter={x:Static local:Converters.TextWrappingStringToTextWrapping}}"
```

The `EditorMetadata` property is a `ImmutableDictionary<string, string>`, and throws a `KeyNotFoundException` when we attempt to look up a value that's not present.

We should make the binding tolerate the case that the value is missing.

**Comment by drewnoakes** [comment]
@adamint did your recent CPS PR address this issue?
