### ISSUE TITLE
Multiple errors and missing project items when a "\\?\" path is used

### ISSUE THREAD

**Issue by lorcanmooney** [dotnet/project-system#9180]
## Visual Studio Version
17.6.4

## Summary
In a `.csproj` file, item paths with a `\\?\` prefix cause project load errors, and some variations are inaccessible from the solution explorer.

The former seems to be caused by `ProjectDirectoryGlobTreesSnapshotProvider.GetGlobRoot`, which is treating the `?` in the prefix as a glob pattern.

## Steps to Reproduce

```xml
<ItemGroup>
  <None Include="\\?\C:\foo.txt" Link="foo.txt" />
</ItemGroup>
```

or

```xml
<ItemGroup>
  <None Include="\\?\Volume{7CB2204C-C73F-4052-8537-A60CC342C989}\foo.txt" Link="foo.txt" />
</ItemGroup>
```

## Expected Behavior
No error messages, and both items should be visible and accessible from the solution explorer.

## Actual Behavior
- Multiple errors are shown at the top of the IDE:
  - > Visual Studio ran into an unexpected problem. Please save your work and restart Visual Studio.
  - > Visual Studio ran into an unexpected problem with one or more projects. You may need to reload affected projects or the solution to prevent further problems.

- When a volume GUID is used for the path, the item is not shown in the solution explorer.

## User Impact
Spurious error messages, and some items may not be shown in the soultion explorer. The IDE doesn't crash and remains usable.

## Log File
```
=====================
NotRecoverable
System.ArgumentException: 'caption' cannot be an empty string ("") or start with the null character.
Parameter name: caption
   at Microsoft.Requires.NotNullOrEmpty(String value, String parameterName)
   at Microsoft.VisualStudio.ProjectSystem.Designers.CoreProjectTreeFactory.NewTree(String caption, String filePath, IRule browseObjectProperties, ProjectImageMoniker icon, ProjectImageMoniker expandedIcon, Boolean visible, Nullable`1 flags, IEnumerable`1 children, Int32 displayOrder)
   at Microsoft.VisualStudio.ProjectSystem.Designers.CoreProjectTreeFactory.NewTree(String caption, String filePath, IRule browseObjectProperties, ProjectImageMoniker icon, ProjectImageMoniker expandedIcon, Boolean visible, Nullable`1 flags, IEnumerable`1 children)
   at Microsoft.VisualStudio.ProjectSystem.Designers.CoreDirectoryTreeProvider.GenerateOriginalTreeAsync(IProjectVersionedValue`1 nullTree, ConfiguredProjectExports configuredProjectExports, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.ProjectTreeProviderBase.TreeUpdateSubmission.<UpdateTree>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.CoreProjectTreeProviderBase.<>c__DisplayClass76_1.<<Initialize>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.CoreProjectTreeProviderBase.<>c__DisplayClass78_0.<<SubmitTreeUpdateCoreAsync>g__WaitOnTask|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Designers.CoreDirectoryTreeProvider.<<Initialize>b__66_0>d.MoveNext()
===================
LimitedFunctionality
System.AggregateException: One or more errors occurred.
---> (Inner Exception #0) System.ArgumentException: 'caption' cannot be an empty string ("") or start with the null character.
Parameter name: caption
   at Microsoft.VisualStudio.ProjectSystem.CoreProjectTreeProviderBase.<>c__DisplayClass76_0.<Initialize>b__1(Tuple`2 t)
   at Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim`2.TransformBlockSlimSync.ProcessInputAsync(TInput input)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.<ProcessInputQueueAsync>d__5.MoveNext()
<--- (Inner Exception #0) 
===================
```

**Comment by drewnoakes** [comment]
@lorcanmooney this issue relates to CPS, the internal component upon which the dotnet/project-system is built. To that end, the issue should be tracked by them internally. Would it be too much trouble to create a feedback ticket with the above details in it? If you are able to do that, and link it here, I'll ensure it's routed to the correct people internally.

**Comment by lorcanmooney** [comment]
Done: https://developercommunity.visualstudio.com/t/Multiple-errors-and-missing-project-item/10421054

**Comment by drewnoakes** [comment]
Thank you @lorcanmooney, I've routed it internally.
