### ISSUE TITLE
Renaming a project won't load project properties UI.

### ISSUE THREAD

**Issue by melytc** [dotnet/project-system#9253]
## Visual Studio Version
VS 2022 Version 17.8.0 Preview 3.0 [34105.243.main]

## Summary
After renaming a project, I was unable to open the Project Properties UI. See video below:

![rename-project-bug](https://github.com/dotnet/project-system/assets/8518253/dfb0bf81-f252-4a90-aa9e-dd1a457716d9)

## Steps to Reproduce

1. Create a class library.
2. Open the Project Properties UI. It should load as expected. Close it.
3. Rename the project.
4. Open the Project Properties UI.

## Expected Behavior
It should load as expected.

## Actual Behavior
Shows an exception message, saying it couldn't find the project GUID:
```
Microsoft.Assumes+InternalErrorException: Project with GUID 34d15c1e-f825-402b-8c40-6718ab1894e1 not found.
   at Microsoft.Assumes.Fail(String message)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.ProjectPropertyDataAccess.Observer.<HandleDataAsync>g__ProcessInitialData|14_1(<>c__DisplayClass14_0& )
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.ProjectPropertyDataAccess.Observer.<InitializeAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.ProjectPropertyDataAccess.Observer.<CreateAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.ProjectPropertiesEditor.<>c__DisplayClass0_0.<<-ctor>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.AsyncLoadContent.<>c__DisplayClass0_0.<<Initialize>b__0>d.MoveNext()
```

**Comment by melytc** [comment]
Note: closing the solution and reopening it will keep showing the error; however, closing VS and reopening the solution will make it go away.

**Comment by adamint** [comment]
@melytc this is a CPS codepath, closing and reopening as an ado ticket

**Comment by drewnoakes** [comment]
@adamint it's true that this code is in CPS, but our team owns that code and has historically tracked work items for it on GitHub. If it turns out to be in code we don't own (e.g. the Project Query API) then moving to AzDO makes sense.
